### ISSUE TITLE
Captcha is broken

### ISSUE THREAD

**Issue by StephanFS** [K1rakishou/Kuroba-Experimental#1001]
Trying to post anything on 4chan doesn't work after I input the right captcha. Tried several times, even with the Solver turned on, but it still won't accept the captcha.

**Comment by K1rakishou** [comment]
Try this apk https://github.com/K1rakishou/Kuroba-Experimental/issues/996#issuecomment-1914685399

**Comment by K1rakishou** [comment]
Already fixed.
