### ISSUE TITLE
some images dont load  "failed to download image"

### ISSUE THREAD

**Issue by shultays** [K1rakishou/Kuroba-Experimental#1002]
I am not sure what is special about those images but the real image does not load and it shows thumbnail

![Screenshot_20240131_120045](https://github.com/K1rakishou/Kuroba-Experimental/assets/3469314/1235e413-158d-4ffe-b3b0-4e51be067e53)

**Comment by K1rakishou** [comment]
Settings -> sites -> 4chan -> concurrent chunked image downloading -> set to 1

**Comment by shultays** [comment]
Thanks, that solves the issue
