### ISSUE TITLE
Posting broken, captchas will not load

### ISSUE THREAD

**Issue by bungholemaster** [K1rakishou/Kuroba-Experimental#1003]
![Screenshot_20240131_214552](https://github.com/K1rakishou/Kuroba-Experimental/assets/16147700/fe5e07f8-cbd8-4408-96ce-0d41fb9ba5c2)
I get this error whenever I try to load a captcha, which means I cannot post at all

**Comment by K1rakishou** [comment]
Already fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/271bd104eb1c3be2bfcca76949e65de6f73f6a50
Will be released some time at the weekends.
