### ISSUE TITLE
fallback for chunked download

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#1010]
For whatever reason when you have set KurobaEx to use multiple chunks to download files, some images/webms refuse to load and it throws up an error.
This only happens to a maximum of 10% of files, but the files that refuse to load in multiple chunks will never load.

There should be a check and fallback for these files. If the error would pop up, KurobaEx should fallback to a single chunk download for that specific file.

![Screenshot_20240203-232224](https://github.com/K1rakishou/Kuroba-Experimental/assets/17074394/5e2e590c-c47f-40c3-bb59-d265028e1698)

**Comment by K1rakishou** [comment]
Can you give me some example posts where when you open an image it gives this error?

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/a6f94e6f81f32e4285c3dc949c535d3a2056bad1
Check the beta.
