### ISSUE TITLE
Java.lang.NullPointerException Error

### ISSUE THREAD

**Issue by BeautysBeast1445** [K1rakishou/Kuroba-Experimental#1012]
Java.lang.NullPointerException error when I try to load captcha.
I tried fresh updated install of KurobaEx from Fdroid and fresh install of chan4CaptchaSolver.

![Screenshot_20240206_001155](https://github.com/K1rakishou/Kuroba-Experimental/assets/159104660/9c23d81e-d106-45b9-a071-5e289d055f13)

**Comment by K1rakishou** [comment]
Use Beta/Stable builds. It's already fixed. Fdroid's updates are released with a ~week delay compared to beta/stable.
