### ISSUE TITLE
Unable to post

### ISSUE THREAD

**Issue by reportthings** [K1rakishou/Kuroba-Experimental#1023]
Unable to find your post '4chan/g/99084450/99089173' on the server in the same thread.
This means that you have made a mistake in your captcha and 4chan completely discarded your post.
Good news is that your post won't be discarded locally so you can try again with a new captcha.

Keep receiving this error.  100% sure I am typing the captcha accurately

https://github.com/K1rakishou/Kuroba-Experimental/assets/85461551/7ced0037-cd84-4cbb-9b8e-062ad3060f7d

**Comment by reportthings** [comment]
Also getting 60 second rate limit upon trying to load the first captcha after a while of not attempting to post.  10-15 minutes between attempts gives a rate limit

**Comment by K1rakishou** [comment]
What version? Try disabling this thing.

**Comment by reportthings** [comment]
Beta V1.3.33.12. I had to disable that option to enable cloudflare check apparently but couldn't pass it.  So I reset cloudflare + captcha cookies and got it to work.  Still get 60 second rate limit after cloudflare check, not sure why that's happening.  Closing since it's working
