### ISSUE TITLE
Request support for soyjak.party

### ISSUE THREAD

**Issue by NoName-5c** [K1rakishou/Kuroba-Experimental#1025]

**Comment by Shtrausberg** [comment]
Support is bugged, soyjak.party site shows no boards available for reading.
![Screenshot_2024-04-26-11-29-17-876_com github k1rakishou chan beta](https://github.com/K1rakishou/Kuroba-Experimental/assets/168160045/85493f70-05b3-4453-aa7f-103c9a7e3135)
