### ISSUE TITLE
Unique Poster Data no longer shown on 4chan

### ISSUE THREAD

**Issue by tidux** [K1rakishou/Kuroba-Experimental#1032]
![Screenshot_20240311_080611](https://github.com/K1rakishou/Kuroba-Experimental/assets/1330562/e85911df-b5ca-4d32-a36b-d25a661dbe6a)

This is exhibiting even on boards like /biz/ that track user IDs visibly.  API change?

**Comment by K1rakishou** [comment]
https://boards.4chan.org/g/thread/99432488

**Comment by tidux** [comment]
Of course.  Fucking gookmoot.

**Comment by tidux** [comment]
Oh well.
