### ISSUE TITLE
kuroba is not responding 

### ISSUE THREAD

**Issue by lickafrog** [K1rakishou/Kuroba-Experimental#1034]
It hands like that and nothing you can you until you clear all data 

Happens the second time 

![Screenshot_2024-03-12-11-33-00-758_com github k1rakishou chan beta](https://github.com/K1rakishou/Kuroba-Experimental/assets/130896496/a9f04b31-7f70-42ba-b721-b7a3af104ebc)

![Screenshot_2024-03-12-11-36-38-995_com android settings](https://github.com/K1rakishou/Kuroba-Experimental/assets/130896496/dd96314c-4862-42ae-a1fe-2bd34e395258)

**Comment by K1rakishou** [comment]
You are on the latest beta, right?

**Comment by lickafrog** [comment]
Yes

**Comment by lickafrog** [comment]
It was the issues with updating. I download the latest version and now it's fine
