### ISSUE TITLE
Workflow for downloading threads is confusing 

### ISSUE THREAD

**Issue by trgreiss** [K1rakishou/Kuroba-Experimental#1039]
The workflow (as I see it) for downloading a thread is Bookmark > navigate to bookmarks pane > long press to select > Download.

Am I missing something, or does this seem unnecessarily complicated? It seems like there should be a download button directly from the board navigator.

**Comment by K1rakishou** [comment]
Open a thread -> three dot menu -> start thread download

**Comment by trgreiss** [comment]
Thanks!
