### ISSUE TITLE
Loading fails for image with only black-white colors

### ISSUE THREAD

**Issue by hafizhmakmur** [K1rakishou/Kuroba-Experimental#1042]
Almost whenever an image has only black and white colors and low details, the loading fails because of "HttpCodeException" (another issue: I can never see full error message) like this.

![Screenshot_20240321_045845](https://github.com/K1rakishou/Kuroba-Experimental/assets/14178101/d49c83ab-02da-4bd4-9016-1ec9d4fc1de8)

It works fine when I open the image in external browser.

**Comment by K1rakishou** [comment]
Settings -> Sites -> 4chan -> `Concurrent chunked downloading` -> set to 1 chunk

**Comment by hafizhmakmur** [comment]
Looks good so far. Thank you :D 

Btw still, how do I see full error messages, @K1rakishou? It keeps cutting before the crucial part.

**Comment by K1rakishou** [comment]
Google decided that having more than two lines of text in a toast is too much for users. The only way to fix it is to implement my own toasts.
