### ISSUE TITLE
Japanese input in new reply interface

### ISSUE THREAD

**Issue by kancas55** [K1rakishou/Kuroba-Experimental#1067]
Using the newest beta version it is not possible to input japanese text with an IME, it takes each letter as inputted before the IME converts it to kana or kanji, so if I input "i" I can get "い" but if I input "mi" I get "mい" instead of "み"

**Comment by kancas55** [comment]
![scrcpy_2024-04-28_12-48-40](https://github.com/K1rakishou/Kuroba-Experimental/assets/165630040/c1e72ead-17e0-403a-a294-b0688dcc1d32)

**Comment by K1rakishou** [comment]
They fixed it in Jetpack Compose in the latest beta so it will be fixed with the next beta release.
