### ISSUE TITLE
After several hours of working properly after installation, the app returns me to homescreen after launching.

### ISSUE THREAD

**Issue by SamuelBucher** [K1rakishou/Kuroba-Experimental#107]
It is worth noting that the app doesn't close afterwards. I can try to view it, but it still returns me to homescreen. Re-installing and rebooting doesn't help.

**Comment by K1rakishou** [comment]
Would be nice to see some logs. But if the app crashes right on start then you will have to use ADB to get them. 

So, what you need to do is:
- Download ADB (https://developer.android.com/studio/releases/platform-tools)
- Open terminal and run "adb" to make sure it works, you will see something like this:

![image](https://user-images.githubusercontent.com/10332458/93074597-46fc8f80-f68d-11ea-870f-a6f702f90b32.png)

- Run "adb shell"
- Run "logcat".
- Open the app so it can crash.
- Get the crash log and post it here.

The crash log should look like this:

![image](https://user-images.githubusercontent.com/10332458/93075261-3993d500-f68e-11ea-8cc6-6d7388a4fd31.png)

Or you can just post everything.

**Comment by SamuelBucher** [comment]
Doesn't work. All .exe files in the folder crash on start and "adb" isn't a command.
![Screenshot 2020-09-15 183500](https://user-images.githubusercontent.com/56469863/93224618-590c2a00-f782-11ea-8eff-3e11c1ccf326.png)

**Comment by K1rakishou** [comment]
>All .exe files in the folder crash on start

They do not crash on start, they are just console programs without GUI.

>and "adb" isn't a command.

Navigate into the directory via the terminal and then enter "adb.exe" or drag the adb.exe onto the terminal and hit enter.

**Comment by SamuelBucher** [comment]
What next?

**Comment by SamuelBucher** [comment]
How do I run adb shell and logcat?

**Comment by K1rakishou** [comment]
Open terminal, navigate to where adb.exe is located, and then run it.

**Comment by SamuelBucher** [comment]
Yes, I did that. It works. But how do I run adb shell and logcat?

**Comment by K1rakishou** [comment]
Just like you did with adb. But instead of just entering "adb" enter "adb shell" and after that "logcat"

**Comment by SamuelBucher** [comment]
![Screenshot 2020-09-16 131949](https://user-images.githubusercontent.com/56469863/93318122-5c092800-f81f-11ea-8b67-e724f7c3fa37.png)
I managed to run adb shell, but logcat still doesn't work.

**Comment by K1rakishou** [comment]
>no devices/emulators found

You need to connect your device first. And you will probably have to enable "USB debugging" but I'm not sure here. If it works without it then it's fine.

**Comment by SamuelBucher** [comment]
![Screenshot 2020-09-16 141831](https://user-images.githubusercontent.com/56469863/93324881-8828a700-f827-11ea-9153-4749e4799922.png)
I connected my phone, but how do I make the program recognise it?

**Comment by K1rakishou** [comment]
Well, apparently you need to turn on USB debugging - https://developer.android.com/studio/debug/dev-options#enable

**Comment by SamuelBucher** [comment]
OK, I think I did it.
![Screenshot 2020-09-16 143950](https://user-images.githubusercontent.com/56469863/93326845-87454480-f82a-11ea-8571-e1f77f2057f7.png)

**Comment by K1rakishou** [comment]
Nice, thanks. Alright, this looks like a known bug that's already been fixed but not released yet. This is because of PHONE layout. You can avoid it by switching to SLIDE layout instead of PHONE for now until the fix is released (It's in the "Appearance" settings).

**Comment by SamuelBucher** [comment]
That's great, I don't like the phone layout anyway. However, I can't get to settings since the app crashes on start even after reinstalling.

**Comment by K1rakishou** [comment]
Well you will have to reset the application data to do that.

**Comment by SamuelBucher** [comment]
How do I do that?

**Comment by K1rakishou** [comment]
It's in the app's settings. There should be "Storage and cache" setting (or something like that, depends on your phone) and then there should be a "Clear storage" button. Or you can just delete it completely and install again. 

![qemu-system-x86_64_x2ArxjEmJM](https://user-images.githubusercontent.com/10332458/93328965-27986a80-f825-11ea-9eeb-709021e2c228.png)

**Comment by SamuelBucher** [comment]
Thank you.

**Comment by K1rakishou** [comment]
If this helped then I'm gonna close the issue.

**Comment by SamuelBucher** [comment]
Yes. It's good now.

**Comment by K1rakishou** [comment]
Alright.
