### ISSUE TITLE
[Feature Request] Google Lens support in reverse image search

### ISSUE THREAD

**Issue by Licious-lul** [K1rakishou/Kuroba-Experimental#1070]
For some time now the "normal" Google reverse image search has been an unusable mess that often finds 0 results, while Google Lens on the other hand manages to find slightly better results, sometimes even the image source itself. This is an issue on Google's side of course, I'm assuming they are planning to abandon the non-lens reverse image search at some point.

Here's an example with a random pic from /a/.

Google reverse image search:
![google-search-example](https://github.com/K1rakishou/Kuroba-Experimental/assets/127618044/2c7c0e8d-9190-4b0b-80b4-cf57230d68a4)

Lens (Right side is the "Find Image Source" page):
![lens-example](https://github.com/K1rakishou/Kuroba-Experimental/assets/127618044/af6581ed-4566-4684-9a2a-c903ff5f07d8)

I'm suggesting adding Google Lens to the list of reverse image search sites.
Lens does suck for various other reasons, but in many situations it manages to be a bit more useful than the older reverse search.
"https://lens.google.com/uploadbyurl?url=" should work for directly uploading photos from an URL

**Comment by K1rakishou** [comment]
Will be added in the next beta.
