### ISSUE TITLE
Stuck after Cloudflare verification

### ISSUE THREAD

**Issue by clover-supply** [K1rakishou/Kuroba-Experimental#1077]
After "waiting for sys.4chan" I get a blank white window with {"ticket":"1715608597.701a26dd54bdafaf5de7fffdd44da4359c24fc91bc0d29589941de3914e20c42","pcd":60,"pcd_msg":"Please wait a while before making a post"}

and it doesn't go through

**Comment by hiragashi** [comment]
Delete your CloudFlare cookies mah nigga

**Comment by clover-supply** [comment]
> Delete your CloudFlare cookies mah nigga

I might be blind because I can't see the option for it anywhere in settings.

**Comment by bqv** [comment]
4chan site settings

**Comment by clover-supply** [comment]
> 4chan site settings

Still nothing. Tried the beta too and doesn't work either.
![Screenshot_20240514-153511](https://github.com/K1rakishou/Kuroba-Experimental/assets/112143811/89edf78e-acc4-4662-80a7-71cdf73ffd7a)

**Comment by K1rakishou** [comment]
@entauri I think your WebView needs to be updated. I get the same result in my emulator but it works fine on a real phone.

**Comment by clover-supply** [comment]
> @entauri I think your WebView needs to be updated. I get the same result in my emulator but it works fine on a real phone.

Is it possible my android is no longer supported? I couldn't even find webview in play store and manually deleting updates and re-updating only brought it back to my current version. Android 6 custom rom btw.

**Comment by clover-supply** [comment]
nvm, it needs ver 8+ at least. It's over.

**Comment by K1rakishou** [comment]
I'm not 100% sure that this is the case. Just try to update it if you can.
