### ISSUE TITLE
Display threads mixed from all boards in the composite catalog with sort "Newest".

### ISSUE THREAD

**Issue by Wyuis** [K1rakishou/Kuroba-Experimental#1108]
Now, if there are two boards in the composite catalog and the sorting is "Newest", then in the list of catalog threads, all new threads of the first board will appear first, and only then at the bottom all threads of the second board...

It seems to me that this is wrong and needs to be done differently -> all new threads should be displayed mixed from all boards of the composite catalog.

This is very important and a change is needed, please make it, it is very necessary.

**Comment by K1rakishou** [comment]
This should be already fixed. Maybe it's hasn't been released in the main version and is still a beta feature. But if should be fixed.

**Comment by Wyuis** [comment]
I checked, it’s done in beta, it works as it should. Thanks. Finally it was fixed, hurray :)
