### ISSUE TITLE
App does not set the top board as the startup board after restart

### ISSUE THREAD

**Issue by obscenelyvague** [K1rakishou/Kuroba-Experimental#125]
S̶t̶e̶p̶s̶ ̶t̶o̶ ̶r̶e̶p̶r̶o̶d̶u̶c̶e̶:̶
̶1̶.̶ ̶R̶e̶a̶r̶r̶a̶n̶g̶e̶ ̶y̶o̶u̶r̶ ̶a̶d̶d̶e̶d̶ ̶b̶o̶a̶r̶d̶s̶ ̶f̶r̶o̶m̶ ̶s̶e̶t̶t̶i̶n̶g̶s̶
̶2̶.̶ ̶V̶i̶e̶w̶ ̶b̶o̶a̶r̶d̶s̶ ̶w̶i̶t̶h̶ ̶t̶h̶e̶ ̶d̶r̶o̶p̶-̶d̶o̶w̶n̶ ̶m̶e̶n̶u̶ ̶f̶r̶o̶m̶ ̶t̶h̶e̶ ̶b̶r̶o̶w̶s̶e̶ ̶t̶a̶b̶ ̶a̶n̶d̶ ̶m̶a̶k̶e̶ ̶s̶u̶r̶e̶ ̶o̶r̶d̶e̶r̶ ̶i̶s̶ ̶s̶a̶n̶e̶
̶3̶.̶ ̶(̶F̶o̶r̶c̶e̶)̶ ̶c̶l̶o̶s̶e̶ ̶a̶n̶d̶ ̶r̶e̶s̶t̶a̶r̶t̶ ̶a̶p̶p̶
̶4̶.̶ ̶C̶l̶i̶c̶k̶ ̶o̶n̶ ̶d̶r̶o̶p̶-̶d̶o̶w̶n̶ ̶m̶e̶n̶u̶ ̶a̶g̶a̶i̶n̶;̶ ̶o̶r̶d̶e̶r̶ ̶o̶f̶ ̶b̶o̶a̶r̶d̶s̶ ̶i̶s̶ ̶n̶o̶w̶ ̶r̶e̶v̶e̶r̶s̶e̶d̶
̶
̶E̶d̶i̶t̶:̶ ̶#̶9̶9̶ ̶s̶e̶e̶m̶s̶ ̶l̶i̶k̶e̶ ̶a̶ ̶s̶i̶m̶i̶l̶a̶r̶ ̶i̶s̶s̶u̶e̶ ̶t̶h̶a̶t̶ ̶i̶s̶ ̶a̶p̶p̶a̶r̶e̶n̶t̶l̶y̶ ̶n̶o̶w̶ ̶f̶i̶x̶e̶d̶.̶ ̶I̶ ̶d̶o̶n̶'̶t̶ ̶k̶n̶o̶w̶ ̶a̶t̶ ̶w̶h̶i̶c̶h̶ ̶c̶o̶m̶m̶i̶t̶ ̶t̶h̶e̶ ̶c̶u̶r̶r̶e̶n̶t̶ ̶b̶e̶t̶a̶ ̶v̶e̶r̶s̶i̶o̶n̶ ̶i̶s̶ ̶b̶u̶i̶l̶t̶ ̶o̶n̶ ̶b̶u̶t̶ ̶I̶ ̶c̶a̶m̶e̶ ̶a̶c̶r̶o̶s̶s̶ ̶t̶h̶e̶ ̶a̶f̶o̶r̶e̶m̶e̶n̶t̶i̶o̶n̶e̶d̶ ̶b̶u̶g̶ ̶o̶n̶ ̶t̶h̶e̶ ̶1̶0̶7̶_̶4̶6̶2̶d̶5̶a̶8̶6̶4̶4̶7̶1̶f̶f̶8̶9̶a̶b̶9̶e̶6̶4̶8̶d̶7̶0̶d̶e̶6̶2̶c̶5̶5̶0̶a̶c̶0̶d̶9̶b̶ ̶b̶u̶i̶l̶d̶.̶

Edit 2: Welp disregard all of that. Looks like the beta isn't up to date and the fix will be present later down the line anyway. This just turned into an issue with a different title now.

After reopening the app it retains the board which you were last on as its startup board as opposed to making it whatever board is at the top of the board selection list regardless of where you left off (which is what both Kuroba and Clover does). I'm not sure if this is an intentional change made on this fork, but if it is, then there should at least be a toggle for it.

**Comment by K1rakishou** [comment]
Yes that bug was fixed in #99

>I'm not sure if this is an intentional change made on this fork

Yes, it's intentional. It automatically loads the top most board from the history list (not the top most of the board selection list where you can reorder them). If there were no boards in the history then it loads the first board from board selection list.

>then there should at least be a toggle for it.

Yeah, I should probably add an option.

Will be implemented in https://github.com/K1rakishou/Kuroba-Experimental/issues/126
