### ISSUE TITLE
Videos aren't cached when streaming option enabled

### ISSUE THREAD

**Issue by obscenelyvague** [K1rakishou/Kuroba-Experimental#128]
When the streaming option is enabled, videos aren't saved to a cache for later viewing in that session like how they are with the option disabled. If you back out and click to view the same video again the video buffers from the beginning. I'm not sure if this can be implemented efficiently but if it is then it'll be a good addition.

**Comment by K1rakishou** [comment]
That's just how webm streaming was originally implemented. I agree that it should write directly into a file instead of an in-memory buffer, though.

**Comment by K1rakishou** [comment]
ExoPlayer now uses disk caching.
https://github.com/K1rakishou/Kuroba-Experimental/commit/b0592f3fde478ac30a6fb0fc4cda8dda997979ba
