### ISSUE TITLE
App opens last thread when "Load last opened board upon app start" option disabled

### ISSUE THREAD

**Issue by obscenelyvague** [K1rakishou/Kuroba-Experimental#145]
Steps to reproduce:
1. Disable "Load last opened board upon app start" option
2. View any thread from any board
3. Kill app
4. Upon relaunching app you'll be taken back to the same thread you viewed instead of the browse tab's thread feed

**Comment by K1rakishou** [comment]
Oh, so you meant to just load the default board without anything else. Alright.
