### ISSUE TITLE
[Request] Make highlighted thread top of catalogue.

### ISSUE THREAD

**Issue by Yoirkie** [K1rakishou/Kuroba-Experimental#147]
Almost like 4chan X does it with pinned threads.
If its possible to search the entire board with your highlight words and place it on top.

Heres an example of what it would look like, if my highlight word were "book", it will search the entire board and place on top.
![Capture](https://user-images.githubusercontent.com/55001676/93934125-4779d380-fce8-11ea-926b-6259bef0b1e2.PNG)

**Comment by K1rakishou** [comment]
I don't get what you mean by that. What highlighted thread? You can't highlight threads currently.
