### ISSUE TITLE
Add an option to open the original thread when viewing thread in archive and add visual indication

### ISSUE THREAD

**Issue by ayy91** [K1rakishou/Kuroba-Experimental#164]
After you open thread in archive, there is no option to open the original thread in the menu which would be pretty convenient.

It would also be nice if there is a visual indication that thread is currently being viewd in archive. Maybe add the archive logo next to the title or something.

**Comment by K1rakishou** [comment]
You can switch to the original thread via history (tabs). And you can tell them apart by their site icons (again in history).

![image](https://user-images.githubusercontent.com/10332458/94232616-1202ff00-ff0f-11ea-9d16-cf3e8aca8eee.png)

**Comment by ayy91** [comment]
Fair enough.
I still think it's counterintuitive having to open the history tab for these.

**Comment by K1rakishou** [comment]
That's what it was implemented for.
