### ISSUE TITLE
scrollbar tap zone too small, cant interract

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#167]
only time im able to scroll is slide mode where scrollbar is away from the edge, and the interractable area is like 1 pixel

**Comment by K1rakishou** [comment]
You don't need to tap exactly on the scrollbar's thumb location, you can tap any part of it and it will scroll you there. And the scrollbar needs to be visible (you need to scroll the content a little bit) before you can use it. It was done like this to prevent accidental touches.

**Comment by 1sad** [comment]
https://streamable.com/246ovd

**Comment by K1rakishou** [comment]
It seems like the touch position is outside of the scrollbar. I guess I can make a setting to increase it's width.

**Comment by 1sad** [comment]
thanks

**Comment by 1sad** [comment]
also forgot to mention, dont know if it helps, but i have the same problem in kuroba and clover, and changing app dpi to make everything "bigger" would allow me to interact 
the apps become unusable at that point though cause everything is too big

**Comment by K1rakishou** [comment]
Alright, I didn't implement a setting but made the scrollbar a little bit thicker.

https://github.com/K1rakishou/Kuroba-Experimental/commit/ef1d76ecd44698ced1060e58f1f869efcbd59c0b
