### ISSUE TITLE
oppening media in multi window mode stops buttons from working

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#168]
stops buttons from working untill the multi window area gets resized

**Comment by K1rakishou** [comment]
Can't reproduce on 0.2.4. You mean opening this app and another one in split screen mode and then opening any image? Or is it some kind of non standard window mode?

**Comment by 1sad** [comment]
samsung split view, dont know what its called

https://streamable.com/v9fy68

log after video

E/KurobaEx | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-1]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/v/1601323967XXX.jpg, state = Canceled
E/KurobaEx | DrawerController: topController is an unexpected controller type: BottomNavBarAwareNavigationController
E/KurobaEx | DrawerController: topController is an unexpected controller type: BottomNavBarAwareNavigationController
E/KurobaEx | DrawerController: topController is an unexpected controller type: BottomNavBarAwareNavigationController
E/KurobaEx | DrawerController: topController is an unexpected controller type: BottomNavBarAwareNavigationController

**Comment by 1sad** [comment]
so, uh, I put the logs, any idea if its fixable?

**Comment by K1rakishou** [comment]
Yeah, this is a known and a really shitty bug. I already did couple attempts to fix it but apparently it's still present.

**Comment by 1sad** [comment]
oh... I see, thank you and good luck
