### ISSUE TITLE
Viewing replies to picture

### ISSUE THREAD

**Issue by jkrass1** [K1rakishou/Kuroba-Experimental#184]
When a thread contains a lot of images and you swipe them, sometimes you want to see replies to a particular image. 

I think it would be very handy to quickly reveal such replies without exit viewing images mode.

Maybe with swiping up or long press gesture or something.

![Screenshot_2020-10-02-12-06-36-462_com github k1rakishou chan beta](https://user-images.githubusercontent.com/9212851/95002955-56169380-05e2-11eb-914e-a8dacba73451.jpg)

**Comment by K1rakishou** [comment]
I don't think this is going to be easy to implement. Especially because I'm planning to move image viewer into a separate activity/window.
