### ISSUE TITLE
Board search popup is covered by keyboard

### ISSUE THREAD

**Issue by jkrass1** [K1rakishou/Kuroba-Experimental#185]
![Screenshot_2020-10-02-12-05-11-872_com github k1rakishou chan beta](https://user-images.githubusercontent.com/9212851/95003012-2ae07400-05e3-11eb-9e2d-2d3fe87842d7.jpg)

**Comment by K1rakishou** [comment]
Yes, this is a know issue - https://github.com/K1rakishou/Kuroba-Experimental/issues/179
