### ISSUE TITLE
Add new theme with default gray colors to make all controls gray by default (fix for devices that do not allow coloring some controls)

### ISSUE THREAD

**Issue by obscenelyvague** [K1rakishou/Kuroba-Experimental#200]
Some important elements seem to be missing from the available themeable elements. If an entry for any of these do already exist, please point out what it's called.

1. Text selection highlight color (Appears to be purple on the dark theme).

2. Markdown texts (e.g. code snippets on /g/) are colored black. This makes them unreadable while using a dark background.

3. The loading circle for when video is buffering or streaming option is enabled appears to be purple. (This should match the accent color like every other instance of loading circles on the app)

**Comment by K1rakishou** [comment]
>Text selection highlight color (Appears to be purple on the dark theme).

Are you talking about post text selection in threads? Or is it some other screen?

>Markdown texts (e.g. code snippets on /g/) are colored black. This makes them unreadable while using a dark background.

Can you show a screenshot?

**Comment by K1rakishou** [comment]
The third case is fixed, the first two require more info.

**Comment by obscenelyvague** [comment]
![Screenshot_KurobaEx-beta_20201007-025848_1](https://user-images.githubusercontent.com/36733368/95259579-e76e4b80-0816-11eb-860c-01e85a2300bf.png)

I meant being able to change the purple highlight color seen on the first post of the screenshot.

On the second post there is a code snippet, but it's barely visible because I have a dark background and the code snippet has black texts.

**Comment by K1rakishou** [comment]
Alright, the code tags are fixed. The text selection is probably impossible to fix on your device. In one of the future updates I will just make all those things gray by default so at least it won't look this ugly. But for now I will leave it like this because I need more feedback since there are probably more places where I forgot to apply colors.
