### ISSUE TITLE
Custom themes. Post your custom theme here (Json + Screenshot) and one day it might get added to the wiki page which then will be used for in-app theme gallery.

### ISSUE THREAD

**Issue by paradox460** [K1rakishou/Kuroba-Experimental#203]
It might be useful to allow people to share premade themes. But I thought I should ask before I just went ahead and added the theme I made

**Comment by K1rakishou** [comment]
Yeah, I don't mind.

**Comment by paradox460** [comment]
Looks like I don't have permissions to do so

**Comment by K1rakishou** [comment]
I guess the easiest way would be to use this issue page as a theme dump and I will be gradually moving them to the wiki page. Refer to [this page](https://github.com/K1rakishou/Kuroba-Experimental/wiki/Dynamic-themes) for the guide on how to make a theme/what the colors mean.

**Comment by paradox460** [comment]
Ok, here's the theme I made, basically its tomorrow night. 
Preview: https://i.imgur.com/sxDWZpu.png

# Base16 Tomorrow Night
```json
{
  "accent_color": "#ff81a2be",
  "back_color": "#ff1d1f21",
  "bookmark_counter_has_replies_color": "#ffcc6666",
  "bookmark_counter_normal_color": "#ff81a2be",
  "bookmark_counter_not_watching_color": "#ffb4b7b4",
  "divider_color": "#ff373b41",
  "error_color": "#ffcc6666",
  "is_light_theme": false,
  "light_nav_bar": true,
  "light_status_bar": true,
  "name": "Tomorrow Night",
  "post_details_color": "#ff7b7b85",
  "post_highlight_quote_color": "#ffcc6666",
  "post_highlighted_color": "#608abeb7",
  "post_inline_quote_color": "#ffb5bd68",
  "post_link_color": "#ff81a2be",
  "post_name_color": "#ff81a2be",
  "post_quote_color": "#ff81a2be",
  "post_saved_reply_color": "#60b5bd68",
  "post_spoiler_color": "#ff373b41",
  "post_spoiler_reveal_text_color": "#ffffffff",
  "post_subject_color": "#ffb294bb",
  "post_unseen_label_color": "#ffb294bb",
  "primary_color": "#ff000000",
  "text_color_hint": "#ffb4b7b4",
  "text_color_primary": "#ffc5c8c6",
  "text_color_secondary": "#ffb4b7b4"
}
```

**Comment by MaxTendency** [comment]
Theme name: TrueDark
True black background, none of that fake grey shit. Should look good on AMOLED displays. 

Preview: https://i.imgur.com/rJwexOY.jpeg

```json
{
  "accent_color": "#2696D7",
  "back_color": "#000000",
  "bookmark_counter_has_replies_color": "#298a2e",
  "bookmark_counter_normal_color": "#18769b",
  "bookmark_counter_not_watching_color": "#ff898989",
  "divider_color": "#404040",
  "error_color": "#ffff4444",
  "is_light_theme": false,
  "light_nav_bar": true,
  "light_status_bar": true,
  "name": "TrueDark",
  "post_details_color": "#ff7b7b85",
  "post_highlight_quote_color": "#18769b",
  "post_highlighted_color": "#2b2b2b",
  "post_inline_quote_color": "#23a923",
  "post_link_color": "#18769b",
  "post_name_color": "#298a2e",
  "post_quote_color": "#18769b",
  "post_saved_reply_color": "#1f1f1f",
  "post_spoiler_color": "#2b2b2b",
  "post_spoiler_reveal_text_color": "#cacecb",
  "post_subject_color": "#c93b3b",
  "post_unseen_label_color": "#ffbf3232",
  "primary_color": "#ff090909",
  "text_color_hint": "#cacecb",
  "text_color_primary": "#cacecb",
  "text_color_secondary": "#c93b3b"
}
```

**Comment by K1rakishou** [comment]
Gruvbox Black
https://i.imgur.com/1oKumIH.png

```json
{
  "accent_color": "#d79921",
  "back_color": "#000000",
  "bookmark_counter_has_replies_color": "fb4934",
  "bookmark_counter_normal_color": "#fabd2f",
  "bookmark_counter_not_watching_color": "#ff898989",
  "divider_color": "#1effffff",
  "error_color": "#ffff4444",
  "is_light_theme": false,
  "light_nav_bar": true,
  "light_status_bar": true,
  "name": "Gruvbox Black",
  "post_details_color": "#ff7b7b85",
  "post_highlight_quote_color": "#ff612c38",
  "post_highlighted_color": "#60947383",
  "post_inline_quote_color": "98971a",
  "post_link_color": "#458588",
  "post_name_color": "#ff996878",
  "post_quote_color": "#cc241d",
  "post_saved_reply_color": "#6078616c",
  "post_spoiler_color": "#32302f",
  "post_spoiler_reveal_text_color": "#ffffffff",
  "post_subject_color": "#928374",
  "post_unseen_label_color": "#282828",
  "primary_color": "#000000",
  "text_color_hint": "#ff7b7b85",
  "text_color_primary": "#bdae93",
  "text_color_secondary": "#a89984"
}
```

**Comment by lkd70** [comment]
I've just attempted to convert the default oneechan themes over to Kuroba-Ex, I'm sure they're far from perfect, but may give someone a jumping off point to make something nice and clean.

https://gist.github.com/lkd70/5bba22aa67db1304e6954833e92e2945

Any feedback is appreciated.

Screenshots: https://imgur.com/a/FZtxQBz

Yes, the white themes are broken at the moment. Will fix soon(tm)

Edit: Fixed the white themes. Some themes are stil a little "off" in my opinion, but it might just be that i don't like the style of them.

It's worth noting, these are the Oneechan versions of these themes. That means "real" monokai, tomorrow, etc... might not be reflective of these versions.

**Comment by K1rakishou** [comment]
@lkd70 
Thanks for converting so many different themes, but yeah, some light themes need adjustments. By the way, toolbar and bottomnavview do not support very light colors like here:

![image](https://user-images.githubusercontent.com/10332458/105844848-eaba5c80-5fea-11eb-8191-f8b884e0f673.png)

I doubt that anyone will ever want to have a theme with colors this bright so I will probably leave it like this, meaning those colors will have to be darkened in the themes' files for them to look good.

Also, I think with this amount of themes I can now implement some kind of in-app theme gallery.

**Comment by lkd70** [comment]
Thanks for the feedback @K1rakishou 

I've updated all the themes with some edits. White themes actually look usable now. If there's anything else you can recommend please let me know.

**Comment by lkd70** [comment]
Hand-made a couple more. They're available here along with screenshots: https://github.com/lkd70/Kuroba-Ex-Themes

Contains:

Ayu Light/Dark/Mirage
Dracula
Nord Dark/Light (based on nord-vim, but added a light version, too)
Solarized Light

**Comment by K1rakishou** [comment]
Looks good. A couple of things that I've noticed.
- There are incorrect color values in this theme - https://github.com/lkd70/Kuroba-Ex-Themes/blob/master/Dracula.json
("post_highlighted_color": "##ffb86c") and ("post_quote_color": "##44475a") They have two ## instead of one.
- Ayu-Dark's "bookmark_counter_not_watching_color" is very similar to background color when when a bookmark is not watched (or is archived or deleted or whatever) you can't read what it says. (The same happens in Ayu-Mirage theme)

![image](https://user-images.githubusercontent.com/10332458/106010661-c2099400-60ca-11eb-9bd4-cb19f55df62d.png)

**Comment by K1rakishou** [comment]
Also "post_highlighted_color" in Solarized-Light theme is very similar to "post_highlight_quote_color" color.

![image](https://user-images.githubusercontent.com/10332458/106018483-9be7f200-60d2-11eb-80cd-66e20c45bd52.png)

I guess you can just simply add some transparency to it like - "#2aa198" -> "#802aa198"

**Comment by he2a** [comment]
Didn't know the wiki existed. Good for AMOLED screens with muted colors for reading in the dark.
## Theme: Kuronegro
```
{
       "accent_color":"#ff78a83a",
       "back_color":"#ff000000",
       "bookmark_counter_has_replies_color":"#ffff4444",
       "bookmark_counter_normal_color":"#ff33b5e5",
       "bookmark_counter_not_watching_color":"#ff898989",
       "divider_color":"#1effffff",
       "error_color":"#ffff4444",
       "is_light_theme":false,
       "light_nav_bar":true,
       "light_status_bar":true,
       "name":"Kuronegro",
       "post_details_color":"#ff7b7b85",
       "post_highlight_quote_color":"#ffab4d63",
       "post_highlighted_color":"#11ffffff",
       "post_inline_quote_color":"#bb9ab63f",
       "post_link_color":"#bbace5fc",
       "post_name_color":"#ff996878",
       "post_quote_color":"#ffab4d63",
       "post_saved_reply_color":"#ff1d1519",
       "post_spoiler_color":"#ff1d1519",
       "post_spoiler_reveal_text_color":"#ffd4c9ce",
       "post_subject_color":"#bbfda957",
       "post_unseen_label_color":"#bbedacc9",
       "primary_color":"#ff000000",
       "text_color_hint":"#ff7b7b85",
       "text_color_primary":"#ffffffff",
       "text_color_secondary":"#ff8c8ca1"
}
```

**Comment by he2a** [comment]
Didn't know this post existed. Been using this for AMOLED phone.

# Kuronegro
```
{
	"name":"Kuronegro",

	"is_light_theme":false,
	"primary_color":"#ff000000",
	"accent_color":"#ff78a83a",
	"back_color":"#ff000000",
	"divider_color":"#1effffff",
	"error_color":"#ffff4444",
	
	"text_color_primary":"#ffffffff",
	"text_color_secondary":"#ff8c8ca1",
	"text_color_hint":"#ff7b7b85",
	
	"light_nav_bar":true,
	"light_status_bar":true,
	
	"post_details_color":"#ff7b7b85",
	"post_unseen_label_color":"#bbedacc9",
	"post_highlighted_color":"#11ffffff",
	"post_name_color":"#ff996878",
	"post_link_color":"#bbace5fc",
	"post_quote_color":"#ffab4d63",
	"post_spoiler_color":"#ff1d1519",
	"post_spoiler_reveal_text_color":"#ffd4c9ce",
	"post_highlight_quote_color":"#ffab4d63",
	"post_inline_quote_color":"#bb9ab63f",
	"post_saved_reply_color":"#339ab63f",
	"post_subject_color":"#bbfda957",
	
	"bookmark_counter_normal_color":"#ff33b5e5",
	"bookmark_counter_not_watching_color":"#ff898989",
	"bookmark_counter_has_replies_color":"#ffff4444"
}
```

**Comment by lkd70** [comment]
> 
> 
> Also "post_highlighted_color" in Solarized-Light theme is very similar to "post_highlight_quote_color" color.
> 
> ![image](https://user-images.githubusercontent.com/10332458/106018483-9be7f200-60d2-11eb-80cd-66e20c45bd52.png)
> 
> I guess you can just simply add some transparency to it like - "#2aa198" -> "#802aa198"

Thank you for your attention to detail @K1rakishou 
I've updated all the themes on my github now. Should solve the issues you addressed and a couple others. Still more tweaks until I'm happy, but at least they're usable now.

**Comment by K1rakishou** [comment]
https://i.imgur.com/sKgHL4d.png

```
{
  "name": "Kuromakaba Light",
  "is_light_theme": true,
  "light_nav_bar": true,
  "light_status_bar": true,
  "accent_color": "#f3630e",
  "primary_color": "#000000",
  "back_color": "#e2e2e2",
  "post_details_color": "#6a6a6a",
  "post_highlight_quote_color": "#f3630e",
  "post_highlighted_color": "#f1f1f1",
  "post_inline_quote_color": "#899918",
  "post_link_color": "#f3630e",
  "post_name_color": "#6a6a6a",
  "post_quote_color": "#f3630e",
  "post_saved_reply_color": "#f1f1f1",
  "post_spoiler_color": "#c6c6c6",
  "post_spoiler_reveal_text_color": "#303030",
  "post_subject_color": "#134b6b",
  "post_unseen_label_color": "#ea8162",
  "text_color_hint": "#6a6a6a",
  "text_color_primary": "#474747",
  "text_color_secondary": "#6a6a6a",
  "bookmark_counter_has_replies_color": "#f3630e",
  "bookmark_counter_normal_color": "#474747",
  "bookmark_counter_not_watching_color": "#6a6a6a",
  "divider_color": "#c6c6c6",
  "error_color": "#ff0000"
}
```

https://i.imgur.com/C1jra1Y.png

```
{
    "name": "Kuromakaba Dark",
    "is_light_theme": false,
    "light_nav_bar": true,
    "light_status_bar": true,
    "accent_color": "#d77841",
    "primary_color": "#000000",
    "back_color": "#1c2633",
    "post_details_color": "#919191",
    "post_highlight_quote_color": "#d77841",
    "post_highlighted_color": "#29313d",
    "post_inline_quote_color": "#7f9b23",
    "post_link_color": "#d77841",
    "post_name_color": "#919191",
    "post_quote_color": "#d77841",
    "post_saved_reply_color": "#29313d",
    "post_spoiler_color": "#001224",
    "post_spoiler_reveal_text_color": "#9e9e9e",
    "post_subject_color": "#5895d3",
    "post_unseen_label_color": "#d38d70",
    "text_color_hint": "#919191",
    "text_color_primary": "#b9b9b9",
    "text_color_secondary": "#919191",
    "bookmark_counter_has_replies_color": "#d77841",
    "bookmark_counter_normal_color": "#b9b9b9",
    "bookmark_counter_not_watching_color": "#919191",
    "divider_color": "#001224",
    "error_color": "#ff0000"

  }
```

**Comment by MrPrettyKitty** [comment]
Literally just copied over as much from the Black Kuroba theme. I liked the colors it used.

Preview: https://imgur.com/a/VvQhrFQ
```
{
  "accent_color": "#424242",
  "back_color": "#000000",
  "bookmark_counter_has_replies_color": "#CC0000",
  "bookmark_counter_normal_color": "#2AB6FC",
  "bookmark_counter_not_watching_color": "#424242",
  "divider_color": "#282828",
  "error_color": "#CC0000",
  "is_light_theme": false,
  "light_nav_bar": true,
  "light_status_bar": true,
  "name": "Kuroblack",
  "post_details_color": "#C4C4C4",
  "post_highlight_quote_color": "#CC0000",
  "post_highlighted_color": "#1C1C1C",
  "post_inline_quote_color": "#779C18",
  "post_link_color": "#635BFF",
  "post_name_color": "#E0E1FF",
  "post_quote_color": "#D90000",
  "post_saved_reply_color": "#1f1f1f",
  "post_spoiler_color": "#424242",
  "post_spoiler_reveal_text_color": "#cacecb",
  "post_subject_color": "#625cff",
  "post_unseen_label_color": "#500001",
  "primary_color": "#000000",
  "text_color_hint": "#cacecb",
  "text_color_primary": "#FFFFFF",
  "text_color_secondary": "#B5B5B5"
}
```

**Comment by crisalis2** [comment]
I will post this here instead of creating a new issue. These are several "issues" regarding app's appearance/themes. 

- The splash background color when lauching the app if it hadn't been opened before is gray, regardless of whether the light theme or the black theme is active. I think it should be for example white for the light theme and black for the dark theme, or even better, configurable in the custom theme JSON. 

- The status bar background color is always black and its text is white, regardless of whether the light theme or the black theme is active. I think it should be for example green with white text for the light theme and black with white text (same as now) for the dark theme, or even better, configurable in the custom theme JSON. 

- Can you make the "X new posts    VIEW" bottom notification's color configurable separately? Right now it uses the color defined in primary_color (color for the bottom drawer and other things). I want mostly everything black for OLED, that's why I have primary_color and back_color as 000000, but that makes that bottom notification particularly difficult to see because it kind of blends in with the background and the bottom drawer, which is always shown at first by default when entering a thread. 

- Can you make the colors of the scroll bar configurable? They don't seem to be configurable.

**Comment by K1rakishou** [comment]
@crisalis2 No this should be a separate issue because this issue is exclusively for posting themes.

**Comment by crisalis2** [comment]
Okay.

**Comment by K1rakishou** [comment]
Most of the themes from this repo (the ones that won't fuck me over) have been moved to the new repository ( https://github.com/K1rakishou/KurobaEx-themes ) which then will be used for built-in theme gallery. If you want to add new themes, then you will have to send a Pull Request to that repository. This issue will be closed once theme gallery is implemented and released.

**Comment by K1rakishou** [comment]
I'm closing this issue. Themes were moved here https://github.com/K1rakishou/KurobaEx-themes
