### ISSUE TITLE
ui ideas

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#204]
undo popup on swiping bookmark/history entry off to remedy accidental swipes

pulldown to refresh pins/history, pinned only maybe? (not sure if this is really needed but sometimes post counter doesnt update till you go into the bookmark)

some way to clear history/clear only unbookmarked history entries

sort option for bookmarks to be on top/bottom of history, same as bookmarks menu order/recently oppened order (can increase use of history as primary/secondary thread list depending on setting)

save bookmark window scroll position, instead of going to the top when you reopen it (when having a lot of bookmarks have to scroll down a lot while navigating)

long press on a thread in catalog to bookmark (currently no function on longpress?)

long press post number to reply instead of tap to prevent accidents

bookmarks catalog mode column number, maybe same as catalog?

**Comment by K1rakishou** [comment]
>undo popup on swiping bookmark/history entry off to remedy accidental swipes

I'm actually thinking of removing swipes in favor of selecting multiple bookmarks/history entries and then deleting them in one click.

>sort option for bookmarks to be on top/bottom of history, same as bookmarks menu order/recently oppened order (can increase use of history as primary/secondary thread list depending on setting)

I don't really get when you mean by this.

>long press on a thread in catalog to bookmark (currently no function on longpress?)

You can already bookmark threads from the catalog via post menu.

>long press post number to reply instead of tap to prevent accidents

I'm not sure about this one.

Some of other ideas were already planned.

**Comment by 1sad** [comment]
> > sort option for bookmarks to be on top/bottom of history, same as bookmarks menu order/recently oppened order (can increase use of history as primary/secondary thread list depending on setting)
> 
> I don't really get when you mean by this.

right now, bookmarks in history are just there, and sorted by most recently openned, and they shuffle around when you reopen them

if you sort for bookmarks to always be on top of the list, sorted the same way they are in bookmark menu, and non bookmarked entries below, you can use history panel the same way you use the bookmark menu but easier to access and having history below it, so you use history panel as primary browsing tool

if you sort bookmarks to be on the bottom, with history above, youll have history as almost a secondary bookmark menu 
or maybe better yet, if you have 2 bookmarks groups to switch in the bookmark menu, to have one current bookmarks and one for long term slow board bookmarks or nsfw stuff


> > long press on a thread in catalog to bookmark (currently no function on longpress?)
> 
> You can already bookmark threads from the catalog via post menu.

yea i know, its just that its pretty much the only function of the context menu i use, and i use it 100% of the times im in the catalog to just bookmark threads to look at them after im done scrolling the catalog, so it just streamlines the process. maybe my browsing habits are not common
just thinking of ways to not have to go to context menus cause they are getting crowded, putting common command on long press seems nice

**Comment by K1rakishou** [comment]
Gonna close this issue since it's very old, some stuff was implemented and some won't be implemented.
