### ISSUE TITLE
scrollbar post highlights not accurate

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#214]
its a bit inconsistent, sometimes the post is in the middle of the scrollbar, sometimes at top, sometimes several scrollbars worth of distance above it

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/6d1f724c0dad91c23f3b18fca46fb373f0d9ba8a
