### ISSUE TITLE
webm streaming doesnt start for long time

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#216]
checked on dashchan to confirm its not internet or server issues, same files start streaming instantly

```
E/KurobaEx | PartialContentSupportChecker: HEAD request to url (https://i.4cdn.org/v/1602785507XXX.webm) has failed because of "CancellationException" exception, time = 1ms
I/KurobaEx | WebmStreamingDataSource: detectLength: 3062667
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: detectLength: 3062667
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 1055463 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 0 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 3062600 length: -1
I/KurobaEx | WebmStreamingDataSource: close
I/KurobaEx | WebmStreamingDataSource: opening, position: 481 length: -1
I/KurobaEx | WebmStreamingDataSource: close
```

**Comment by K1rakishou** [comment]
This is most likely 4chan servers' issue. If you checked the same file then it probably already got cached by the cloudflare so it's no wonder it was faster in dashchan. You can try using "Force cloudflare to cache all files" and all the files in a thread will start loading instantly.

**Comment by 1sad** [comment]
i see, is there plans to make cache a toggle? or would that cause issues if literally everything got cached every time
aany plans for locally preloading images and videos for later viewing?

also have similar issue with images when chunked downloads are enabled, is that possible server issue too?

**Comment by K1rakishou** [comment]
>i see, is there plans to make cache a toggle?

I'm still collecting feedback on that feature (though it seems like nobody uses it or just nobody cares to leave the feedback so it's hard to say how good it works, but it works for me at least) but yeah, there are plans on making this feature behaving like media prefetching works.

>or would that cause issues if literally everything got cached every time

I guess it would only cause problems for 4chan (more traffic - more money) but on the other hand it's kinda supposed to work like that (media is always cached by Cloudflare when you open it, though in this case I'm using a little hack). It may even get disabled.

>aany plans for locally preloading images and videos for later viewing?

Something like a thread download feature? No, not for now. There is the archives support instead of that. There is also media prefetching but it only downloads media for visible posts (and a couple of posts outside of the screen).

>also have similar issue with images when chunked downloads are enabled, is that possible server issue too?

You mean images sometimes not loading fully?

**Comment by 1sad** [comment]
caching seems to work for me, it worked for the webm issue i had

> Something like a thread download feature? No, not for now. There is the archives support instead of that.

any plans to have selective post screenshot like dashchan? where you can pick posts to screenshot only them in a long image
youre right that local downloading is not very needed anymore, but this would be a nice feature to have

> You mean images sometimes not loading fully?

yes something like that, they start to load only after some time, and when i look at the log theres a bunch of stuff about chunked downloader failing, or the load bar gets stuck along the way and it takes couple of seconds (im guessing it retries something) to start loading again
ill try to post logs sometime later

**Comment by 1sad** [comment]
something like this
also I dont know if load bar represents actual progress, but it doesnt seem like chunks ever load in parallel
first part of the bar loads and then second one

E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-1]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/v/1603025824XXX.jpg, state = Canceled




E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ViewUtils: setHandlesColors() failure, error=Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/KurobaEx | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-0]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/g/1602965527XXX.jpg, state = Canceled


scrolling through a gallery for couple minutes with 4 chunk enabled

E/KurobaEx | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/g/1602978831XXX.jpg, state = Canceled
E/KurobaEx | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-2]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/g/1602976644XXX.jpg, state = Canceled
E/KurobaEx | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/g/1603002780XXX.png, state = Canceled
E/KurobaEx | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-0]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/g/1603005816XXX.png, state = Canceled
E/KurobaEx | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-1]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://i.4cdn.org/g/1603021754XXX.png, state = Canceled

**Comment by K1rakishou** [comment]
CancellationException means that you didn't wait until the image was downloaded or timed out.

>also I dont know if load bar represents actual progress, but it doesnt seem like chunks ever load in parallel
first part of the bar loads and then second one

That happens when you download image directly from 4chan server which disables this feature from working because 4chan servers are really bad (or maybe they are not that bad but there is a huge amount of traffic). It only works on 4chan when an image is cached by cloudflare.

**Comment by 1sad** [comment]
>CancellationException means that you didn't wait until the image was downloaded or timed out.

i didnt cancel the loading, i just waited till it finishes, so it takes to long to load, times out automatically and restarts the loading?..
i can see clear hang ups when trying to download non cached with multiple chunks, compared to single chunk non cached

>It only works on 4chan when an image is cached by cloudflare.

i see, might be good to put that into the description of the feature
works well with caching, on 2 chunks at least, nothing in the log and everything loads real fast

**Comment by K1rakishou** [comment]
>i see, might be good to put that into the description of the feature

It also works on every other supported site, it's just 4chan that actively blocks it.
