### ISSUE TITLE
check for duplicates when saving images\videos

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#243]
dashchan has this cool feature, where when you save a duplicate, it asks you if you want to override, rename or view the original image
so if youre not sure that the image is a duplicate, you can view the local image, and then choose to either rename or override or cancel
it would be nice to have a thumbnail and some size information instead of just saving images with appended random letters (i dont know what the reason behind having that kind of append instead of file_(1) (2) (3) etc or why it was changed in the first place in kuroba, but its not very helpful i dont think)

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/1589e1cd4b22883974f93ba279283387f0aade15
