### ISSUE TITLE
Random video playback issue

### ISSUE THREAD

**Issue by xscd** [K1rakishou/Kuroba-Experimental#244]
The root issue is originally from Clover, Kuroba and now on Kuroba-Experimental. Its really annoying. It happens randomly but can be produced very easily just using the app is enough. I really want to raise this issue here since its really a blocker of comfy lurking. Having to switch back or forth to load the video. Here is the issue I talk about in a video: [https://files.catbox.moe/fl42nf.mp4](https://files.catbox.moe/fl42nf.mp4
)
Check 01:27 and 01:53 (All settings are defaults and cleared the data before recording so its the first clean launch) 

Not sure if its a device specific issue but I use Android 9 on my Samsung Galaxy S8+ (SM-G955F)

**Comment by K1rakishou** [comment]
This is most likely a problem in the player that Clover/Kuroba/KurobaEx use - Google's ExoPlayer ( https://github.com/google/ExoPlayer ). There is little we, app developers, can do. This might even be a phone specific problem. 
This https://github.com/K1rakishou/Kuroba-Experimental/issues/133 may somehow fix this issue though.

It would also be really helpful if you could provide the logs when this happens. Here is a guide how to get the logs - https://github.com/K1rakishou/Kuroba-Experimental/wiki/Getting-application-logs-crashlog-on-beta-release-builds
