### ISSUE TITLE
Catalog posts are not updated after new filter creation

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#246]

**Comment by K1rakishou** [comment]
Is it still not working after restarting the app too? Just checked and yeah, it doesn't update catalog posts after setting a filter but everything works after app restart.

**Comment by 1sad** [comment]
oh yea, seems to work after a full app restart

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/6502af7847a4e9d57c89a75abc616562cdc51819
