### ISSUE TITLE
Cant post on /bant/

### ISSUE THREAD

**Issue by MaxTendency** [K1rakishou/Kuroba-Experimental#250]
With KurobaEX I cant post on /bant/ , other boards seem to be working fine. It shows "post succesful" but the post doesn't actually post. On browser and kuroba (normal version) it works fine. Using the latest version and also tried both v2nojs and v2js captcha, still doesnt fix.

**Comment by K1rakishou** [comment]
Duplicate of https://github.com/K1rakishou/Kuroba-Experimental/issues/249
