### ISSUE TITLE
Use XML Preference for settings

### ISSUE THREAD

**Issue by TacoTheDank** [K1rakishou/Kuroba-Experimental#260]
Looks much nicer and is easier on the codebase.

- https://developer.android.com/guide/topics/ui/settings
- https://medium.com/google-developer-experts/exploring-android-jetpack-preferences-8bcb0b7bdd14
- https://blog.mindorks.com/implementing-android-jetpack-preferences

**Comment by K1rakishou** [comment]
This thing requires fragments and this app does not use any fragments and I have no plans to switch to them because I think they are not good.

**Comment by TacoTheDank** [comment]
I see. Fair enough.
