### ISSUE TITLE
Use ExoPlayer-DASH for video streaming instead of home-made solution

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#262]
is it possible to add an option for external webm plugin? 
or implement something from its code (dont know how this works at all)?

dash updated recently and i tried it to realize that webms play way better, I dont know if its something on my end, but by comparison its a big difference

https://streamable.com/nzvn9y

streaming is on in both cases

**Comment by K1rakishou** [comment]
I think I should better try using this thing https://exoplayer.dev/dash.html instead of home-made data source implementation for 
 video streaming.

**Comment by K1rakishou** [comment]
Alright, so DASH is a completely different thing and not what I though it is (it's MPEG-DASH). But I did change some things in how the current media player works so hopefully it helps.
