### ISSUE TITLE
M A S S I V E caches

### ISSUE THREAD

**Issue by obscenelyvague** [K1rakishou/Kuroba-Experimental#270]
App caches tend to pile up pretty quickly. Now, while there is an option to clear them from the developer options, a user shouldn't have to do this manually. The app should automatically clear caches once it crosses a certain threshold. There's two ways to go about this, let the user choose a limit starting from 128 MB to 512 MB, or hard-code a rational value within the app itself. I'm more in favor of the former.

**Comment by K1rakishou** [comment]
It already does that, all caches are getting automatically cleaned up once they reach a threshold.

**Comment by obscenelyvague** [comment]
Ah, I don't have prefetching enabled and 512 MB still is a lot. I'd like for it to be lower. Maybe half of that. I guess the preference for this would vary depending on the sites/boards users browse. Which is why I suggested adding an option to let users choose a limit.

**Comment by K1rakishou** [comment]
Yeah, adding an option for that is a good idea.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/20bac1965dec646c2a5cdd3f37d91a080282e2d2
