### ISSUE TITLE
Remember the custom flags and other bugs

### ISSUE THREAD

**Issue by User1l0** [K1rakishou/Kuroba-Experimental#276]
Add option to remember the custom country flags, or set the default flag, the problem is every time you have to enter the flag code to post, ex kuroba can't remember custom flags, it would be cool if you added the costum flag finding support to tap and select the available flag. Tere's another bug the back button doesn't work when you're enter some sections of settings

**Comment by K1rakishou** [comment]
>Tere's another bug the back button doesn't work when you're enter some sections of settings

What back button do you mean (hardware or some UI button) and what settings are you talking about?

**Comment by User1l0** [comment]
> > Tere's another bug the back button doesn't work when you're enter some sections of settings
> 
> What back button do you mean (hardware or some UI button) and what settings are you talking about?

The android navigation back Button, j don't know where it happens, it happens sometimes but it's somewhere in the settings like when you go to deeper section of settings like push the settings icon and go to behavior page or etc.  about other bugs the settings import export doesn't work, also  fix the dark theme, the purple text is slightly visible it's very uncomfortable to use the app, also you can make thread replyed user text number highlighted to see who is replyed to the comment.

**Comment by K1rakishou** [comment]
I  checked the settings but couldn't find a place where the back navbar button doesn't work. 

>the settings import export doesn't work

Yes because it's not implemented yet.

>fix the dark theme, the purple text is slightly visible it's very uncomfortable to use the app

You can adjust the colors by yourself. Here is a guide - https://github.com/K1rakishou/Kuroba-Experimental/wiki/Dynamic-themes

>also you can make thread replyed user text number highlighted to see who is replyed to the comment.

You mean to highlight a post that replies to your post? That's already planned.

**Comment by K1rakishou** [comment]
Flags now should be remembered, also new flag picker was implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/779ac6c8d42e3615b8455ea9081bc33c2afe4e81
