### ISSUE TITLE
/vt/ board missing

### ISSUE THREAD

**Issue by lebimax98** [K1rakishou/Kuroba-Experimental#280]
The new Virtual YouTubers board doesn't appear on the board list.

**Comment by K1rakishou** [comment]
Yes, because 4chan API has no such board as well.
Try searching for "vt" here -> https://a.4cdn.org/boards.json
Wait a couple of days and it will show up.

**Comment by K1rakishou** [comment]
The API has updated, now you just need to open the site settings and the boards should automatically update. Then you will finally see it.
