### ISSUE TITLE
option for page number on threads in bookmarks

### ISSUE THREAD

**Issue by greenscarf07** [K1rakishou/Kuroba-Experimental#284]
I realise this is already available for the gallery like mode but it would be useful in the list mode as well. Options to show images and number of posters in threads for bookmarks would be useful as well I think

**Comment by K1rakishou** [comment]
The problem here is that there is no space for those things in the list mode. List mode was only made for people who are too used to how bookmarks were in Clover/Kuroba. Preferred bookmark layout mode in KurobaEx is grid mode. 

>Options to show images and number of posters in threads for bookmarks would be useful as well I think

This can be added.

**Comment by seniorm0ment** [comment]
There is room in list mode, no? It would just cut off long titles.
We already have counters on the right. 
(Although it's not entirely clear which counter is for what imo)

**Comment by K1rakishou** [comment]
The list mode is deprecated and will be removed at some point in the future. It's just inferior to grid mode in every possible way.

**Comment by seniorm0ment** [comment]
Rip. I do love the list mode, I personally find it a lot cleaner and easier to read titles.
