### ISSUE TITLE
[Feature Request] GUI Improvements

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#289]
I'm finding a few things with the GUI that are a bit touchy, I'd like to suggest. As well as some quality of life features.

- If the typing box is open, and the page refreshes, the new posts notification displays over the text box.

- The ability to swipe up and swipe back down on the text box area (alternative to clicking the arrow to expand)

- Suggesting the ability to sort boards by name, and by shortcut name (/a/, /g/). Otherwise this needs to be done manually.

- Improved filter management (being able to simply paste in like such would be amazing: https://wiki.installgentoo.com/wiki/4chanX_filters). It also seems to apply kinda wonky currently.

- Using filters, hiding posts messes up images when you click on stuff. (Click on an image, it's the wrong image).

- An option to swap the left hamburger menu, to be bookmarks instead of history (this would swap the bottom button for bookmarks to then be history).

- counters for threads (ip, replies, etc)

- Global search (does it not work on anything but 4chan?)

Thanks! Love the app, appreciate it being pushed to f-droid as well.

**Comment by K1rakishou** [comment]
>Alternative way to quickly change filename, image checksum, and remove metadata instead of needing to hold down on each image, then click open in editor. Maybe make one click open image editor instead of selecting the files, then only select files if the user clicks the selection dot.

In the next version it will be possible to open image editor by double-tapping the reply image.

>Dark theme consistency, I think the default dark theme should ditch the amoled black headers, and just use a darker gray than the page backgrounds for consistency.

Themes are fully customizable, you can easily change it by yourself.

>An option to wrap text around images in posts would be nice.

That's not easily done on Android. I will overhaul the post views at some point though.

>An option to swap the left hamburger menu, to be bookmarks instead of history (this would swap the bottom button for bookmarks to then be history).

You can't swap them completely, but you can disable history so it will only show bookmarks in the left menu right now. There are no plans to add a setting to swap them completely though.

>Global search (does it not work on anything but 4chan?)

Only 4chan for now; four 4chan archives (warosu.org, fireden.net, arch.b4k.co, archived.moe) will be added in the next version

**Comment by seniorm0ment** [comment]
Removed addressed comments

**Comment by seniorm0ment** [comment]
~

**Comment by K1rakishou** [comment]
>If the typing box is open, and the page refreshes, the new posts notification displays over the text box.

I couldn't reproduce this one maybe it was already fixed?

>The ability to swipe up and swipe back down on the text box area (alternative to clicking the arrow to expand)

Already implemented.

>Suggesting the ability to sort boards by name, and by shortcut name (/a/, /g/). Otherwise this needs to be done manually.

This will be implemented in the future. https://github.com/K1rakishou/Kuroba-Experimental/issues/158

>Improved filter management (being able to simply paste in like such would be amazing: https://wiki.installgentoo.com/wiki/4chanX_filters). It also seems to apply kinda wonky currently.

Dunno about this one. Maybe, but not in the near future.

>Using filters, hiding posts messes up images when you click on stuff. (Click on an image, it's the wrong image).

I think this was already fixed.

>counters for threads (ip, replies, etc)

What do you mean by this? There are already counters in the thread's status view (the bottom one).

**Comment by seniorm0ment** [comment]
As for one, I think that was fixed. However I do notice images display under the notch cutting off text.
I can get back to the other points later

**Comment by baraa272** [comment]
can you please add the option to make images is next to text inside threads ??

**Comment by seniorm0ment** [comment]
+1 to text wrap around images, I also saw someone in a thread asking to adjust the image thumbnail sizes.

**Comment by K1rakishou** [comment]
>asking to adjust the image thumbnail sizes.

You can already do this.

**Comment by seniorm0ment** [comment]
Didn't know, didn't look. Just saying what someone posted.
Is it something that needs to be done in the json I assume?

**Comment by K1rakishou** [comment]
No it's in the settings. Search for "Post thumbnails size"
