### ISSUE TITLE
[Feature Request] New Site Support, Privacy Flag, WhoIS/Geotool/SSLLabs Information

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#290]
Requesting support for the following:

https://wirechan.org/

https://endchan.gg/ (https://endchan.net)

https://4taba.net/

https://8chan.moe/

https://8kun.top/

https://9chan.tw/

https://alogs.theguntretort.com/

https://anon.cafe/

https://smuglo.li/

https://tvch.moe/

https://zzzcban.xyz/

https://erischan.org/

https://late.city/

https://prolikewoah.com/

I assume some of these are utilizing the same backend.

________

I also wanted to suggest providing a flag, or little warning to users for sites that require non-free (libre) dependencies (Google reCaptcha, Cloudflare CDNs, Google API's, Fonts, etc) to view/post.

Even if the dependencies aren't required within the app, if it's something relevant when visiting the webpage I think a flag is due if the site uses stuff like such just notifing the user would be nice.

Also I'm not sure how much of that is relevant, I'm not an app developer, but it would be nice to be able to localize as much as possible (Similar to how browser extensions such as LocalCDN/Decentraleyes works) if relevant in this case. And block anything not needed to view and post.

_________

And lastly, suggesting fetching WhoIS information, and Geotool style results with country flag (domain name, where the host server is located, IP, server address, etc), and SSL Labs rating for sites. Unimportant, just a "cool to have" type thing.

Thanks, keep up the great work!

**Comment by K1rakishou** [comment]
That's a lot of sites and I don't plan to add them in the near future. Basically, If you want to see a site here you do all the work, I'm only providing the necessary tools for that (engine/backend support if necessary).

>I also wanted to suggest providing a flag, or little warning to users for sites that require non-free (libre) dependencies (Google reCaptcha, Cloudflare CDNs, Google API's, Fonts, etc) to view/post.

All of the sites use at least one of those. There is a warning of the F-Droid page (NonFreeNetwork).

>And lastly, suggesting fetching WhoIS information, and Geotool style results with country flag (domain name, where the host server is located, IP, server address, etc), and SSL Labs rating for sites. Unimportant, just a "cool to have" type thing.

You can probably just check all of that manually before enabling a site. It's not like that information changes that often.

**Comment by seniorm0ment** [comment]
> That's a lot of sites and I don't plan to add them in the near future. Basically, If you want to see a site here you do all the work

Understood, and yeah I didn't expect implementation of all.
Curiously though, if a site uses the same backend as another that is already supported, what needs to be added to support it?

>All of the sites use at least one of those. There is a warning of the F-Droid page (NonFreeNetwork).

I was suggesting the flag under the site settings, as it could make it clear to users who may want to base decisions per site. F-Droid's anti-feature is vague.
Even if none of the current sites use no nonfree dependencies, future sites may not. There's quite a few imageboards that don't use non-free dependencies. I think a note under the sites settings could be added that users could fill in when adding new sites would be nice. If not I understand though.

**Comment by K1rakishou** [comment]
>Curiously though, if a site uses the same backend as another that is already supported, what needs to be added to support it?

In the base-case scenario you just need to copy an existing site, rename it and change some links but that's rarely the case.

>I was suggesting the flag under the site settings, as it could make it clear to users who may want to base decisions per site.

Some sites use CloudFlare which hides the original host IP address so this thing becomes useless in this case (you will be most likely connected to a CDN that is closest to you). Right now there is only one such site, though (warosu).

>Even if none of the current sites use no nonfree dependencies, future sites may not. There's quite a few imageboards that don't use non-free dependencies. I think a note under the sites settings could be added that users could fill in when adding new sites would be nice.

Are you suggesting to do that manually for each site? Because there is probably no way to do that automatically (at least I can't think of any). If yes, then that means that I would have to check all the sites manually every day because something may change on a site literally any minute and that information will become irrelevant.

Privacy is good and all but that's not the main point of this app. There is already a lot of stuff done for privacy (like you don't load JS, except for one case to pass CloudFlare anti-ddos checks) but I think what you are suggesting is overkill.
