### ISSUE TITLE
Board ordering is not honored when adding

### ISSUE THREAD

**Issue by tidux** [K1rakishou/Kuroba-Experimental#291]
Adding 4chan to a fresh install and select all boards.  The list as presented to me starts with /3/ indicating an alphabetical sort.  When the boards are added, they display in the navigation menu in a completely different order, with /trash/ at the top.  The same bad ordering persists across removing and re adding the boards so it looks to be based on some defined value.  Is this an elaborate shitpost telling your users their posts belong on /trash/ or is this a case of treating a hash table as a sorted list?

**Comment by K1rakishou** [comment]
Yeah, this is already fixed in the latest beta. Thanks for reporting it anyway. The release will follow today or maybe tomorrow.
