### ISSUE TITLE
URLs won't open specific threads/posts in app

### ISSUE THREAD

**Issue by greenscarf07** [K1rakishou/Kuroba-Experimental#293]
I've tested this for boards.4chan.org and boards.4channel.org links

**Comment by K1rakishou** [comment]
~Can you provide those urls?~
Oh I see.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/c48166544c2ae4ca6a977c55481babc4b68c74e7
