### ISSUE TITLE
Not given watch option when applying default type filter

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#297]
Version: fdroid 0.4.75919
OS: Android 11
Model: samsung s21

I turned on the thread watcher, made a filter to search /jp/ for posts that had /elona/i in the subject. When chosing the action it only presented the 3 defaults without watch being an option.

 When turning on the background thread watcher I was given a notice that this type of phone had a habit of killing background processes. Does that have something to do with it?

**Comment by K1rakishou** [comment]
~Are you on the latest version? Filter watching was introduced in v0.5.0. If you don't see the WATCH action in filter creation dialog that means that you are on a v0.4.X or below.~

Oh yeah, I just noticed the version. Yes, you are not on the latest version. Filter watching was introduced in v0.5.0. F-Droid version still hasn't been updated for some reason (it's been two weeks). If you really want to use it you can download an apk from github.

**Comment by ghost** [comment]
Well, seems I just didn't read enough into the feature. Thanks for the reply, installed the github apk and works perfectly.
