### ISSUE TITLE
[Feature Request] Undo download and Confirm before download

### ISSUE THREAD

**Issue by inventfossil** [K1rakishou/Kuroba-Experimental#304]
Firstly - thank you for maintaining this app, it's amazing. ❤️

1. ReadChan has this feature where it shows an undo dialogue at the bottom after downloading something for few secs. 

2. Having an option to enable confirmation before downloading something.

**Comment by K1rakishou** [comment]
Do you want this to prevent accidental downloads by using swipe gestures or something? Because if so then there is a more simple way - you can just disable swipe to save gesture. Otherwise I can't think of why would anyone ever need this.

**Comment by inventfossil** [comment]
> Do you want this to prevent accidental downloads by using swipe gestures or something? Because if so then there is a more simple way - you can just disable swipe to save gesture. Otherwise I can't think of why would anyone ever need this.

my bad, didn't know that. Thanks 😄
