### ISSUE TITLE
Issue posting from smaller displays

### ISSUE THREAD

**Issue by svin24** [K1rakishou/Kuroba-Experimental#305]
![Screenshot_20210309-071717](https://user-images.githubusercontent.com/51864332/110422488-247d8900-80a8-11eb-9f15-f356a556d2b3.png)
KurobaEX takes way too much space already. With the picture layout you can't even see the first line of the post you are making.
Maybe if we had the option to make the pictures into smaller squares then it would fit.

**Comment by K1rakishou** [comment]
What display size is that?

**Comment by svin24** [comment]
5 inch display

**Comment by K1rakishou** [comment]
I guess that's because you have the numbers row on your keyboard which makes it bigger than it's supposed to be.

![qemu-system-x86_64_SpSsJ3ZrA8](https://user-images.githubusercontent.com/10332458/110467232-d1c3c180-80e7-11eb-9ead-a3bafd95aa0c.png)

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/9295d1558633747225099eb11164c5f6c1b54447
