### ISSUE TITLE
New media downloader FAQ (You can find answers to your reports here)

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#310]
UUID: 8b80d2fe190221ef20d670db555e4e99
Build flavor: stable
Version name: v0.6.4
OS info: Android 7.0, sdk version: 24
Report description: Kuroba no longer saves images in board folders and the option for it was removed.

**Comment by K1rakishou** [comment]
Is it really that hard to notice?

![image](https://user-images.githubusercontent.com/10332458/110743812-b375d700-8249-11eb-894b-c4657d7ee363.png)

**Comment by K1rakishou** [comment]
Save location
UUID: 118094185492c6e6deb17cbfda965bfd
Build flavor: stable
Version name: v0.6.5
OS info: Android 9, sdk version: 28
Report description: There isn't an option to put images in specific folders this wasn't an issue in the beta :(.

**Comment by K1rakishou** [comment]
> Download directory and duplicate file resilution
> UUID: 85ed1055c99012aabcae1cd6951acf0e
> Build flavor: stable
> Version name: v0.6.5
> OS info: Android 10, sdk version: 29
> Report description: In the latest kurobaex, once the initial setting of directory and saving duplicates is set the options are no where to be found in settings page. Can not change options.

Longtap any thumbnail or longtap download icon in image viewer.

**Comment by K1rakishou** [comment]
Save Location
UUID: fcee17944ef6609ce6d6e311649d10a2
Build flavor: stable
Version name: v0.6.5
OS info: Android 10, sdk version: 29
Report description: Any option about "save location" disappeared from the menu, now I'm stuck saving shit to the wrong folder

**Comment by Cerberuschan** [comment]
> Save Location
> UUID: fcee17944ef6609ce6d6e311649d10a2
> Build flavor: stable
> Version name: v0.6.5
> OS info: Android 10, sdk version: 29
> Report description: Any option about "save location" disappeared from the menu, now I'm stuck saving shit to the wrong folder

Have the same problem, can't seem to find the save location option anywhere.

**Comment by K1rakishou** [comment]
@Cerberuschan 
>Longtap any thumbnail or longtap download icon in image viewer.

**Comment by K1rakishou** [comment]
I guess it's fine now.
