### ISSUE TITLE
{Request} Could you add <root irectory>\<thread name> as a save option for albums?

### ISSUE THREAD

**Issue by warhugger** [K1rakishou/Kuroba-Experimental#312]
Sorry if this is the wrong place, I'm very new to GitHub. 

This is the one thing that kept me to Clover for Android, it made sorting massive libraries quicker and simpler.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/a628cd29e08416a40750b65345cb05e526188d65
