### ISSUE TITLE
Search In Thread Covers Captcha Goal

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#315]
# How To Replicate

1. Enter any thread (4chan)
2. Start a search, then click enter. Keyboard hides (cursor still blinks in search field).
3. Click a post to reply.
4. Enter your reply, then click submit
5. Captcha window opens
6. Search bar still at the top, also shows "Found x post for "xxxxx"", and below it shows the captcha icons
7. The search bar at the top hides the goal of the captcha (tap all crosswalks)
8. If you click android nav bar back button once, it closes search and reveals captcha goal. - However this should have simply been hidden after clicking step 4, then the search bar should have been recovered when the post is submitted after captcha completion.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/ffdc300f71a7dd3df7c0d968d29a2b32531c55bf
