### ISSUE TITLE
Issues with playing/saving videos

### ISSUE THREAD

**Issue by AnonAnonson0** [K1rakishou/Kuroba-Experimental#318]
Hello there, I am having an issue on my client where it will not save certain webms to my device. This problem occurs when I use the swiping gestures and when using the download buttons. If I open them in my browser it can download just fine. Along with this, some videos just wont play at all despite seeming to have all the prerequisite data loaded. Is there any way to fix this?

**Comment by K1rakishou** [comment]
What version? Does it show any errors? Can you provide the logs the next time this happens? (You need to send the logs right after it happens because the logs have fixed length after which they are cut off).

**Comment by AnonAnonson0** [comment]
> What version? Does it show any errors? Can you provide the logs the next time this happens? (You need to send the logs right after it happens because the logs have fixed length after which they are cut off).

Using the most updated version from F-droid and just sent you a report/logs from the app itself! Thanks for looking into it

**Comment by AnonAnonson0** [comment]
The version is KurobaEx-fdroid v0.6.4.8554  (commit 57ef141c6f42). Should I upload the logs here as well?

**Comment by K1rakishou** [comment]
Can you try updating to the v0.6.5 version? It came out earlier today on F-Droid and there might be a fix for this problem.

**Comment by AnonAnonson0** [comment]
> Can you try updating to the v0.6.5 version? It came out earlier today on F-Droid and there might be a fix for this problem.

Will do, ill see if that fixes it

**Comment by AnonAnonson0** [comment]
That seems to work! Thank you for your help!

**Comment by K1rakishou** [comment]
No problem.
