### ISSUE TITLE
Automatically open gallery

### ISSUE THREAD

**Issue by 0x74hd9** [K1rakishou/Kuroba-Experimental#321]
Whenever I attach an image, I have to select to select my gallery app from the hamburger menu then choose the Clover folder. Can you change it so it's like Twitter or FaceApp, where they show all the images on my phone and I can choose the folder. Something like this from Twitter:

![Screenshot_20210323-192919](https://user-images.githubusercontent.com/81269363/112231989-31ed5400-8c0e-11eb-867c-1126a0871de9.png)

**Comment by K1rakishou** [comment]
Unfortunately, no, I don't think this can be done because I don't think SAF's file manager allows doing this.
