### ISSUE TITLE
Report "local 4chan archive"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#329]
UUID: fb345d4a39ef64a4701f9e6ae738778a
Build flavor: beta
Version name: v0.7.4
OS info: Android 11, sdk version: 30
Report description: how do I view the local archive built in to 4chan?

**Comment by K1rakishou** [comment]
You can't. Use other archives.

**Comment by crisalis2** [comment]
B-but Kuroba had this.

**Comment by K1rakishou** [comment]
It's redundant because you can find the same stuff in other archives.

**Comment by crisalis2** [comment]
Yes, but the local archive is like an extended version of the current catalog, I can go there and easily see the threads that have just died and are relevant to the present. How can I find those threads easily in other archives? I can't even seem to browse other archive's catalogs directly within KurobaEx, I need to open a specific thread and then open it in the archive, and then what? How do I even access an archive's catalog or search in a given archive from within KurobaEx? Maybe I'm missing something. Even if I can access an archive's catalog within KurobaEx, there's no immediate way to locate those threads from the local archive that are so easily found just by going to boards.4channel.org/board/archive using an external browser.
