### ISSUE TITLE
App is permanently loading on start-up

### ISSUE THREAD

**Issue by gut5** [K1rakishou/Kuroba-Experimental#331]
Using the latest version 0.7.4. Previous version was fine and I'm no longer able to downgrade back to 0.6.5.

**Comment by K1rakishou** [comment]
I'm gonna need logs.

**Comment by gut5** [comment]
It's a non-rooted device, sorry. If it helps, the progress circle indicator just keeps spinning on all screens, even when you open the sidetab that has all the watched threads.

**Comment by K1rakishou** [comment]
I mean the app has built-in logger which is enabled by default. When this happens the next time you need to go to settings and send me a report (logs will be attached automatically). But you need to do that right when this happens because there is a limited amount of log lines and the important part may get overwritten.

**Comment by K1rakishou** [comment]
Alternatively, if it still doesn't work, you can export app backup, clean the app data and then import it back.

**Comment by gut5** [comment]
I can't even access the options, it's doing the same infinite loading indicator on the options tab.

**Comment by K1rakishou** [comment]
Oh well that sucks. Does force stopping the app help?

**Comment by gut5** [comment]
No, same problem as before

**Comment by K1rakishou** [comment]
Can you try taking the logs via ADB?
https://github.com/K1rakishou/Kuroba-Experimental/wiki/Getting-application-logs-or-crashlogs-on-beta-or-release-builds

**Comment by gut5** [comment]
Yep thanks I'll give it a try, not much to lose at this point.

**Comment by gut5** [comment]
https://a.uguu.se/ozdsXquG.log 
Let me know if this helps.

**Comment by K1rakishou** [comment]
Alright I found the potential place but I have no idea what's causing it. I made a new apk with more logs so if it's not a bother to you then could you please take the logs again after installing this apk? Judging by the logs you are using the stable version so this one is stable too.

Here is the apk:
[KurobaEx.zip](https://github.com/K1rakishou/Kuroba-Experimental/files/6227879/KurobaEx.zip)

**Comment by gut5** [comment]
Thanks, here are the logs for the version you posted just now 
https://a.uguu.se/FlYtGzPH.log

**Comment by K1rakishou** [comment]
Alright, how about now.
[KurobaEx.zip](https://github.com/K1rakishou/Kuroba-Experimental/files/6228421/KurobaEx.zip)

**Comment by gut5** [comment]
Installed the version you just posted but it's the same problem as before. Should I post logs again?

**Comment by K1rakishou** [comment]
Damn. Yeah, please post the logs again, I've added more stuff there.

**Comment by gut5** [comment]
posted
https://a.uguu.se/nxiUcjTh.log

**Comment by K1rakishou** [comment]
Alright, this is the last one. If this one doesn't work then I have no idea what's causing it, most likely a library bug. Judging by the logs it just hangs during a database call which works fine for me. Oh yeah, if it doesn't work then please attach the logs once again.

[KurobaEx.zip](https://github.com/K1rakishou/Kuroba-Experimental/files/6229127/KurobaEx.zip)

**Comment by gut5** [comment]
Sorry I have no idea why it lagged out the first time I tried it, but the version ( https://github.com/K1rakishou/Kuroba-Experimental/files/6228421/KurobaEx.zip ) previous to the one you just linked actually worked after I opened it another time.

**Comment by K1rakishou** [comment]
Alright, then I guess you can use this APK for now, I will do a proper release today or tomorrow.

**Comment by gut5** [comment]
Sorry, this is embarrassing but after working for like an hour or so, the app went back to the infinite-loading thing in the thread catalog. I did try the last version you posted here ( https://github.com/K1rakishou/Kuroba-Experimental/files/6229127/KurobaEx.zip ) but the same problem exists. The good thing is I managed to export the backup before so at least I have a record of where I was.

The log posted is for the latest version you posted in this conversation.

https://a.uguu.se/kvPAOZyA.log

**Comment by K1rakishou** [comment]
Well this suck. And I was about to release it too. Well, I know the exact place where this happens but I have no idea why. The method is called two times, the first time it completes just fine the second time it hangs for some unknown reason. I have a couple of more things I would like to try and if none of them work then I give up. 

You don't have to take the logs for this one.
[KurobaEx.zip](https://github.com/K1rakishou/Kuroba-Experimental/files/6235456/KurobaEx.zip)

**Comment by gut5** [comment]
Tried the version you just posted but it didn't fix it. I'll probably nuke the app data and start again from 0.6.4 which was working fine for me.

**Comment by K1rakishou** [comment]
What about clearing the app data and then restoring it from backup?

**Comment by gut5** [comment]
I tried that but it still had the same problem.

**Comment by gut5** [comment]
I don't know if this is relevant but I noticed after I leave the current version (0.7.5) of the app open long enough in the permanent-loading state it eventually crashes out by itself with no errors. Is it worth logging the entire thing for you from when I open the app to when it crashes on its own?

**Comment by lsvy97** [comment]
Same problem here.
Here's a log: https://pastebin.com/2YkWuBgM

**Comment by lsvy97** [comment]
Oh, also if you leave it open in the foreground and return to it after a while, it starts working as it normally would.

**Comment by gut5** [comment]
What Android version are you using? I'm on 11 and it just crashes when it's been open in the foreground for long enough.

**Comment by lsvy97** [comment]
LeEco Le 2, Android 6.0.
Mistype btw, background, not foreground. Also works in foreground when phone was locked for some amount of time. Maybe has nothing to do with background/foreground and just works after some amount of time, haven't checked yet.

**Comment by K1rakishou** [comment]
@lsvy97 Unfortunately there is nothing in the logs related to the app.

I rewrote the place where the deadlock occurs a little bit, now it doesn't load sites from the DB a second time anymore and instead uses cache. If the reason of the deadlock lies in that DB call then the app shouldn't hang anymore. The logs were removed so there is no need to take them this time.

@gut5 
@lsvy97 
[KurobaEx.zip](https://github.com/K1rakishou/Kuroba-Experimental/files/6277605/KurobaEx.zip)

**Comment by gut5** [comment]
It's still perma-loading on the main catalog but bookmarked-threads sidebar now shows whatever I had bookmarked so that's a step forward I guess.

**Comment by lsvy97** [comment]
> @lsvy97 Unfortunately there is nothing in the logs related to the app.

I also sent logs another way, through built-in app feature, when it loaded. Did you get it?

New version still doesn't load anything, both catalog, settings and bookmarks. It's still the same.

**Comment by K1rakishou** [comment]
>I also sent logs another way, through built-in app feature, when it loaded. Did you get it?

They are the same logs, if logs taken via ADB do not show anything then in-app logs are the same.

**Comment by lsvy97** [comment]
> > I also sent logs another way, through built-in app feature, when it loaded. Did you get it?
> 
> They are the same logs, if logs taken via ADB do not show anything then in-app logs are the same.

Would "verbose logs" option help?

**Comment by K1rakishou** [comment]
Well it will add some additional logs but the problem here is different. There should be at least something in the logs if the app is running. Maybe you somehow filtered it out? All of the app logs have "KurobaEx" tag.

**Comment by gut5** [comment]
Thanks, the suggestion about leaving it open in the background actually worked but yeah the problem still exists if you don't do that or you come back to it after a while.

**Comment by K1rakishou** [comment]
@gut5 
@lsvy97 
Where do you have the app installed: on a sd-card or on the internal storage? And where is the app data located: on a sd-card or internal storage?

**Comment by gut5** [comment]
It's a Pixel 2, so it's all on internal storage (afaik this only has internal storage)

**Comment by K1rakishou** [comment]
Alright I got another idea of why this may happen. Again, no need to take the logs if it gets stuck.

@gut5 
[KurobaEx.zip](https://github.com/K1rakishou/Kuroba-Experimental/files/6297707/KurobaEx.zip)

**Comment by gut5** [comment]
Tried the new build but no luck this time sorry. Just to reiterate, I'm starting from scratch by removing any old versions of the app then installing, then importing the exported data zip from when I managed to do so. I can send you a copy of the data zip file if it will help figure out what's going on here.

**Comment by K1rakishou** [comment]
>I can send you a copy of the data zip file if it will help figure out what's going on here.

Yeah this will be really helpful. You can send it to me via the email.

**Comment by K1rakishou** [comment]
@gut5 
Alright, I got your backup and managed to reproduce it. And now I know what's the cause. It's not actually freezing/deadlocking, there is just way too many threads in the database (so it takes a lot of time to complete) and one memory optimization that I did ended up being waaaay too slow.

**Comment by K1rakishou** [comment]
@gut5 
Alright, it works for me now but just to be sure that it works for you too.

@lsvy97 
You most likely have the same problem so try this apk out.

[KurobaEx.zip](https://github.com/K1rakishou/Kuroba-Experimental/files/6310674/KurobaEx.zip)

**Comment by gut5** [comment]
Yep, that works now, thanks.

**Comment by K1rakishou** [comment]
Nice.
https://github.com/K1rakishou/Kuroba-Experimental/commit/a2b9122b8c77dee9acadbd87b55589a5beb3aeb2

**Comment by lsvy97** [comment]
> @gut5
> Alright, it works for me now but just to be sure that it works for you too.
> 
> @lsvy97
> You most likely have the same problem so try this apk out.
> 
> [KurobaEx.zip](https://github.com/K1rakishou/Kuroba-Experimental/files/6310674/KurobaEx.zip)

Just tried it up, it works, thanks👍
