### ISSUE TITLE
[Bug] Black Padding Behind Sites Edit Popup

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#334]
When you go to sites, tne click the edit icon in the top right, the popup window has a black box behind it.

Also two updates ago, Kuroba messed up my ordering of the boards. Any chance a simple button could be added that just sorts the boards alphabetically could be added? 
It's a PITA to manually sort 80 boards by dragging.

**Comment by K1rakishou** [comment]
>When you go to sites, tne click the edit icon in the top right, the popup window has a black box behind it.

What version?

**Comment by seniorm0ment** [comment]
0.6.5 Fdroid

**Comment by K1rakishou** [comment]
That bug is fixed in v0.7.x
