### ISSUE TITLE
Report "Adaptative icon"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#336]
UUID: 23e0e956a9bbbb22fb26871f87ce5054
Build flavor: stable
Version name: v0.7.5
OS info: Android 11, sdk version: 30
Report description: Android sometimes adds a white border to the circular icon, I believe changing it to the adaptative guidelines would be better for modern android versions.

https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by K1rakishou** [comment]
If somebody makes the current icon into the vector file that android supports, then sure, why not.

**Comment by obj44** [comment]
I've noticed that on my phone, so I'll try and adjust it to support all android launchers.

**Comment by Guernsey219** [comment]
Can't you just use the same icon for the foreground and background like Kuroba does?

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/891f76deb6666745e032691f7bc6cdfd48952dfe
