### ISSUE TITLE
New catalog search UI is terrible

### ISSUE THREAD

**Issue by tidux** [K1rakishou/Kuroba-Experimental#339]
Seriously, it's fucking garbage.  I can't believe one user even asked for this gay popup that only shows you one thread at a time until you stop typing.  Please revert to how it was in prior releases when it worked like the catalog is supposed to.

**Comment by K1rakishou** [comment]
Close the keyboard and you will see more.

**Comment by tidux** [comment]
It's still shit. What exactly was wrong with the old behavior that left all the matching threads visible at the same time?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by K1rakishou** [comment]
The problem was that it would fuck up the original scroll position and scroll you at the very beginning after you are done with the search. Plus that implementation was pretty complex so it lead to bugs.

**Comment by tidux** [comment]
OK, as long as this was actually designed to fix a problem rather than just change for the sake of it.
