### ISSUE TITLE
Color of op post text changes to black (probably Xiaomi device needed for testing)

### ISSUE THREAD

**Issue by cuteasci** [K1rakishou/Kuroba-Experimental#346]
![Screenshot_2021-04-13-23-05-50-617_com github k1rakishou chan beta](https://user-images.githubusercontent.com/59581277/114614982-d44ca480-9cad-11eb-9236-af7bafdb7905.jpg)
![Screenshot_2021-04-13-23-05-22-883_com github k1rakishou chan beta](https://user-images.githubusercontent.com/59581277/114615037-df073980-9cad-11eb-895e-11d10f222170.jpg)

**Comment by cuteasci** [comment]
Looks like this happens when it checks if there is new posts. (I.e. loader timer goes to 0) 

When you scroll a little, the color goes back to original color. 

And then again back to black after loading.

**Comment by K1rakishou** [comment]
What happens if you try to toggle the theme?

**Comment by cuteasci** [comment]
Same.
Also, it seems if you disable dark mode (I have Miui) the problem goes away 
![Screenshot_2021-04-14-21-48-57-252_com github k1rakishou chan beta](https://user-images.githubusercontent.com/59581277/114763364-61096800-9d6b-11eb-9952-b7d19f891d63.jpg)

**Comment by K1rakishou** [comment]
Do you have "Ignore system day/night mode" setting disabled? It's in the themes settings (where the themes are located) in the three dot menu.

>Also, it seems if you disable dark mode (I have Miui) the problem goes away

Well I guess if it's something xiaomi-related then the only way for me to fix it is to buy a xiaomi device.

**Comment by cuteasci** [comment]
> Do you have "Ignore system day/night mode" setting disabled?

It was enabled.

**Comment by barabraa** [comment]
I also get this bug on a Xiaomi phone, the fix is to go Settings -> Display -> More dark mode options -> Individual apps and unselect KurobaEx in the app list, this way you can still keep dark mode enabled globally.

**Comment by baraa272** [comment]
Turn off dark theme for specific apps in phone settings 
![Uploading Screenshot_2021-05-30-18-36-03-833_com.android.settings.jpg…]()

**Comment by baraa272** [comment]
Turn off dark theme for specific apps in phone settings
![Screenshot_2021-05-30-18-36-03-833_com android settings](https://user-images.githubusercontent.com/32843097/120110437-22dad300-c176-11eb-8890-28ecda880dd2.jpg)

**Comment by K1rakishou** [comment]
I guess the problem was in Xiaomi's forced dark mode? Didn't see any similar reports recently so I'm going to close this.
