### ISSUE TITLE
[Enhancement] Support for exporting threads into local storage

### ISSUE THREAD

**Issue by ashut0shk** [K1rakishou/Kuroba-Experimental#347]
Hi 

Please add feature to export a thread into local filesystem. For reference, that is available in [Overchan](https://github.com/AliceCA/Overchan-Android), as well as in [Dashchan](https://github.com/Mishiranu/Dashchan).

The standard approach could be to have it exported in a html file with corresponding folder for resources, or probably a zip. You can prefer select the best suited way.

Please accept apologies if this is already addressed.

E1: a word

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/d78d6790d2b02d774f5cf227ebf7b9643fc49b99
