### ISSUE TITLE
[Bug] Can't open archive threads from previews

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#350]
When clicking on the arrow in the preview popup, you are not asked if you want to open the thread and nothing happens
Video: https://imgur.com/a/Uby86Qs

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/85baa16ec64da32c6bc5a387ef97fb8978a55e3c
