### ISSUE TITLE
App OOMs and crashes on startup if too many threads are bookmarked.

### ISSUE THREAD

**Issue by tidux** [K1rakishou/Kuroba-Experimental#352]
Steps to reproduce:

1. Bookmark 50+ image-heavy threads on device with 4GB RAM.
2. Reboot device to forcibly clear memory.
3. Open app.
The app will hang at the initial loading screen and then exit.  It takes forcibly clearing all app data to clear this problem, since the directory where this is stored is not filesystem accessible to other apps.

**Comment by K1rakishou** [comment]
What version?

**Comment by tidux** [comment]
0.7.5

**Comment by K1rakishou** [comment]
Yeah, this is already fixed in 0.7.6

**Comment by tidux** [comment]
Sweet, looks like that hit F-Droid today so I'll take a look.

**Comment by tidux** [comment]
0.7.6 works.  Thanks.
