### ISSUE TITLE
Report "Catalog font is too tiny, board selection font too big"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#355]
UUID: 395ff30b588eef691ee1aaa17a3767a9
Build flavor: stable
Version name: v0.7.6
OS info: Android 11, sdk version: 30
Report description: the font size is too small in catalog, and the size doesn't match with the font size in threads so if I increase font size, the font size in threads then becomes too large. In Kuroba the font size is the same in threads and catalog. Here's KurobaEX and Kuroba both set to font size 14:
https://i.imgur.com/pd0poFP.jpg

Also the font in board selection is massive for some reason, here's KurobaEX and Kuroba, both at font size 14 again:
https://i.imgur.com/p47yOs8.jpg

this odd mix of different font sizes (tiny in catalog, regular in threads, huge in board menu) just looks ugly and inconsistent, it would be better if the font size was more consistent through the app.

**Comment by K1rakishou** [comment]
It's supposed to be like this. The font gets smaller if you set catalog to 3+ columns.

**Comment by barabraa** [comment]
>The font gets smaller

I don't think that makes sense, I've adjusted the font to the size that is the most comfortable for me to read in threads, but if I want to keep the 3 column catalog (my preferred setting) it then makes the text in catalog uncomfortably small to read. The font size I've set is the size I want, it should remain consistent thorough the app. I get that you're making the text smaller to show more of the OP post but there's already board mode and staggered catalog mode that shows the entire OP post so I don't think that is necessary.

Maybe a separate font size setting for catalog would be a solution? You can have the current behaviour be an "auto" option and give the option to choose another font size manually.

What is the reason for the huge font in the board menu? I don't really see why it has to be so big relative to other text in the app.

**Comment by K1rakishou** [comment]
This was originally introduced in Kuroba, I just changed it a little bit so it's applied when you have set 3+ column catalog (6 or something like that on tablet) instead of when the size of a single column is too small. But maybe it should be removed, yeah, because if you want to read more text you are supposed to be using "board" mode. 

>What is the reason for the huge font in the board menu? I don't really see why it has to be so big relative to other text in the app.

No real reason, probably it seemed fine to me when I was developing that view.

**Comment by K1rakishou** [comment]
Changed a little bit in https://github.com/K1rakishou/Kuroba-Experimental/commit/76b575df88b4fce56515c698c72e8e2fab2877cf
