### ISSUE TITLE
[Xiaomi] Report "Text selection cursor drag "button" is ugly and too big"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#359]
UUID: 650a383284d5dac7993f00be16e2dce5
Build flavor: stable
Version name: v0.7.6
OS info: Android 11, sdk version: 30
Report description: The text selection cursor drag "button" is ugly and too big, it's hard to even tell where the text selection starts and ends. Every other app just uses the stock Android style, I don't think this is something that this app should change.
https://i.imgur.com/khTUXWx.jpg

**Comment by K1rakishou** [comment]
This is most likely your vendor's system customization bug because I don't change those handles, I only change the color (via hacks).

**Comment by barabraa** [comment]
It's a Xiaomi phone.

> I don't change those handles, I only change the color (via hacks).
If the handles need a hack to change the color then maybe it's better to not change it?

**Comment by K1rakishou** [comment]
Oh wait, you are using Android 11. There is a legal way to do that in Android 10+, which I'm using, so it's probably some kind of weird behavior on xiaomi phones.

https://github.com/K1rakishou/Kuroba-Experimental/blob/32528e24721eab4037ffb340b1fca968bc8008e1/Kuroba/app/src/main/java/com/github/k1rakishou/chan/utils/ViewUtils.kt#L83

**Comment by barabraa** [comment]
Maybe you could detect if the phone is a Xiaomi / running MIUI and disable that feature in that case?
