### ISSUE TITLE
Report "Pull down to refresh doesn't work in catalog"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#360]
UUID: 96c01d268110372a684268d228257eb9
Build flavor: stable
Version name: v0.7.6
OS info: Android 11, sdk version: 30
Report description: Pull to refresh does not work in catalog, only in threads.

**Comment by K1rakishou** [comment]
I've seen multiple similar reports but I can't reproduce this. It works for me. It's probably a combination of settings that causes this. Need more info.

**Comment by barabraa** [comment]
I noticed pull to refresh also works in board mode, it's only when you set it to catalog mode it stops working.

**Comment by K1rakishou** [comment]
Yeah, I tried both catalog modes and it works for me. Must be something additional.

**Comment by K1rakishou** [comment]
Alright, this was probably the check I added that disallows using it when the reply layout is opened. Probably was not a good idea to add it in the first place.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/995e68165da6c8b124c8cd74f8b64d064e47fa3c
