### ISSUE TITLE
Typo in hamburger menu

### ISSUE THREAD

**Issue by willywoo-cyber** [K1rakishou/Kuroba-Experimental#363]
There's a minor error in the main hamburger menu. "It's" should be "its". It would look better without " its" since the item below doesn't include it (ie "by url/by ID"). SS attached.
![IMG_20210426_121315](https://user-images.githubusercontent.com/83234895/116116369-13ed9600-a689-11eb-9e5b-f35bd3a0761d.jpg)

**Comment by K1rakishou** [comment]
Updated in https://github.com/K1rakishou/Kuroba-Experimental/commit/7f18914d0870d2f8196031c8c27cf0318a034713
