### ISSUE TITLE
Image font resolution to big 

### ISSUE THREAD

**Issue by PLAYERUNKNOWNHatsune01** [K1rakishou/Kuroba-Experimental#364]
The image font resolution is to big that the caption of the post was on below! Why?

My phone screenshot

![Screenshot_20210428_004858](https://user-images.githubusercontent.com/75108124/116281131-fa00a000-a7bb-11eb-83e9-b4609db8dfbe.jpg)

On fdroid 

![Screenshot_20210428_004439_org fdroid fdroid](https://user-images.githubusercontent.com/75108124/116281240-17356e80-a7bc-11eb-90ff-f0b9de68399a.jpg)

Is there a way to change it? Because it seem I can't find it on the settings

**Comment by K1rakishou** [comment]
>Is there a way to change it? Because it seem I can't find it on the settings

No there is no way to change it back. You can make the thumbnail smaller, though, so it will take less space.

**Comment by PLAYERUNKNOWNHatsune01** [comment]
> > Is there a way to change it? Because it seem I can't find it on the settings
> 
> No there is no way to change it back. You can make the thumbnail smaller, though, so it will take less space.

Ohh. But sir can you fix it on next update?

**Comment by K1rakishou** [comment]
This was an intentional change, so there is nothing to fix.

**Comment by PLAYERUNKNOWNHatsune01** [comment]
> This was an intentional change, so there is nothing to fix.

I understand sir. But kinda like not good tho sir it's just my opinion

**Comment by K1rakishou** [comment]
~~Well if you don't like then I guess I have no other choice but to rewrite it.~~
JK.

**Comment by PLAYERUNKNOWNHatsune01** [comment]
> Well if you don't like then I guess I have no other choice but to rewrite it.

Wow! Really sir! Thank you so much sir! (*♡∀♡)
