### ISSUE TITLE
The option to save WebM as Mp4. 

### ISSUE THREAD

**Issue by obj44** [K1rakishou/Kuroba-Experimental#365]

**Comment by K1rakishou** [comment]
You mean reencoding a webm into mp4? Or just changing the extension?

**Comment by obj44** [comment]
changing the extension. a lot of apps don't support WebM, like Facebook's Messenger and Telegram.

adding the option to save WebM videos as MP4 in the settings would be a great addition.

2chan [android app](https://play.google.com/store/apps/details?id=jp.andosan.futabaviewer) already has this feature.
