### ISSUE TITLE
Make the logo display more nicely

### ISSUE THREAD

**Issue by crisalis2** [K1rakishou/Kuroba-Experimental#367]
As you can see in the image below, Clover didn't display the logo "nicely" (at least for my tastes), then Kuroba fixed it, then KurobaEx went back to Clover's style. Most apps today, and all well-known apps, display their logos like Kuroba. Can you fix this? Thanks.

![Screenshot](https://user-images.githubusercontent.com/65630147/116817953-22482000-ab69-11eb-9a8b-88265a6e212e.png)

(And by the way, can you consider removing the "-fdroid" from the name in the F-Droid version?)

**Comment by K1rakishou** [comment]
Sure, once someone makes one. There is already an issue for that, btw: https://github.com/K1rakishou/Kuroba-Experimental/issues/336

**Comment by crisalis2** [comment]
Ah, okay, sorry, only searched for "logo" in the issues, should have searched for "icon" too. Will close now.
