### ISSUE TITLE
[Bug] Posting To Lainchan Broken

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#368]
Posting to Lainchan is broken, the error says something about value "NONE" after trying to submit the post.
Tried on sec and technology.

Android 10, v0.82 fdroid

**Comment by K1rakishou** [comment]
Open Reply Layout -> longtap the "send reply" button -> "Attempt to post without captcha"

**Comment by K1rakishou** [comment]
Some adjustments added in https://github.com/K1rakishou/Kuroba-Experimental/commit/294e78b557fb18feffdc7d82690bd89b1e6951a5

**Comment by seniorm0ment** [comment]
Waa the reply layout captcha option added on a newer release? or available on 0.8.2 (fdroid)

**Comment by K1rakishou** [comment]
No it's already in 0.8.2

**Comment by seniorm0ment** [comment]
i'm not seeing that option? where is reply layout?

**Comment by K1rakishou** [comment]
![image](https://user-images.githubusercontent.com/10332458/117572707-c3d8ef80-b0dc-11eb-89c2-53b34e7a0ff5.png)

**Comment by seniorm0ment** [comment]
Ah.. that is hidden. 
Thank you
