### ISSUE TITLE
Archive Not working

### ISSUE THREAD

**Issue by rickninja765** [K1rakishou/Kuroba-Experimental#384]
Archiveofsins is not showing in search bar.![Screenshot_2021-05-11-10-41-05-88.jpg](https://user-images.githubusercontent.com/61545131/117761692-7035e580-b245-11eb-869b-50299d5dbb6e.jpg)

**Comment by K1rakishou** [comment]
Because it does not support search in the API.
https://github.com/4chenz/archives.json/blob/gh-pages/archives.json#L92
