### ISSUE TITLE
[Feature Request] Enable thread/filter watchers manually only

### ISSUE THREAD

**Issue by crisalis2** [K1rakishou/Kuroba-Experimental#387]
Right now you can only set the watchers to update automatically in user-defined intervals of seconds/hours. 

I would like to set thread/filter watchers to never update automatically either in background or foreground, and still be able to trigger the updates manually in the "Bookmarks" section of the bottom drawer with the pull-to-refresh gesture (both for updating the bookmarked threads and for bookmarking new threads that match the filters).

**Comment by K1rakishou** [comment]
I mean you can set it to 24 hours which is pretty much nothing if you worry about the battery life or traffic.

**Comment by crisalis2** [comment]
I'm still interested in this, but okay. In any case, there is other issue. I think updating bookmarked threads does work on demand when I pull-to-refresh, but the filter watches to bookmark threads that match don't seem to work on demand when I pull-to-refresh - for example I remove from bookmarks a thread that matched my filter, then pull-to-refresh inside the filter watches and nothing happens, the matching thread isn't bookmarked.

**Comment by K1rakishou** [comment]
Alright, I think the filter watches not being updated when manually triggering update was caused by a bug that was fixed here https://github.com/K1rakishou/Kuroba-Experimental/commit/db197b298d454327e365c587b9d7ae6e10127818
