### ISSUE TITLE
 [Feature Request] Option to sort posts inside a thread by the number of replies they have

### ISSUE THREAD

**Issue by crisalis2** [K1rakishou/Kuroba-Experimental#389]
This is useful in general to find the "best" inside a thread. For example, in threads about images/webm you could quickly find the "best" ones.

**Comment by K1rakishou** [comment]
There was added a new thread scrollbar mark option which marks "Hot posts", in other words posts with lots of replies to them. So probably no need for this feature anymore.

**Comment by crisalis2** [comment]
Kuroba added this, don't know if you can just "copy" it, just saying:

https://github.com/Adamantcheese/Kuroba/issues/916

https://github.com/Adamantcheese/Kuroba/commit/4d40954b137ce653e9cf1e729de9eb11efa5294c
