### ISSUE TITLE
Updater doesn't launch the apk

### ISSUE THREAD

**Issue by lsvy97** [K1rakishou/Kuroba-Experimental#393]
Apk doesn't launch automatically after download and shows the error. Have to launch a copy of apk manually.

LeEco Le 2, Android 6.0.1

Screenshot of the error:

![Screenshot_2021-05-14-09-09-20](https://user-images.githubusercontent.com/32693465/118210554-b9c83f80-b494-11eb-9d68-a598a2ef49b1.jpg)

It also crashed after that, here's a log:

https://pastebin.com/3PX4KcUg

**Comment by K1rakishou** [comment]
Honestly I have no idea because I didn't change the updater for god knows how much time and it works for me. The seconds crash is something completely different.

**Comment by 1sad** [comment]
same issue android 5.0.2
it happened on old kuroba too I'm pretty sure, but old kuroba dev worked properly
