### ISSUE TITLE
Offline thread downloader

### ISSUE THREAD

**Issue by cramrafalgue** [K1rakishou/Kuroba-Experimental#395]
Hi, sorry if this has already has been asked (didn't find anything in record)

Where has the automatic thread downloader functionality gone? I recall being able to bookmark a thread (or have one flagged automatically via a filter) and it would download the comments and files to a folder on phone for offline viewing (and not simply caching temporarily) .

Currently,  the thread watcher doesn't allow this functionality? Please let me know if I am doing things wrong.

**Comment by K1rakishou** [comment]
It was removed before the very first release. But there are plans to bring it back. Probably in v0.10.x
And there is already an issue for that: https://github.com/K1rakishou/Kuroba-Experimental/issues/347

**Comment by K1rakishou** [comment]
I'm going to close this issue since it's a duplicate of another one.
