### ISSUE TITLE
can't select text

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#398]
it was like this for a while now, don't remember which version changed a lot of gestures

https://user-images.githubusercontent.com/23120024/118370287-b5dd1000-b5af-11eb-87f5-61f46ac30ae1.mp4

**Comment by K1rakishou** [comment]
This is very weird. I tried to reproduce it on emulator with Android 5 and 6 and it works fine. Most likely some weird device quirk. Don't even know whether I will be able to fix it without the actual device where it's happening. What's the phone model, anyway? Maybe I'll buy one of these.

**Comment by 1sad** [comment]
Samsung galaxy alpha
I mean its old as fuck but text selection did work many versions ago
also it works in the quote linked popups fine, just not the actual thread

**Comment by raisehero** [comment]
https://user-images.githubusercontent.com/71166028/126037342-870ef165-c5fc-4339-9feb-d27fbf8b01cb.mp4

Device: Xiaomi Redmi Note 8
MIUI version: MIUI 12.5 by xiaomi.eu 21.3.17 Beta
Android Version: 11

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/71166028/128521643-f69427ef-d58f-46bc-9f96-5eaf9a1d1b29.mp4

Device: Xiaomi Redmi Note 8 (ginkgo)
ROM/MIUI version: MIUI 12.5 by xiaomi.eu 21.3.17 Beta
Android Version: 11

@K1rakishou Selecting text doesn't work. Trying to tapping and holding the text (red circle with smaller white circle) opens the post context-menu/options.

**Comment by K1rakishou** [comment]
@raisehero It's been changed to doubletap for a couple of months now.

**Comment by ghost** [comment]
Sorry, you were right.
