### ISSUE TITLE
[Feature Request] Hydrus ClientAPI support

### ISSUE THREAD

**Issue by Wyrrrd** [K1rakishou/Kuroba-Experimental#403]
It would be useful to send threads or single images directly to a Hydrus Network server via [ClientAPI](https://hydrusnetwork.github.io/hydrus/help/client_api.html)

The context menu options could be hidden if no API key is set, to not overwhelm users.

**Comment by K1rakishou** [comment]
If this thing has an Android client that supports sharing then you already should be able to do that.

**Comment by K1rakishou** [comment]
Actually it would be a much better idea. Someone writes a client that allows stuff getting shared into it and then relays that stuff into the Hydrus. This way other applications can use it too and I won't even have to do anything.

**Comment by Wyrrrd** [comment]
It doesn't have one, but I agree, that would solve it not just for Kuroba, but for every app. Maybe I'll take a look at it myself.

**Comment by Wyrrrd** [comment]
I found an easy solution, there is an app on Fdroid and GPlay called [HTTP Request Shortcuts](https://http-shortcuts.rmy.ch/).
The app supports sharing into it and just works.

For anyone stumbling on this, here is an [importable shortcuts file](https://github.com/Wyrrrd/send-to-hydrus). You only have to set the Variable `hydrus_url` to the URL of your ClientAPI, request an API key (or set it manually via `hydrus_api_key`), and you are ready to go.

**Comment by K1rakishou** [comment]
Nice.
