### ISSUE TITLE
no "view in archive" in the post context menu

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#405]
archives open only from the thread menu, not post menu anymore, and don't track the progress of the thread
so if you were half way down, opening archive brings you to top of the thread in the archive

would be nice to be able to track which posts were yours in the archive, the same way normal threads do too

and the "preview" of the archive thread itself seems a bit redundant, since you know you're opening this thread anyway, but thats just my opinion

**Comment by K1rakishou** [comment]
Actually it should scroll you to the post you are currently above. Probably it's a bug.

**Comment by K1rakishou** [comment]
Added two post menu options: preview in archive and open in archive. The second one will scroll you to the selected post.
https://github.com/K1rakishou/Kuroba-Experimental/commit/c23beb3b5e686f405fb56311eda4d94faed407b5
