### ISSUE TITLE
QOL request, save as duplicate in the duplicate popup

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#412]
currently, in the popup, you can only use override or leave local
but if the name is the same but content different you have to go into the save settings and choose save as duplicate, then save  then settings again and change back

maybe if you could by selecting both local and server file tickboxes in the duplicate popup, save as duplicate?

would also be nice to have an option to check filesize so if name is same but filesize different, it would save as duplicate name too

also an option for the popup to appear right away, when it detects a duplicate, instead of spamming the pulldown menu (if you save a lot of images) would be really nice

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/631c8fd4c8f4b6281476a859da4286f6db90292a
