### ISSUE TITLE
No "reply" notification in bookmarks

### ISSUE THREAD

**Issue by baraa272** [K1rakishou/Kuroba-Experimental#413]
Hi dev
So I bought a new phone which is Poco X3 pro (Android 11 miui 12) and installed kuroba ex since kuroba Dev was having problems with storage and all and EX is working pretty much perfectly else one small bug ^^; 
Even though the thread watcher is enabled the never gets red colour when I have a reply to my posts ?? Nor I get a notification about that reply since I enabled that feature 
I actually enabled EX to autostart and changed some settings but still it won't notify me about replays to my posts 
So any help ?

**Comment by K1rakishou** [comment]
What version? Does it not work only when the app is in background (or closed) or is it the same when you are using the app and someone replies to your posts?

**Comment by baraa272** [comment]
Let me test something

**Comment by baraa272** [comment]
Ok in foreground I got notification but the problem the bookmark icon never turn red since I mostly depend on bookmark icon on the bottom all the time and this is all in foreground background isn't working even though I have autostart on for kuroba ex 
Also more info I migrated a kuroba file if that helps

**Comment by baraa272** [comment]
![Uploading Screenshot_2021-05-29-14-29-03-858_com.github.k1rakishou.chan.jpg…]()

**Comment by baraa272** [comment]
![Screenshot_2021-05-29-14-29-03-858_com github k1rakishou chan](https://user-images.githubusercontent.com/32843097/120068715-cd75c780-c08a-11eb-8706-af418214d8b8.jpg)

**Comment by baraa272** [comment]
Background isn't that important for now 
All I want to understand why the bookmarks button doesn't turn red even though there is a you ( I disabled dark theme for kuroba ex so system doesn't conflict with the app)

**Comment by baraa272** [comment]
It appears it's a problem with kuroblack theme because I reset the theme and the bookmarks turned to red

**Comment by baraa272** [comment]
Sorry for any annoyance

**Comment by K1rakishou** [comment]
I think it's because of the theme you are using. The color of the badge is the same as the color of the Floating Action Button (accentColor). They both have the same color.

**Comment by K1rakishou** [comment]
You can change the color by yourself by editing the theme. Look for "accent_color" and change it to red, for example.

**Comment by baraa272** [comment]
Ok I'll change it thanks

**Comment by baraa272** [comment]
I'll upload a fixed version

**Comment by baraa272** [comment]
![Screenshot_2021-05-29-15-00-51-988_com github k1rakishou chan](https://user-images.githubusercontent.com/32843097/120069456-bdf87d80-c08e-11eb-9f5e-0e7a930fa028.jpg)
Fixed

**Comment by baraa272** [comment]
Made a pull request

**Comment by baraa272** [comment]
You can close the issue 
Also thanks for assistance
