### ISSUE TITLE
My posts highlight 

### ISSUE THREAD

**Issue by baraa272** [K1rakishou/Kuroba-Experimental#414]
Dear Dev 
I know this is a simple thing but I have already read themes documents and everything and still can't figure out this thing 
Kuroba ex :
![Screenshot_2021-05-29-18-39-37-483_com github k1rakishou chan](https://user-images.githubusercontent.com/32843097/120076280-7af9d280-c0ad-11eb-92e0-3ba64aa155b8.jpg)
Kuroba Dev : 

![Screenshot_2021-05-29-18-08-34-857_com github adamantcheese chan dev](https://user-images.githubusercontent.com/32843097/120076299-8ea53900-c0ad-11eb-90cd-b027ff4cb52c.jpg)
How do I make the highlight of my posts in kuroba ex similar to kuroba Dev in screenshot ???

**Comment by K1rakishou** [comment]
It's either post_highlighted_color or post_saved_reply_color. The former one is used by the app for things like highlighting a thread OP in the catalog that is currently opened. The latter one is used for your replies or for posts you marked as your replies.

**Comment by baraa272** [comment]
Ok let me test something

**Comment by baraa272** [comment]
Ok it was saved reply colour 
I proposed a change

**Comment by baraa272** [comment]
you can close the issue dev
