### ISSUE TITLE
Gesture exclusion zones stopped working in media viewer

### ISSUE THREAD

**Issue by ChillHorse** [K1rakishou/Kuroba-Experimental#427]
In V0. 9. 1. 11669 the gesture exclusion zones don't work as intended. You can reset or move them but they will not prevent you from not triggering the back gesture.

**Comment by K1rakishou** [comment]
Oh yeah, it's a separate activity now. That's why it doesn't work.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/34ae45b5b0154465c36c8a9fc3f63db7d270a910
