### ISSUE TITLE
Media viewer and image gestures 

### ISSUE THREAD

**Issue by baraa272** [K1rakishou/Kuroba-Experimental#430]
So today I updated since I was on 0.8.9 and latest is 0.9.3 but to my surprise the app have a new media viewer 
But actually it have problems 
1. Where are image gestures now ?
2. Where are advanced options of image viewer ? When I click the 3 dots only options are spoiler and transparency ???

**Comment by K1rakishou** [comment]
1. Tap the image and start dragging it.
2. Longtap the image.

**Comment by baraa272** [comment]
Is there a way to bring back tap on image close it ???
Like in previous versions instead of going fullscreen?

**Comment by K1rakishou** [comment]
No. It was only there because fullscreen was buggy in some rare cases. Now it should work fine.

**Comment by baraa272** [comment]
Jeez instead of just tapping the image itself to close and return to thread I have to press either back button on soft nav bar or press on very top icon every time ?

**Comment by K1rakishou** [comment]
There are swipe up/down gestures to close the media viewer.

**Comment by baraa272** [comment]
I hope I don't sound annoying or anything but just a tap always beat a swipe In anything 
Unless I'm forced to get used to swipe ?

**Comment by K1rakishou** [comment]
Literally in most media viewers I've used there is some kind of a swipe gesture (either up or down) to close the viewer. It's like the default gesture for media viewers in Android nowadays. And tap is usually used to toggle fullscreen mode.

**Comment by baraa272** [comment]
Ok guess I need to get used to it
