### ISSUE TITLE
[Feature] Vibrate On File Save

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#436]
Requesting vibration feedback when you save a file.
If not the button, at least when you swipe down on a file.

**Comment by K1rakishou** [comment]
Yeah this is actually already implemented and will be in the next release.
https://github.com/K1rakishou/Kuroba-Experimental/commit/b0903bfcc387c2654048e76f4b1866b7b94c805a#diff-cf2b93d9bb97a88323c25525f54c37eb17e412da5edcb5b5ad004020a390eb33R335

**Comment by K1rakishou** [comment]
I'm closing this issue since it's already implemented.
