### ISSUE TITLE
Add support for 2ch.hk global search

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#440]
Search url example:
https://2ch.hk/makaba/makaba.fcgi?task=search&board=mobi&find=poco%20x3&json=1

**Comment by K1rakishou** [comment]
???
There is already thread search function. There is also global search (for 4chan and some archives).

**Comment by acimanx** [comment]
Please try to repeat the following steps yourself:

1. Open the board /mobi/ on 2ch.hk
2. Use top search button in kurobaex
3. Write example: "poco x3" (without quotes)
4. You'll receive around 3 results that match this words in thread opener
5. Follow the link https://2ch.hk/mobi/ or open the /mobi/ board in dashchan app
6. Use website search or app top search button
7. Write example: "poco x3" (without quotes)
8. You'll receive around 47 results counting thread openers and comments

**Comment by K1rakishou** [comment]
Didn't know there was API for global search.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/d26621042a3aeeadbf992bf16a69ac8017359a58
