### ISSUE TITLE
[Request] Cache Watch Threads Automatically

### ISSUE THREAD

**Issue by zero77** [K1rakishou/Kuroba-Experimental#441]
Can you give the option to cache watch threads automatically and not auto clear that cache.
So, that you can still view all post content even if the thread is removed.

**Comment by K1rakishou** [comment]
You probably want thread downloading which is planned but not implemented yet (see https://github.com/K1rakishou/Kuroba-Experimental/issues/347 ).
Alternatively you can enable post database caching but it doesn't cache threads in background, only when you are using the app.

**Comment by zero77** [comment]
Thanks, would either of these allow for separate cache clearing, so that cache can be cleared without removing saved content.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/d78d6790d2b02d774f5cf227ebf7b9643fc49b99
