### ISSUE TITLE
App Will Freeze If You Use Gesture To Download Image

### ISSUE THREAD

**Issue by PLAYERUNKNOWNHatsune01** [K1rakishou/Kuroba-Experimental#442]
I just notice it when I try to download some image and the app is freeze you can't touch anything. Here's a video

https://streamable.com/0646he

But when using gesture to close/exit to that image the app is fine just the gesture

**Comment by K1rakishou** [comment]
Already fixed in v0.9.5. If you are using FDroid version you will have to wait until it's updated (probably tomorrow).
https://github.com/K1rakishou/Kuroba-Experimental/blob/develop/fastlane/metadata/android/en-US/changelogs/905.txt#L11

**Comment by PLAYERUNKNOWNHatsune01** [comment]
> Already fixed in v0.9.5. If you are using FDroid version you will have to wait until it's updated (probably tomorrow).
> https://github.com/K1rakishou/Kuroba-Experimental/blob/develop/fastlane/metadata/android/en-US/changelogs/905.txt#L11

ohh thanks ^w^
