### ISSUE TITLE
Decoder init failed

### ISSUE THREAD

**Issue by Pentaphon** [K1rakishou/Kuroba-Experimental#443]
Stock Motorola ROM running Android 10 on a Snapdragon 460 device. 

Link to post: https://boards.4channel.org/tv/thread/152359531#p152361921

![decoder](https://user-images.githubusercontent.com/49374058/122058658-b16b6900-cda0-11eb-9ec4-6badfffadf7a.jpg)

**Comment by K1rakishou** [comment]
Works in the emulator. Most likely a bug in the video codecs supplied by the vendor. Can't fix it.
