### ISSUE TITLE
Board level thread OP image scroll is always in Bumped sort order

### ISSUE THREAD

**Issue by darvilp** [K1rakishou/Kuroba-Experimental#444]
Swiping through board level thread images is always using Bump Order instead of the selected board level thread sorting option. 

To reproduce set the board's thread sort to 'Reply Count' (or any non-Bump option), open a thread image and swipe left or right through images.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/76237ce28ec228dc6f8823e6b4f541ae6b5bf9e6
