### ISSUE TITLE
Some links give error when trying to open

### ISSUE THREAD

**Issue by cuteasci** [K1rakishou/Kuroba-Experimental#445]
![Screenshot_2021-06-17-01-56-18-256_com github k1rakishou chan beta_1](https://user-images.githubusercontent.com/59581277/122305846-26a97c00-cf10-11eb-9753-b2adc501bfe7.jpg)

If you "copy value", it gives you this "https://2ch.hk/djdhd"

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/1b448442478be9289fa644752b09c7bb37ddf740
