### ISSUE TITLE
Option to always open different app by default when attach a file

### ISSUE THREAD

**Issue by cuteasci** [K1rakishou/Kuroba-Experimental#446]
I always use gallery app to attach images.

So instead of opening Files and then opening gallery, it would be nice to open an app you choose right away

**Comment by K1rakishou** [comment]
If you can't select the gallery in the application chooser that means it doesn't support that action.

**Comment by cuteasci** [comment]
You are right. I remember I was able to do that some time, probable on a GSI firmware, and MIUI doesn't let you do that. 

But maybe is it possible to implement built in image picker? Something like that? 

https://github.com/Dhaval2404/ImagePicker

**Comment by K1rakishou** [comment]
Why would I want to do that when it's way easier to just let the user use whatever file picker he wants (Literally everyone benefits from doing  it this way). And It won't even probably work on Android 11+.  You just need to install a gallery app that supports [ACTION_GET_CONTENT](https://developer.android.com/reference/android/content/Intent#ACTION_GET_CONTENT) (I personally use Simple Gallery Pro from FDroid).

**Comment by cuteasci** [comment]
I do use Simple Gallery but still it doest appear in file picker 

![Screenshot_2021-06-17-20-07-22-525_android_1](https://user-images.githubusercontent.com/59581277/122443209-062d0080-cfa8-11eb-8c49-b72c29e0b741.jpg)
![Screenshot_2021-06-17-20-07-24-409_android_1](https://user-images.githubusercontent.com/59581277/122443229-0a591e00-cfa8-11eb-9430-34c554c75267.jpg)

**Comment by K1rakishou** [comment]
That's very strange. Maybe it's somehow disabled somewhere in the OS settings? Can't say for sure because it works fine for me. Maybe reinstalling it will help?
