### ISSUE TITLE
4chan pass not respected

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#450]
UUID: b8e980380b136a2b88133a316f5b7024
Build flavor: stable
Version name: v0.9.6
OS info: Android 11, sdk version: 30
Report description: Despite showing a success message after logging in with my 4chan pass, KurobaEx continues to present me with captchas.

**Comment by K1rakishou** [comment]
Longtap the send reply button and select "Post using passcode".

**Comment by ghost** [comment]
I think there should at least be some text about this after you log on with a 4chan pass, since it is confusing without checking the GitHub issue. Excellent software otherwise.

**Comment by K1rakishou** [comment]
Added more info about "Reply modes" to Login controller in https://github.com/K1rakishou/Kuroba-Experimental/commit/bd14c1e1a21cc8d8f3867448483102d8d36f18e1
