### ISSUE TITLE
Browse archive of entire board

### ISSUE THREAD

**Issue by Xenoslyce** [K1rakishou/Kuroba-Experimental#456]
Saw Clover (the app Kuroba is based on, as we all know) had this feature added in 2016.

Is this possible with Kuroba-Ex?

**Comment by K1rakishou** [comment]
You mean the built-in 4chan archive? Yeah it will be possible in v0.10.0

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/27640169f5f2ef504d58a00956bfed052d06b305
