### ISSUE TITLE
Report "No sound in webm's"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#457]
UUID: ac21d4ce66b11c4ed1fe5f5093e05537
Build flavor: fdroid
Version name: v0.9.6
OS info: Android 10, sdk version: 29
Report description: No sound in webm, has been a problem for many versions, mute/unmute doesn't work

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/71166028/126037342-870ef165-c5fc-4339-9feb-d27fbf8b01cb.mp4

Device: Xiaomi Redmi Note 8
MIUI version: MIUI 12.5 by xiaomi.eu 21.3.17 Beta
Android Version: 11

**Comment by K1rakishou** [comment]
@raisehero What am I supposed to see here?

**Comment by ghost** [comment]
I posted in the wrong issue, sorry.
