### ISSUE TITLE
Swipe up to close image causes 2-3 second "delay" before I can continue browsinf

### ISSUE THREAD

**Issue by reportthings** [K1rakishou/Kuroba-Experimental#461]
Hey K1rakishou you've helped me in the past and I am grateful, I love your app.  I understand you are busy with the new captcha and I don't want to take too much of your time. 

I posted an issue a couple months ago about the scrollbar.  You told me it was due to android gestures, so I enabled "Draggable Scrollbar" to fix it. And it worked perfectly, thank you again for that.

Today I updated to the latest f-droid release and noticed that I could no longer "tap" to close images.  I saw another issue posted by someone else, and you said this was intended.  

I'm ok with swiping up to close images, I can get used to that (even though I loved being able to "tap" them closed.

On to my problem: In the past, when I would "tap" an image closed, I could instantly start scrolling through the thread the image was in.

Now "Swiping" an image away causes a 2 to 3 second delay before I can scroll through a thread, open another image,  tap a post number to reply, etc. Basically 2-3 seconds before touches are recognized again. Is there anything I can do to lessen the delay before I can start scrolling or opening other images?  

The reason I brought up my first issue from months ago is because it was an Android gesture problem.  Swiping up falls into that category.  Yet tapping to close the image did not cause the delay, so was that not considered a gesture as well?  

Thank you for your time, I speak for many people when I say your work here is greatly appreciated.

**Comment by reportthings** [comment]
https://streamable.com/bs0bxa

Here is also a video showcasing what I am talking about

**Comment by K1rakishou** [comment]
Looks like the fade out animation is way slower than it's supposed to be. Maybe you somehow changed the animation speed in the Android developer settings?

**Comment by reportthings** [comment]
The only option I see that could relate is "animator duration scale". It was set to '1x' (default).  Changing it to off does not change anything inside KurobaEx. 

Also I don't know if this happened in the previous version either because I always tapped images to close before last night.

Any other info you require I'm happy to provide, thanks.

**Comment by reportthings** [comment]
Also, I just downloaded the beta version with the captcha changes, from github and the problem persists

**Comment by K1rakishou** [comment]
That's strange. I will probably add a setting to make the fade out animation 2-3 times faster.

**Comment by K1rakishou** [comment]
The animations' speed was increased in https://github.com/K1rakishou/Kuroba-Experimental/commit/af52e0b23a318a72e67040b279b0527e7e02dbe0

**Comment by modrei** [comment]
this seems to be present again in the newest version of the app on android 14, swipe up "locks" the responsiveness of the app until the fade animation finishes, can be avoided by clicking the android back button instead of swiping up
