### ISSUE TITLE
Captcha unnormal size 

### ISSUE THREAD

**Issue by baraa272** [K1rakishou/Kuroba-Experimental#463]
It seems like there is a cut off from captcha image
![Screenshot_2021-07-06-21-16-39-315_com github k1rakishou chan](https://user-images.githubusercontent.com/32843097/124648464-f49c9180-de9f-11eb-967b-a486dd091149.jpg)
There is 8 or 6 cut off from the picture of captcha 
If you can look at this

**Comment by baraa272** [comment]
The image fully display correctly in landscape mode

**Comment by awelton85** [comment]
I'm having the same issue, only slightly worse. All I can see are 4 characters at the most.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/5d862258e6c6eebeb8b96ff7e68721041b7959ea
