### ISSUE TITLE
Captcha is unreadable

### ISSUE THREAD

**Issue by 213a21g** [K1rakishou/Kuroba-Experimental#464]
![captcha](https://user-images.githubusercontent.com/87037553/124650842-7984ac80-de9a-11eb-9699-7d4acf0847a7.png)

Android version is 10

**Comment by K1rakishou** [comment]
Do you use forced dark mode or something like that?

**Comment by 213a21g** [comment]
![light mode](https://user-images.githubusercontent.com/87037553/124652712-b81b6680-de9c-11eb-9e6f-d24637caff91.jpg)

It looks like this with the light mode on

**Comment by K1rakishou** [comment]
There were some adjustments in v0.10.3

**Comment by 213a21g** [comment]
![captcha](https://user-images.githubusercontent.com/87037553/124673216-be1f4080-deb8-11eb-8576-83c14842590d.png)

It looks like this with dark mode on on v0.10.3

**Comment by K1rakishou** [comment]
That doesn't look like v0.10.3. It's not supposed to be magenta color and the slider should be below the input.

**Comment by K1rakishou** [comment]
I've made more adjustments in v.0.10.4 so try it out.

**Comment by 213a21g** [comment]
> 
> 
> That doesn't look like v0.10.3. It's not supposed to be magenta color and the slider should be below the input.

That was v0.10.3. I'm on v0.10.4 now and the scaling issue has been fixed, but the colored boxes are really annoying and it's difficult to read the text. Imo, it should match the white/gray background color.
![captcha](https://user-images.githubusercontent.com/87037553/124771802-bb196400-df3b-11eb-9e83-4f80276032f2.jpg)

**Comment by 213a21g** [comment]
![captcha](https://user-images.githubusercontent.com/87037553/124791057-03d91900-df4c-11eb-8a4f-1f401f6ae83c.png)

I found out that the captcha boxes are using the accent color from the themes, is this intentional? It's quite difficult to match the text with the slider because of it. I think the captcha should look exactly the same as it does on the site.

**Comment by K1rakishou** [comment]
Yes it was intentional and yes it doesn't look good on some dark themes where accent color is dark, too. I will probably add a checkbox to disable it.

**Comment by K1rakishou** [comment]
A setting to enable/disable colored background for slider captcha was added in https://github.com/K1rakishou/Kuroba-Experimental/commit/bcbb1b66726ebc03667828b8e77ce2d99b952425
