### ISSUE TITLE
Verify captcha with enter key

### ISSUE THREAD

**Issue by happapa** [K1rakishou/Kuroba-Experimental#466]
Currently, if you press the enter key after writing the captcha solution into the box, it inserts a new line. It would be better if hitting enter would work the same way as tapping the "Verify" button with your finger.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/5d862258e6c6eebeb8b96ff7e68721041b7959ea
