### ISSUE TITLE
Image viewer gestures similar to issue #435

### ISSUE THREAD

**Issue by cosmobooker** [K1rakishou/Kuroba-Experimental#467]
The new image viewer gestures are unreliable and unnatural. I agree with the poster of issue #435, having the option of reverting to the old method of swiping up for close and down for download would be more preferable than the new system of "grabbing" the image and dragging it to either 'close' or 'download'.

**Comment by K1rakishou** [comment]
There are three different methods you can use to download an image via media viewer. 
1. Drag the image to one of the actions.
2. Long-tap the image and click  download.
3. Tap the toolbar download icon.

Alternatively you can long-tap the image thumbnail and click download. This way you don't even have to open the media viewer.

**Comment by cosmobooker** [comment]
I understand the available methods. My complaint is with option 1. We used to be able to quickly save media by swiping down and close media by swiping up. These actions have been replaced by the new dragging method which I and others see as unnatural and uncomfortable to use. I (among others) would much prefer to revert the gesture back to the old method.

**Comment by K1rakishou** [comment]
Unfortunately I'm not planning to revert them back.

**Comment by cosmobooker** [comment]
I'm not asking for the new gestures to be discarded, the community and myself would just like the option of using the old gestures instead, perhaps through a setting toggle or something. Don't get me wrong, I sincerely enjoy this project, but this new change is very jarring for users such as myself.

**Comment by K1rakishou** [comment]
There are no old gestures anymore. The old code was completed rewritten and even trying to use it now won't work since it's 100% not compatible anymore. I'm not planning to reimplement them into the new code because I don't see the problem with the new gestures and I'm too lazy to bother. There are three different methods you can use to download an image. If none of them work for you then PRs are always opened (open source 'n shit).

**Comment by cosmobooker** [comment]
I understand your views on it, I'll figure something out. Thanks for the response and I look forward to future updates
