### ISSUE TITLE
Option to sort out boards or delete boards of specific site (4chan)

### ISSUE THREAD

**Issue by baraa272** [K1rakishou/Kuroba-Experimental#468]
Hi Dev and thanks for the continued work on this app 
Anyway after I updated today to 0.10.4 my board list of 4chan got messed up and to my surprise I can't delete boards in site settings or at least sort them alphabetically again?? 
Also its pain in the ass to sort them manually 
So can you look into it ?
![Screenshot_2021-07-07-15-52-06-887_com github k1rakishou chan](https://user-images.githubusercontent.com/32843097/124762335-755c9b80-df3b-11eb-9cec-667ad9bbfb21.jpg)
![Screenshot_2021-07-07-15-52-11-346_com github k1rakishou chan](https://user-images.githubusercontent.com/32843097/124762342-768dc880-df3b-11eb-9d80-76643679c2dc.jpg)

**Comment by K1rakishou** [comment]
>my board list of 4chan got messed up

Did that happen automatically or were you trying to add/remove boards?

> and to my surprise I can't delete boards in site settings

You can, you need to swipe the board to the right.

>at least sort them alphabetically again
>Also its pain in the ass to sort them manually

I guess this can be implemented.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/79f307285345ae7bc38b1d45a8f2a306e09990bb

**Comment by baraa272** [comment]
Thanks very much Dev
