### ISSUE TITLE
Captcha and case sensitivity 

### ISSUE THREAD

**Issue by 213a21g** [K1rakishou/Kuroba-Experimental#469]
The new 4chan captcha is case sensitive. The site is always using uppercase letters for the captcha, even when your caps lock is disabled.. Typing letters in the captcha box on KurobaEx should also be like that.

**Comment by K1rakishou** [comment]
Is it really though? I didn't notice that. I mean I don't think it's case-sensitive.

> The site is always using uppercase letters for the captcha, even when your caps lock is disabled

I think they did that intentionally so you don't have to worry about that stuff.

**Comment by 213a21g** [comment]
My bad, it's not case sensitive, it works with small letters on KurobaEx.
