### ISSUE TITLE
F-Droid stuck at version 0.9.6

### ISSUE THREAD

**Issue by Frogging101** [K1rakishou/Kuroba-Experimental#470]
No new builds have been added since June 17.
https://f-droid.org/en/packages/com.github.k1rakishou.chan.fdroid/

**Comment by K1rakishou** [comment]
That's how fdroid works. It managed to detect that the app should be updated to v0.10.5 but haven't done that yet for some reason.
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.github.k1rakishou.chan.fdroid.yml#L156

**Comment by crisalis2** [comment]
It is already at 0.9.8, you can close this.

**Comment by K1rakishou** [comment]
The bot will take care of it.
