### ISSUE TITLE
Report "No way to delete all empty comments"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#471]
UUID: 7bdbe751ca859f078c9baede1e56e471
Build flavor: stable
Version name: v0.10.5
OS info: Android 11, sdk version: 30
Report description: A toggle to select all saved posts or just the ones with empty comments would be good to tidy up that section

**Comment by K1rakishou** [comment]
There is a way now it was added in v0.10.5. Longtap them and then hit delete. But be aware that you won't receive (You)s for those posts and they won't be marked as yours too anymore.

**Comment by crisalis2** [comment]
Can you add a checkbox to select all the saved posts at once? If I wanted to just delete the entire database of saved posts for whatever reason, I would have to select them one by one (actually thread by thread, but still...) and that can be a very time-consuming task.

**Comment by K1rakishou** [comment]
This was actually already implemented.
https://github.com/K1rakishou/Kuroba-Experimental/commit/adab26f88b4394a7977455b11fa214a45e0a043e

**Comment by crisalis2** [comment]
~~I can't find a way to _select_ all the saved posts at once.~~
Edit: Oh, the option to delete everything at once was in the three-dots menu. Disregard my comment.
