### ISSUE TITLE
"Pick remote file" doesn't work

### ISSUE THREAD

**Issue by cordelia04m** [K1rakishou/Kuroba-Experimental#475]
Version: 0.10.6.13469

Android version: 10

I long-pressed the file picking area, then chose "pick remote file" and add the file URL to the file path menu. The downloading works fine, but it strucks on "decoding file preview" forever. 

I can't cancel it, the only way to cancel it is to force close the app. Upon open the app again, the unsuccessfully downloaded file shows "ERROR LOADING" in the file picking area. Posting with that error file results in the image doesn't get post.

**Comment by cordelia04m** [comment]
BTW this is the log I got after I force closed the app.

E/(19:54:46.390) KurobaEx | BackgroundUtils: ensureMainThread() expected main thread but got DefaultDispatcher-worker-1
E/(19:54:46.390) KurobaEx | BackgroundUtils: ensureMainThread() expected main thread but got DefaultDispatcher-worker-1
E/(19:54:47.455) KurobaEx | BackgroundUtils: ensureMainThread() expected main thread but got DefaultDispatcher-worker-12
E/(19:54:47.455) KurobaEx | BackgroundUtils: ensureMainThread() expected main thread but got DefaultDispatcher-worker-12
------------------------------
Android API Level: 29
App Version: v0.10.6.13469
Development Build: Release
Phone Model: HUAWEI MED-LX9
isLowRamDevice: false, isLowRamDeviceForced: false
------------------------------
Current layout mode: PHONE
Board view mode: GRID
Prefetching enabled: false
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: false
diskCacheSizeMegabytes: 512
prefetchDiskCacheSizeMegabytes: 1024
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: content://com.android.externalstorage.documents/tree/619F-1017%3AKurobaex
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: true
Watch foreground interval: 60000
Watch foreground adaptive interval: false
Background watcher enabled: false
Filter watch enabled: false
------------------------------

**Comment by K1rakishou** [comment]
I need the link you are trying to load.

**Comment by cordelia04m** [comment]
Here are some example  https://img3.gelbooru.com/images/63/48/6348e83dbd994e6ead6231d877761f1d.jpg
https://img3.gelbooru.com/images/de/a5/dea5a02b9539586dd8edeed31ae7a0d2.jpg
The same images from danbooru, this one works fine https://danbooru.donmai.us/data/original/de/a5/__gm_gundam_and_1_more_drawn_by_abysnova__dea5a02b9539586dd8edeed31ae7a0d2.jpg while this one doesn't work https://danbooru.donmai.us/data/original/63/48/__fighter_and_harukara_7th_dragon_and_1_more_drawn_by_naga_u__6348e83dbd994e6ead6231d877761f1d.jpg

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/1c8e1ab98c82bc971feb6a3231d8a8df8109d4dd

**Comment by cordelia04m** [comment]
Thank you.
