### ISSUE TITLE
Report "4chan captcha"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#479]
UUID: 603cf8dc3ceb8e0aa82b245aba1e62b4
Build flavor: stable
Version name: v0.10.6
OS info: Android 10, sdk version: 29
Report description: The captcha only requires me to verify, but I do it and try to post something and I get this message: "Failed to post, error=ERROR: This CAPTCHA is no long valid because it has expired. Please try again".
I can post without issues on other threads.

**Comment by K1rakishou** [comment]
So here is the captcha request
`D/(14:22:39.847) KurobaEx | suspendConvertIntoJsonObjectWithAdapter: url='https://sys.4channel.org/captcha?board=hr&thread_id=4118875'
`

Here the NOOP captcha is received and added into CaptchaHolder
`D/(14:22:41.547) KurobaEx | CaptchaHolder: A new token has been added, validCount: 1, solution = ChallengeWithSolution{challenge=noop, solution=<empty>}
`

Here we take that solution to put it into the response

`D/(14:22:42.971) KurobaEx | CaptchaHolder: getToken() solution=ChallengeWithSolution{challenge=noop, solution=<empty>}
`

Here we send the post request to the server which takes 5.7 seconds.
```
D/(14:22:42.971) KurobaEx | PostingServiceDelegate: callPostDelegate(SD{4chan}, TD{4chan/hr/4118875})
D/(14:22:42.980) KurobaEx | ReplyPresenter: processPostingStatusUpdates(TD{4chan/hr/4118875}) -> BeforePosting
D/(14:22:48.681) KurobaEx | HttpCallManager: Request (Chan4ReplyCall) execution success, took 5.70s
D/(14:22:49.220) KurobaEx | PostingServiceDelegate: SiteActions.PostResult.PostComplete(TD{4chan/hr/4118875}) failed to post, response=ReplyResponse{posted=false, errorMessage='Error: This CAPTCHA is no longer valid because it has expired. Please try again. 4chan Pass users can bypass this CAPTCHA. [Learn More]', siteDescriptor=SD{4chan}, boardCode='hr', threadNo=0, postNo=0, password='xxx', probablyBanned=false, requireAuthentication=false, rateLimitInfo=null, additionalResponseData=null}
```

And server tells us that the captcha is already invalid.

So it seems like there is nothing wrong with the app. It's either a server bug or I don't even know. As you can see it took 10 seconds for the whole `get captcha -> send reply` chain to be processed. The ttl of noop captcha should be the same as any other - 120 seconds.

**Comment by quickalias** [comment]
I could circumvent this issue by changing the captcha cookie, it only happens on the 4chan boards (not the 4channel ones).

**Comment by K1rakishou** [comment]
Seems like a 4chan bug then.

**Comment by tidux** [comment]
Captcha cookie is invalid and deleting one doesn't force a refresh.

**Comment by K1rakishou** [comment]
I think this might be happening because 4chan and 4channel are supposed to have separate cookies. So if you post on 4chan, get the cookie and then try to post on 4channel if will not allow you because the cookie is different. At least in the browser 4chan and 4channel have separate cookies.

**Comment by quickalias** [comment]
I am getting the same error on Kuroba-dev now (this time on 4channel boards instead of the 4chan ones), so it's looking like a 4chan/4channel bug.

**Comment by K1rakishou** [comment]
So I tried separating the cookie between two domains but it doesn't seem to help. And now I've noticed that the site only shows slider captchas for some reason. Solving multiple of them doesn't make them more simple. I have no idea wtf is going on.

**Comment by K1rakishou** [comment]
Alright. So this was actually a bug. 

- First of all 4chan and 4channel have separate cookies which was not handled by the app. This is now fixed.
- Second, the reply endpoint was always using the 4chan.org domain which, apparently, was incorrect too. This is not fixed as well (it now uses 4chan/4channel depending on the board).

I even managed to reproduce the exact same problem so it should be fixed now 100%

https://github.com/K1rakishou/Kuroba-Experimental/commit/976f28e17dc9ec24cceddeebc1769a638b93a6e7
