### ISSUE TITLE
Still alive thread goes archived after a while 

### ISSUE THREAD

**Issue by cuteasci** [K1rakishou/Kuroba-Experimental#483]
You need to reload manually so automatic loading goes back 

![Screenshot_2021-07-11-15-52-13-980_com github k1rakishou chan beta_1](https://user-images.githubusercontent.com/59581277/125195895-71dd5300-e260-11eb-8e5e-5aaee3c78938.jpg)

**Comment by K1rakishou** [comment]
Next time it would be really helpful to have the thread link.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/38858d29170be9c7b38255cdd0b7ebfc950d740e
