### ISSUE TITLE
Intermittent issues with new captcha

### ISSUE THREAD

**Issue by Dick-Kickem** [K1rakishou/Kuroba-Experimental#484]
Consistently running into an issue where the new 4chan captcha will not load when attempting to post and instead the message "java.lang.NullPointerException" is displayed. Issue seems to be completely random but makes the app virtually unusable for posting because for every two or three times it will actually display the captcha it gives me this error about 10 times. Quitting and restarting the app, restarting the phone and switching between mobile data and wifi does not help, it simply refuses to display the captcha unless it feels like it.

**Comment by K1rakishou** [comment]
Are you using the fdroid version? It lags behind too much. The latest version is 0.10.7 and fdroid is 0.10.3. That's how fdroid works and I can't do anything here. You can temporarily switch to a beta or regular release version.

**Comment by Dick-Kickem** [comment]
I downloaded it directly from GitHub as an apk.

**Comment by K1rakishou** [comment]
Then make sure you are using the latest version. "java.lang.NullPointerException" was fixed in like 0.10.4 or 0.10.5.

**Comment by Dick-Kickem** [comment]
Clearing the captcha cookies appeared to fix the issue, but I also updated to the latest version. I thought I had downloaded the latest one in the first place but it appears I was mistaken.
