### ISSUE TITLE
Option for the "Tap the post number to reply" setting to work even if reply layout is closed

### ISSUE THREAD

**Issue by crisalis2** [K1rakishou/Kuroba-Experimental#485]
This was changed recently. "To avoid accidental taps it now only works when reply layout is opened".

Well, I preferred the previous behavior. I never tapped it by mistake.

I remember that in Kuroba not only the post number itself counted as a tap, but all that line (I think), date included, and it did cause me to accidentally tap it and open the reply layout by mistake many times.

But KurobaEx made it so that the reply layout opened only when specifically tapping the post number, and it was fine. The post number is in the left side, for your right thumb to tap there you have to make it intentionally. At least that was my experience.

So I feel there was no need to change this to further protect against unintentional taps.

Now I'm forced to open the reply layout manually and then tap the post number to quote it. It makes me work more. I'd like if there was an option to bring back the previous behavior.

**Comment by K1rakishou** [comment]
>But KurobaEx made it so that the reply layout opened only when specifically tapping the post number, and it was fine. The post number is in the left side, for your right thumb to tap there you have to make it intentionally. At least that was my experience.

Yeah, you are right. For some reason I though there is the same problem as in regular kuroba where the whole line is clickable but it turns out it's not. So I'm gonna revert it back.

**Comment by K1rakishou** [comment]
https://github.com/K1rakishou/Kuroba-Experimental/commit/4a9ee9c37f73333a445b5185694f5267ca0bab27
