### ISSUE TITLE
Alive thread and 'archived' status

### ISSUE THREAD

**Issue by 213a21g** [K1rakishou/Kuroba-Experimental#486]
When the thread is still alive, it'll say the thread has been archived. You have to exit the thread and find it through the catalog to get rid of the archived status.

I don't know how to reproduce this bug, it is usually happening when I minimize the app, bring it up, and open a thread from the left side bar (whatever it's called). It'll also happen when I jump from one thread to another thread from the left side bar.

**Comment by K1rakishou** [comment]
Already fixed.
https://github.com/K1rakishou/Kuroba-Experimental/issues/483
