### ISSUE TITLE
The erase button in the reply box

### ISSUE THREAD

**Issue by 213a21g** [K1rakishou/Kuroba-Experimental#487]
![wtf](https://user-images.githubusercontent.com/87037553/125489630-c331072d-549a-4761-ae3d-a42da7baceb7.png)

Can this please be removed? What is the point of this when there is an erase button in the keyboard?

**Comment by K1rakishou** [comment]
To quickly undo tag insertion.

**Comment by 213a21g** [comment]
I see now, but how is it any quicker than highlighting the text and using the erase button on the keyboard? For small phones, that button in the reply box is in the way when we try to solve the captcha or pull out the entire reply box.

**Comment by K1rakishou** [comment]
>but how is it any quicker than highlighting the text and using the erase button on the keyboard?

It requires only one click instead of selecting/erasing text?

**Comment by 213a21g** [comment]
It's quick for deleting the tags/brackets but for normal text it's a very useless feature. Since it's easy to tap on it and mess up the text in the reply box, adding an option in the app's settings menu to toggle it on/off would be good.

**Comment by marktaiwan** [comment]
Huh. That's the undo button? I'm new to the app and up till now I thought that's for inserting new lines because it looks almost identical to the enter key on Gboard.
