### ISSUE TITLE
Highlighting text from a post will mute that post

### ISSUE THREAD

**Issue by 213a21g** [K1rakishou/Kuroba-Experimental#488]
When I've highlighted the text from a post, it'll no longer be possible to quote that post or bring out the context menu on that post. Does anyone else have this issue too? I can fix the problem by re-entering the thread.

**Comment by K1rakishou** [comment]
Have you tried clicking the post comment? This usually clear the highlighting.

**Comment by 213a21g** [comment]
Yes, there's no way to clear the highlighting on my phone. I can however quote the post by tapping on the post's number while highlighting that post.

**Comment by 213a21g** [comment]
The latest update made it a bit worse, if I ever highlighted the text from a post, it'll also affect most of the posts in the thread.

**Comment by K1rakishou** [comment]
Still can't reproduce it.
