### ISSUE TITLE
Report "[Feature request] 4chan sounds player/filenames sounds"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#491]
UUID: 43714c20c455862284913b2ae0378537
Build flavor: stable
Version name: v0.10.8
OS info: Android 11, sdk version: 30
Report description: https://greasyfork.org/en/scripts/402682-4chan-sounds-player
Could you add support for audio links included in filenames? It could be nice if you could listen to sound threads on the app, maybe a small player or the option to listen to it with the image/app closed.

**Comment by K1rakishou** [comment]
I think that instead of adding support to this hack people (who care enough about it) should nag hiro add finally allow webms with sound on all boards.

**Comment by crisalis2** [comment]
Kuroba dev added this, not sure if you could just "copypaste" it: https://github.com/Adamantcheese/Kuroba/commit/ab58e9d

**Comment by K1rakishou** [comment]
I still don't feel like adding support to this thing. Loading stuff from urls random people put into image names doesn't seem very secure to me.
