### ISSUE TITLE
Add an option to never store 4chan captcha cookies

### ISSUE THREAD

**Issue by 213a21g** [K1rakishou/Kuroba-Experimental#494]
Just got blocked by a janny for quality posting and it kept saying "you've been blocked for x minutes" when I kept changing my IP.
I presume it's because the app is using the site's API? In that case a rework is needed since ban evading on imageboards is essential to the security of quality posters worldwide.

**Comment by K1rakishou** [comment]
You need to delete the captcha cookie.

**Comment by 213a21g** [comment]
This is a significant problem then. Mods are able to track all of the posts that someone makes with the cookie, despite using a new IP for each post. I suggest giving quality posters the option to have the cookie reset itself when the captcha is brought up, or maybe giving the option to reset it from the cog wheel under the captcha box. It's a hassle to every time go to Settings > Sites > 4chan Configuration > clicking on 4channel and 4chan captcha cookie > deleting it.

**Comment by K1rakishou** [comment]
Sure, I can add an option but FYI If you reset the cookie you will stop receiving easy captcha for like 20 hours.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/a2ef96f010987c6cef9a4560d130ce7a21446816
