### ISSUE TITLE
Persistent "Uploading 100%"  after posting image in thread

### ISSUE THREAD

**Issue by reportthings** [K1rakishou/Kuroba-Experimental#495]
Sometimes after posting in a thread, and only if I post an image, I get pic related.  The post goes through, and the image uploads into the thread.  But pic related won't go away until I restart my phone.  Pressing cancel does nothing, and I can't swipe it away.

Just started happening today and ive been on the same version of KurobaEx for 3 or 4 days.

![Screenshot_20210719-034325](https://user-images.githubusercontent.com/85461551/126122096-26396b1f-e8b6-43a6-8be0-73c5d169d678.png)

I'm not sure if it's my phone or KurobaEx.  If you need any information I'm happy to provide it.

**Comment by K1rakishou** [comment]
I couldn't reproduce it but I found one place that potentially could be the reason of this weird bug.
https://github.com/K1rakishou/Kuroba-Experimental/commit/359e4adb6c9b7b23f8441ea8387dae624ed1496a
