### ISSUE TITLE
Global search doesn't work

### ISSUE THREAD

**Issue by crisalis2** [K1rakishou/Kuroba-Experimental#496]
I type my query and when I tap "search" the app just says "Unhandled error! Unknown error: Bad Status Code: 503". I use the F-Droid version, but I just tried the Github APK and it didn't work either. I only have 4chan added as a site.

**Comment by K1rakishou** [comment]
They have added CloudFlare checks, that's why it doesn't work. Will be fixed in the next updated.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/ff84baac14a31741d4bcea716b4a4c601aa19550
