### ISSUE TITLE
Add more "Supported web addresses"

### ISSUE THREAD

**Issue by crisalis2** [K1rakishou/Kuroba-Experimental#497]
If I open a boards.4channel.org URL, I can open it directly on KurobaEx, but that is not the case for URLs of the various 4chan archives. KurobaEx's "Supported web addresses" are the following (pic taken from "App links" inside Android's "App info" for KurobaEx):
![Screenshot_20210722-074913_Settings](https://user-images.githubusercontent.com/65630147/126595017-9ebdea9c-dab8-412c-a67d-e15ec717b278.png)

I think more URLs could be added so that if I happen to use my browser to visit a thread hosted on a 4chan archive, I can easily open the URL with KurobaEx too (for example in Firefox there's a "Open in app" option).

This is also important for another reason. If you are using KurobaEx to browse a thread hosted in a 4chan archive and there are cross-thread replies (like a link to the previous thread in the case of generals), they are treated like URLs and will open in the browser, because KurobaEx is not associated with the URLs of the several 4chan archives, as seen in the pic above. So adding those URLs would make it possible to open such cross-thread replies inside KurobaEx instead of having to leave the app and open a browser...

This can be extended to other URLs of all the sites supported by KurobaEx that aren't included in the pic above, but I'm personally only interested in 4chan archives.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/fc62517d676f7ab6929fe96fb84cd5d91c17b9ff
