### ISSUE TITLE
Saving an already loaded image should not prompt for re-downloading.

### ISSUE THREAD

**Issue by tidux** [K1rakishou/Kuroba-Experimental#501]
The entire serialized image file should be held in cache or RAM as well as the rendered bitmap, and then the file written to disk when saved.  The current state of things roughly doubles the app's network usage since the JSON objects are so small.

**Comment by K1rakishou** [comment]
It shouldn't do that, though? I've fixed it in the previous version. The notification may still say that it "downloads" something but in reality it should take the image from the disk cache and simply copy it into another directory. You can check that by trying to re-download an image with no internet. It should work just fine.

**Comment by tidux** [comment]
Works on latest version.
