### ISSUE TITLE
BookmarksController. Add an option for selected bookmarks to start downloading them.

### ISSUE THREAD

**Issue by cramrafalgue** [K1rakishou/Kuroba-Experimental#505]
Hello, would it be possible for the thread watcher to automatically activate thread downloader? This is to avoid finding a bunch of dead threads once reviewing the hits of the watcher.
Thanks and great job!

**Comment by K1rakishou** [comment]
I don't really want to do this because this may absolutely destroy your battery if you have tons of bookmarks (like for example you have a filter watcher with a very unspecific pattern that bookmarks tons of threads at a time)

**Comment by K1rakishou** [comment]
On the other hand I probably could add an option to start downloading bookmarked threads when selecting them on the bookmarks screen. This way you can start downloading multiple threads at once and don't have to open them one by one and this is not automatic so you won't in the situation described above.

![image](https://user-images.githubusercontent.com/10332458/127114739-2db4623b-f163-4866-a818-b4bdd8664d30.png)

**Comment by cramrafalgue** [comment]
OK I see what you are saying. I only check the app about once a day and by then all of the threads of interest are dead, so batch downloading multiple threads while helpful won't allow me to read the old threads.
Insofar as the battery usage is concerned, I am sure that each user would be able to use their best judgement depending on their personal use case and toggle the functionality on/off.
Please think about it :) !

**Comment by K1rakishou** [comment]
People never even read changelogs so most of them won't even realize that this is a thing and will start spamming reports with stuff like "MY BATTERY IS DYING WTF IS YOUR APP DOING?!?!?!". And explaining this shit for every single user over and over again is a pain in the ass.

**Comment by cramrafalgue** [comment]
OK I see where you are coming from.Perhaps some other time then. Thanks anyhow :)

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/1ad7c2a19f64303590cc3d1e946e5e68d8dc1cf0
