### ISSUE TITLE
An improvement to the search box

### ISSUE THREAD

**Issue by 213a21g** [K1rakishou/Kuroba-Experimental#506]
Please make it so that the search box stays open after we've quoted a post in it. Trying to quote different posts from the search box is very tedious because each time you quote post, the box closes itself.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/150ff99c709135a53cd8630cf6df09e7ef99e0ed

**Comment by crisalis2** [comment]
Somewhat related to this, can you also make the "Tap the post number to reply" option work with the reply/search popups?

**Comment by K1rakishou** [comment]
Separate issue.

**Comment by crisalis2** [comment]
I will create it.
