### ISSUE TITLE
Reply counter on the right

### ISSUE THREAD

**Issue by brook91** [K1rakishou/Kuroba-Experimental#507]
Hello
I'd like to know if it's possible to put the reply counter on the right, so it can be easier to navigate and see replies when using one hand on a big phone
![Screenshot_20210730-031525](https://user-images.githubusercontent.com/52865487/127585250-79dfca8c-0c03-49a5-a554-09884accb727.jpg)
Like pic related

Thank you

**Comment by brook91** [comment]
I realized you can click on the right side and it does the same thing, so my comment is useless

**Comment by crisalis2** [comment]
I think it was a nice idea nevertheless.
