### ISSUE TITLE
Make the "Tap the post number to reply" option work in reply/search popups too

### ISSUE THREAD

**Issue by crisalis2** [K1rakishou/Kuroba-Experimental#510]
Currently, even if you have this option enabled, it doesn't work in the popup reply/search post screens. I think it would be nice if it worked there too.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/1812de840b948051200a00d5e1d9a692f293e00c
