### ISSUE TITLE
Wrong >>reply colors in archives

### ISSUE THREAD

**Issue by crisalis2** [K1rakishou/Kuroba-Experimental#511]
Replies like >>123456789 (including cross-thread replies) have an incorrect color in external 4chan archives.

In 4chan they look like this:
![20210731_225142](https://user-images.githubusercontent.com/65630147/127752194-6b6831e6-64cc-40d6-9547-a14d403ca6c7.jpg)
As you can see, both normal and cross-thread replies have the same color: a color for replies which is specified in the theme.

But in external 4chan archives they look like this:
![20210731_225205](https://user-images.githubusercontent.com/65630147/127752231-2a734268-bee1-4a26-b598-01699af581d3.jpg)
As you can see:
1) Cross-thread replies don't have the color specified for replies. Instead they have the color for URLs. This also happened in previous versions of KurobaEx.
2) Normal (same thread) replies don't have the color specified for replies. Instead they have the color for >greentext. This didn't happen in previous versions of KurobaEx, where in archives these normal replies had the right color as specified by the theme (0.10.8 is right, 0.11.3 is wrong).

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/bbcafd33b471b8dff1adacd5664b3f30e1d9c08c

**Comment by crisalis2** [comment]
Thanks! I tried the 0.11.4 beta and everything is fine. Unrelated but archive catalogs are very nice to have, good work.

One thing I noticed and didn't check before is that in global search results the color of same-thread and cross-thread replies is not the color specified for replies but the color for URLs. I don't really mind it but I thought I should tell you. Also I only could check this with the global search of archives, not with the one of 4chan itself because I somehow keep getting error 503.

**Comment by K1rakishou** [comment]
>Also I only could check this with the global search of archives, not with the one of 4chan itself because I somehow keep getting error 503.

Yeah this happens sometimes, in this case you just need to retry the "browser verification" a couple of times.
