### ISSUE TITLE
Cookie in plain text - defaultGoogleCookies 

### ISSUE THREAD

**Issue by cyxin577** [K1rakishou/Kuroba-Experimental#514]
Hi, 
I find that the default google cookie is set as a fixed plain text in CaptchaNoJsPresenterV2.java. Will this cause a security issue (e.g. impersonating a legitimate user)? 
Thanks.

**Comment by K1rakishou** [comment]
No. Moreover Google captcha is disabled so it doesn't matter anymore because it's not used.
