### ISSUE TITLE
Reloading threads gets rid of deleted posts

### ISSUE THREAD

**Issue by 213a21g** [K1rakishou/Kuroba-Experimental#518]
Could that function refrain from doing that? A lot of jannies are trigger happy and it's difficult to follow conversations in large threads on /lit/ and other boards when you've had those threads opened for a while.

**Comment by K1rakishou** [comment]
Well it reloads everything so that's what it's supposed to do. If you want to update a thread without fully reloading all posts then use the "thread status" item which is at the very bottom of a thread.
