### ISSUE TITLE
Unable to zoom wallpapers or hd imges.

### ISSUE THREAD

**Issue by AntonioVOL** [K1rakishou/Kuroba-Experimental#519]
When i zoom a wallaper or hd image, the app turns black and one second later the app closes.

**Comment by K1rakishou** [comment]
Need the crashlog.

**Comment by AntonioVOL** [comment]
------------------------------
Android API Level: 24
App Version: v0.11.2.14403
Development Build: Unknown
Phone Model: Lenovo K350t
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 256
------------------------------
Current layout mode: SLIDE
Board view mode: LIST
Prefetching enabled: false
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: false
diskCacheSizeMegabytes: 700
prefetchDiskCacheSizeMegabytes: 1024
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: null
OkHttp IPv6 support enabled: true
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: false
Background watcher enabled: false
Filter watch enabled: false
------------------------------


I dont know that it is the crashlog

**Comment by K1rakishou** [comment]
No it's not. You need to make it crash again then send the report.

**Comment by AntonioVOL** [comment]
When the problem happens the app simply closes and it dont show a screen to report error or view the crashlog.

Where are the txt of crashlogs? 

Pd: the app sometimes in this error say "deep zoom loading error"

**Comment by K1rakishou** [comment]
Settings -> Developer settings -> View logs.
Or
https://github.com/K1rakishou/Kuroba-Experimental/wiki/Getting-application-logs-or-crashlogs-on-beta-or-release-builds

**Comment by AntonioVOL** [comment]
I tap in this option but the logs don't appear

**Comment by K1rakishou** [comment]
Well then at least give a link to the image that crashes the app.

**Comment by AntonioVOL** [comment]
The app crashes in horizontal hd images with phone vertically and viceversa, one example

![1622247954168](https://user-images.githubusercontent.com/68360002/129354980-881620e1-28b7-4d57-b4a7-54b19481ff47.jpg)

Or more links 

https://i.4cdn.org/wg/1628216930982.jpg
https://i.4cdn.org/wg/1628751377736.png

**Comment by K1rakishou** [comment]
Can you also link a thread where this image is posted? For some reason it asks me to solve hcaptcha to view the image. Maybe that's the problem.

**Comment by K1rakishou** [comment]
The images are working fine for me in the emulator. Need logs.
https://github.com/K1rakishou/Kuroba-Experimental/wiki/Getting-application-logs-or-crashlogs-on-beta-or-release-builds

**Comment by AntonioVOL** [comment]
The spaceship image are obtained in 4chan /wg/ (wallapers/general) in a post named ultrawide 21:9, view the image with your phone vertically and zoom the image to force error.


View the image in the app with a phone. Not emulator please

**Comment by K1rakishou** [comment]
Both images load and zoom-in/out fine on my Samsung J5.
I don't have an older device than this.

**Comment by AntonioVOL** [comment]
i have a phone with 3 gb of ram and mediatek 6750m

is a lenovo k350t

**Comment by K1rakishou** [comment]
I'm assuming this error is the same as https://github.com/K1rakishou/Kuroba-Experimental/issues/535 so I'm closing it as well.
