### ISSUE TITLE
An adaptation problem

### ISSUE THREAD

**Issue by EasyVector** [K1rakishou/Kuroba-Experimental#522]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the third tab page, **texts of three tabs could not be fully seen**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 0.11.2, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see all of the texts in those tab buttons, and in this circumstance, part of them seem to be blocked. 

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.click the third tab button on the navigation bar below the main page
3.this error could be seen

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/128804171-0981dd7a-4a7b-4160-8441-78bc2d5a02d5.png" alt="Screenshot_1628565862 copy" width="250"/>

**Environment**

1. Version of KurobaEx : 0.11.2
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/468629b9582ae85d87479d0f9f93f8970d150a87
