### ISSUE TITLE
[Feature] Convert Videos To Boards Max Allowance (If Larger)

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#523]
Suggesting using something like ffmpeg to allow users to re-encode videos to the boards required formats, and compress the file to the maximum size/quality limits that specific board allows (if the file exceedes those limits). This would allow users to easily post videos to any board, with the least amount of quality loss, abd nake it easier to do.

It's a PITA to do media conversion on mobile, even through Termux, it would be very nice to have this built in. It's already kinda possible for images.

**Comment by K1rakishou** [comment]
I'm not going to include ffmpeg into this application because it will add ~30 megabytes of extra weight. This feature should be implemented in a separate application which should provide some kind of API or use existing ones for file selection or something like that.

**Comment by seniorm0ment** [comment]
do you have suggestions for any foss apps that have a good ffmpeg frontend besides using termux?

this still doesn't exactly solve the issue of needing to know the limits of the individual boards, then screwing with ffmpeg paramaters accordingly. an idea could be to allow kuroba to offload this to something like termux w ffmpeg. 
if a user posts to /gif/ and the file is over the limit, kuroba sends a call with the specified ffmpeg parameters (max quality for /gif/, automatically converts it.)
Just an idea, may be kind of complex or not possible without root not sure.

**Comment by K1rakishou** [comment]
>do you have suggestions for any foss apps that have a good ffmpeg frontend besides using termux?

I don't use it so I don't know.

>this still doesn't exactly solve the issue of needing to know the limits of the individual boards

A separate application can get all this information from the 4chan API.

>if a user posts to /gif/ and the file is over the limit, kuroba sends a call with the specified ffmpeg parameters (max quality for /gif/, automatically converts it.)

By the way, Is it possible to convert a video via ffmpeg by only specifying the max file size? Or do you need to constantly adjust the bitrate until everything fits? I'm not an ffmpeg expert and the last time I tried it would cut the video once it went over the limit.

**Comment by seniorm0ment** [comment]
I am no expert either and usually results in my reencoding a million times until I figure it out. I thought you could use the -fs flag for filesize but I can't find docs on the proper formatting of the size you want to specify. Haven't looked too hard yet.
