### ISSUE TITLE
Report "Video Playback Error"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#525]
UUID: 6f6d0330cf839527bc8726698ba41cd3
Build flavor: beta
Version name: v0.11.5
OS info: Android 11, sdk version: 30
Report description: When I try to view some videos in the app, I get an error starting with "Decoder init failed: c2.android.vp8.decoder." I can copy the video links and watch them on a browser. I can also watch them on Kuroba with no issues.
Logs:
```
D/(03:33:32.574) KurobaEx-beta | ExoPlayerWrapper: releaseAll() releasing 2 / 5 player
D/(03:33:32.578) KurobaEx-beta | ExoPlayerWrapper: releaseAll() releasing 3 / 5 player
D/(03:33:32.583) KurobaEx-beta | ExoPlayerWrapper: releaseAll() releasing 4 / 5 player
D/(03:33:32.584) KurobaEx-beta | ExoPlayerWrapper: releaseAll() releasing 5 / 5 player
D/(03:33:33.322) KurobaEx-beta | ControllerNavigationManager: onCloseAllNonMainControllers()
D/(03:33:33.326) KurobaEx-beta | ControllerNavigationManager: onControllerPushed(MainSettingsControllerV2)
D/(03:33:33.333) KurobaEx-beta | screensBuiltOnce: SuspendableInitializer initWithValue() called
D/(03:33:33.334) KurobaEx-beta | screensBuiltOnce: notifyAllWaiters throwable==null: true, waiters=0
D/(03:33:33.334) KurobaEx-beta | screensBuiltOnce: SuspendableInitializer initWithValue() done
D/(03:33:33.337) KurobaEx-beta | screensBuiltOnce: notifyAllWaiters throwable==null: true, waiters=0
D/(03:33:33.339) KurobaEx-beta | screensBuiltOnce: SuspendableInitializer initWithValue() called
D/(03:33:33.340) KurobaEx-beta | screensBuiltOnce: SuspendableInitializer initWithValue() already completed, exiting
------------------------------
Android API Level: 30
App Version: v0.11.5.14714
Development Build: Release
Phone Model: samsung SM-G998U1
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 256
------------------------------
Current layout mode: SLIDE
Board view mode: LIST
Prefetching enabled: true
Hi-res thumbnails enabled: false
CloudFlare force preload enabled: false
diskCacheSizeMegabytes: 512
prefetchDiskCacheSizeMegabytes: 1024
diskCacheCleanupRemovePercent: 25
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: false
Background watcher enabled: false
Filter watch enabled: false
```
------------------------------

**Comment by K1rakishou** [comment]
Media viewer -> three dot menu -> set "Media viewer offscreen page count" to 1.

**Comment by tidux** [comment]
Does not resolve issue on Android 11.  Latest F-Droid build.

**Comment by tidux** [comment]
![Screenshot_20210819-013457](https://user-images.githubusercontent.com/1330562/130036531-29c4ffd8-dce3-4f87-bd57-a9ad9753a4ec.jpg)

**Comment by K1rakishou** [comment]
Then it's some kind of device-specific decoder problem. Can't fix it. The only hope is if ExoPlayer devs somehow find a way to work around this issue.

**Comment by tidux** [comment]
> Then it's some kind of device-specific decoder problem. Can't fix it.

The file works fine in Firefox on the same device so there's clearly a fix.

**Comment by Pentaphon** [comment]
> Then it's some kind of device-specific decoder problem. Can't fix it. The only hope is if ExoPlayer devs somehow find a way to work around this issue.

I think they've isolated the issue here https://github.com/google/ExoPlayer/issues/9142 but they consider it low priority. If we want KurobaEx to have flawless webm playback, we need to get the Exoplayer devs to figure this out.

**Comment by Pentaphon** [comment]
@K1rakishou one of the Exoplayer contributors has followed up on the webm issue and has suggested a workaround here in the meantime. Perhaps you'd like to try it?

https://github.com/google/ExoPlayer/issues/9103#issuecomment-910206336

**Comment by K1rakishou** [comment]
Alright, thanks, I will try it before the next release.

**Comment by K1rakishou** [comment]
If this exoplayer hack won't work I will probably try migrating to mpv.

**Comment by K1rakishou** [comment]
So In the end I decided to try to move to mpv instead of trying to fix exoplayer.
@Pentaphon @tidux check out this issue there is an apk build with the mpv https://github.com/K1rakishou/Kuroba-Experimental/issues/547

**Comment by Pentaphon** [comment]
> So In the end I decided to try to move to mpv instead of trying to fix exoplayer.

That's awesome and it works well but I'm going to keep pushing the devs to fix Exoplayer so we get 2 working video players for Kurobaex instead of just 1. There is more interest in the issue taking place over here if anybody else reading this wants to help the Exoplayer contributors come up with a workaround or permanent solution. 

https://github.com/google/ExoPlayer/issues/9103
