### ISSUE TITLE
Suggestion to add highlights to viewed threads in catalog

### ISSUE THREAD

**Issue by reportthings** [K1rakishou/Kuroba-Experimental#531]
Hello again,

It would be cool if there was an option for threads you have opened in the catalog to remain highlighted upon refreshing the catalog as a reminder you've already visited them.  Acting similarly to the purple highlight you get on Google search results after clicking a website from Google.

 Just a thought but I would enjoy this feature.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/b8fef4fb6709aa9d2936130f27b450de6497777f
