### ISSUE TITLE
Posting to Lainchan is broken

### ISSUE THREAD

**Issue by regularentropy** [K1rakishou/Kuroba-Experimental#536]
Failed to post, error=Your request looks automated; Post discarded.
The error occurs on every board.

OS: Android 11
KurobaEX v0.11.5.14715 FDroid

**Comment by K1rakishou** [comment]
Lainchan uses home-made antispam for posting and I'm too lazy to add support for it. If anyone is interested in implementing it you most likely need to parse the thread html page, find these hidden values and then attach the to the reply request body.

![image](https://user-images.githubusercontent.com/10332458/130790139-b2f8ea97-dda0-4b9c-86a9-deea7026dead.png)

**Comment by andreas-hartmann** [comment]
I'm looking into this. Seems like we need to adjust our VichanAntispam/create a variant to correctly handle their custom "checkSpam" function here: https://github.com/lainchan/lainchan/blob/master/inc/anti-bot.php
It includes a number of checks that need to pass, including a whitelist of fields and checks for validity of the hashes against a DB table.

**Comment by andreas-hartmann** [comment]
I have a working fix, I'll keep testing it for a while and clean it up.
