### ISSUE TITLE
fetching yt title and duration don't work anymore

### ISSUE THREAD

**Issue by samlux04** [K1rakishou/Kuroba-Experimental#537]
it doesn't work for quite some time now. it just says [not available]
4chanX(usercript) still works wonderfully, maybe you can look at their code. maybe there's some changes in the api or something.
kindly do the needful. thanks.

**Comment by K1rakishou** [comment]
Oh yeah this is probably because they've changed the page design.

**Comment by K1rakishou** [comment]
Actually it works for me. Show me the link that cannot be fetched.

**Comment by samlux04** [comment]
apparently it works when I use non Europe VPN. maybe because of the cookie dialog or something which is also happened with newpipe, I reckon seeing an issue about it.
because most VPNs are banned on chan I can't post with it 😢

**Comment by K1rakishou** [comment]
Oh then it's probably the age verification. Nothing I can do about it.

**Comment by samlux04** [comment]
this one
https://boards.4chan.org/pol/thread/336590352

kuroba
![Screenshot_2021-08-29-06-17-33-578_com github k1rakishou chan beta](https://user-images.githubusercontent.com/85811479/131232405-6476d92a-c7ec-4480-af96-f9842846ef29.png)

4chan-x
![Screenshot_2021-08-29-06-18-09-389_org mozilla fennec_fdroid](https://user-images.githubusercontent.com/85811479/131232410-003ef916-d947-46af-92be-19b00fcd6e53.png)

**Comment by K1rakishou** [comment]
Works for me. Most likely it's the forced age verification in some countries. Maybe it's possible to bypass this by using the API but the API has it's own problems.

![image](https://user-images.githubusercontent.com/10332458/131243642-b0c7a0ec-7fde-4159-8b34-82bf15c110a1.png)

**Comment by samlux04** [comment]
checked and worked. thanks man.
