### ISSUE TITLE
Android 10 gesture zone is gone after a while

### ISSUE THREAD

**Issue by cuteasci** [K1rakishou/Kuroba-Experimental#538]
You set it up and after couple of days it is gone and you need to set it up again. 

Also, is it possible to make them bigger? Maybe the half of the screen?

**Comment by K1rakishou** [comment]
>Also, is it possible to make them bigger? Maybe the half of the screen?

No, it's not possible.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/a0e5b639448f875713abb343e3882fdabd70fb03
