### ISSUE TITLE
No longer able to choose a default gallery app

### ISSUE THREAD

**Issue by a84r7a3rga76fg** [K1rakishou/Kuroba-Experimental#541]
I've been unable to choose a default gallery app when uploading images/videos with the current app version. If this feature was removed, can it please be re-added?

**Comment by K1rakishou** [comment]
What do you mean? This dialog? What app version?

![image](https://user-images.githubusercontent.com/10332458/131405220-55f8d74e-b75d-4dbd-8806-55660100f8fd.png)

**Comment by a84r7a3rga76fg** [comment]
Latest version. Yes, it's that dialog. I don't have the option "remember my choice", so I have to always choose which gallery app when trying to upload images/videos.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/6f35db27d21dd0f0422fb550abc3aa391a40c73c
