### ISSUE TITLE
"Clear navigation history" - History reappears

### ISSUE THREAD

**Issue by reportthings** [K1rakishou/Kuroba-Experimental#542]
Steps: 
Clear navigation history
Close KurobaEx
Open KurobaEx
Navigation history is back

The workaround I found is:
Clear navigation history
Navigate to new thread so it is the only one in navigation history
Close and reopen app
Now only the new thread is in navigation history

Not a huge problem just doing my part to report it.

I also just submitted (inside KurobaEx) a report about KurobaEx crashing while updating.  That log should also have the navigation history bug in it.

As always thanks again for making this, still love it

**Comment by reportthings** [comment]
About the last part.  Sorry, I just saw that the new beta version needs to be installed manually so please disregard that part.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/1fe4eccef8675a370e1b0f45f9b6ddefc10859a0
