### ISSUE TITLE
slower captcha slider

### ISSUE THREAD

**Issue by samlux04** [K1rakishou/Kuroba-Experimental#543]
I notice when using kuroba, the captcha was easier to solve, there's a stickyness in the slider, similar to the web. in kuroba-ex the slider is way too smooth. does the captcha getting upscaled? and the slider move this upscaled per pixel instead of its original step. so it's easier to slip with kuroba-ex. I mean the captcha is a low resolution image with noticable pixels, so the slider should have a step corresponding to how much the horizontal pixels in the image.
thanks.

**Comment by K1rakishou** [comment]
>does the captcha getting upscaled? and the slider move this upscaled per pixel instead of its original step.

Yes but it shouldn't matter since you don't have to align them 100% accurately to make out what's the word. At least in most cases. But I guess I could add a min sliding step so it's more snappy.

**Comment by samlux04** [comment]
> > does the captcha getting upscaled? and the slider move this upscaled per pixel instead of its original step.
> 
> Yes but it shouldn't matter since you don't have to align them 100% accurately to make out what's the word. At least in most cases. But I guess I could add a min sliding step so it's more snappy.

I know. I kinda shitposter myself. often solve the captcha in a second. with browser I can quickly glance at the correct letters even after the slider pass it, I don't need to slide back since I already memorize the letters. with kuroba-ex maybe because it can align portion of a pixel so there's more image I had to compute in my brain. often I had to slide back and forth to find the letters.
would be appreciate if you can add step just like in the browser. thanks.

**Comment by samlux04** [comment]
also if possible to remember the slider position. I notice often it's at around 50%-75%. it's not rare to get the right letters in the same position multiple times as well.

**Comment by seniorm0ment** [comment]
I also do find it significantly easier to read the captcha on desktop vs mobile.

**Comment by K1rakishou** [comment]
Captcha slider with snap effect implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/b6dd56a3414d680152da4a9e1b15cff43fd6da97

The old way of sliding without the snap effect is still possible you need to drag the captcha image itself instead of the slider.

**Comment by samlux04** [comment]
Checked and worked fine. Tho isn't well aligned, a little bit of shifted. It still readable just fine. Thanks.

(notice the P)
![Screenshot_2021-10-10-19-07-29-713_com github k1rakishou chan beta](https://user-images.githubusercontent.com/85811479/136693220-e6cbe0c7-fbc5-4d44-aa44-dc9aa984a608.png)

**Comment by K1rakishou** [comment]
The slide step depends on the size of the image which depends on the horizontal screen size. So for me in the emulator it's perfect, the images are always aligned. But it may be different for you, yes. I guess I could make it constant or even let the user decide how many pixels should be used for a slide step.

![image](https://user-images.githubusercontent.com/10332458/136694214-f4d57be7-5f44-46d0-a510-b89308d3b6b4.png)

**Comment by samlux04** [comment]
I see. Maybe due to the different scaled image according to screen size. I notice in kuroba and browser with 4chan-x the calctha image was significantly smaller, not scaled to fit screen wide.

**Comment by seniorm0ment** [comment]
I find browser to be significantly clearer, I think higher dpi?

**Comment by samlux04** [comment]
No but smaller. I looked at the chaptha its width was 235px. Maybe some miscalculation with the scaling and step. I notice it's shifted beyond 10 px, which is a lot. Sometime it's hard to read, need to use the image slide. I think 1080px screen width is the most common.
