### ISSUE TITLE
Gesture support for reply preview pane

### ISSUE THREAD

**Issue by ledcaveman** [K1rakishou/Kuroba-Experimental#551]
![IMG_20210911_151402](https://user-images.githubusercontent.com/5804997/132950882-35f349e3-b5e7-4069-8dd1-f1f08011f751.jpg)

Something like this would be really nice to have to make quick replies easier. As opposed to having to open the whole thread, finding the post in question and only replying then. Sorry if this isn't tagged or labelled correctly, I don't use GitHub very often, even less on my phone.

**Comment by K1rakishou** [comment]
You can longtap the posts and click quote/quote text and it will do exactly what you want.
