### ISSUE TITLE
Can only copy text from the post

### ISSUE THREAD

**Issue by a84r7a3rga76fg** [K1rakishou/Kuroba-Experimental#553]
I can often only copy text from a post and I've to restart the app to get it back to normal behavior. I don't know what's causing it, seems to happen whenever I've copied something from inside the thread.

**Comment by K1rakishou** [comment]
Can you record a video of this happening?

**Comment by a84r7a3rga76fg** [comment]
https://streamable.com/t2egnz

**Comment by K1rakishou** [comment]
Oh you mean the option to quote text disappears?

**Comment by K1rakishou** [comment]
Can't reproduce it on the emulator. What device are you using?

**Comment by a84r7a3rga76fg** [comment]
I'm using Nokia 5. Apparently, the reload option in the top-right menu works instead of restarting the app.

**Comment by a84r7a3rga76fg** [comment]
Bump
