### ISSUE TITLE
[8kun] Failed To load images

### ISSUE THREAD

**Issue by rickninja765** [K1rakishou/Kuroba-Experimental#559]
![Screenshot_2021-09-23-09-52-09-48.jpg](https://user-images.githubusercontent.com/61545131/134454294-0fbe8336-0abe-40d0-a20f-2a0036d08af1.jpg)

How To Reproduce

Load any images in 8kun and it'll redirect like this error.

**Comment by K1rakishou** [comment]
Apparently 8kun introduced some kind of new antispam (?) system and I have no idea how to bypass it because I don't use 8kun (I can't even view the images in the browser). If anyone cares about it then go ahead.

**Comment by AtomicWerks** [comment]
Images are working in browser now. Apparently they're using a new media host:128ducks.com

I'm not a dev, so can't fix the issue in kuroba-ex, but hopefully this info helps.

**Comment by K1rakishou** [comment]
This was fixed by https://github.com/K1rakishou/Kuroba-Experimental/pull/610
