### ISSUE TITLE
captcha input field as password 

### ISSUE THREAD

**Issue by samlux04** [K1rakishou/Kuroba-Experimental#562]
hi man. is it possible to change the input field for captcha as password field but with visible text/without asterisk. so it will summon a keyboard(Gboard/Swiftkey) with number row on top and suggestion, autocorrect, spell check disabled. thanks man.

I mean so it will summon this
![Screenshot_2021-09-26-07-36-57-776_com kiwibrowser browser](https://user-images.githubusercontent.com/85811479/134788535-96d3c8d6-99c9-4e3f-a3e6-483217bab7f3.png)

instead of standard keyboard
![Screenshot_2021-09-26-07-38-01-944_com kiwibrowser browser](https://user-images.githubusercontent.com/85811479/134788549-bc110374-7aa2-40f4-bdf6-7f79e6d1c000.png)

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/issues/556

**Comment by samlux04** [comment]
checked and tested. works fine. thanks man.
