### ISSUE TITLE
odd pixel dimension webms still broken with mpv

### ISSUE THREAD

**Issue by tidux** [K1rakishou/Kuroba-Experimental#563]
Galaxy S21+, KurobaEx-fdroid v0.12.6.16303

**Comment by K1rakishou** [comment]
Can you post the webm url that doesn't play? Also, did you try switching from hardware decoding (HW) to software decoding (SW)? This should help (since the problem is in hardware decoders). If it doesn't then I dunno.

**Comment by tidux** [comment]
Never mind, I didn't see the mpv toggle instructions.  I installed the libraries and the plugin works now.  Can you find a way to bundle the libraries in the APKs?

**Comment by K1rakishou** [comment]
>Can you find a way to bundle the libraries in the APKs?

I don't want to do that because it will make the apk twice as big at the very least.
