### ISSUE TITLE
Can't Quote Reply When Viewing A Reply

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#565]
When you click on "view x replies to post", you can no longer hold down on the post and choose to quote that post.
This is annoying, because it means you have to now jump to that post, quote it, then scroll all the way back up to where you were.

**Comment by K1rakishou** [comment]
You mean this? Seems to be working.

![image](https://user-images.githubusercontent.com/10332458/135253733-1c8cfb03-b66d-4c97-9b3d-88297ef54aaa.png)

**Comment by seniorm0ment** [comment]
click "4 replies", then try it there.
I don't see the quote option there.

I see it when I click the posts, just not when clicking replies, then holding on those. Worked previously.

**Comment by K1rakishou** [comment]
Still works for me. Looking at the code the Quote and Quote text options only do not appear in the menu when you longtap catalog threads. Should always work when viewing threads. Are you trying to quote a post when using search/thread preview/cross-thread reply or something like that? Can you show a video of this happening?

**Comment by seniorm0ment** [comment]
I think this is a potential bug?
It was doing it yesterday, but I just tried it now and I'm seeing the quote buttons. Yesterday it only had the Info, Archive, and Report buttons available.

**Comment by K1rakishou** [comment]
Probably, yes. But without the STR I can't really do much.

**Comment by seniorm0ment** [comment]
I have yet to reproduce it.

**Comment by seniorm0ment** [comment]
Haven't encountered this, but the Mark as my post definitely doesn't appear in that menu. Also evident in your screenshot above.
Can you add that back?

**Comment by seniorm0ment** [comment]
@K1rakishou
Any interest in adding mark as my post to that menu? 
Would be nice to not have to jump to that post to mark it.

**Comment by K1rakishou** [comment]
Actually already did that yesterday, see https://github.com/K1rakishou/Kuroba-Experimental/commit/ed0ffd230877820fe7bd661b0fc2e3e6f6487f59#diff-1d5165f49d226db3cd9527a2b38d46d37bf53dd3b29a932df23749120ee50bdfL1673
