### ISSUE TITLE
Can't Hold For Context Menu On Post With Links

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#566]
It's extremely annoying to get the hold context menu to appear on posts that have nothing but links.
A few updates ago you could click anywhere on the box to get it, but now links have an invisible line that goes all the way fo the right so you can't just hold on blank space.

Please bring back so when you click a link, it clicks the link. But when you click on any empty space, it acts as empty space. It's extremely annoying now.

**Comment by K1rakishou** [comment]
Yeah there is already an issue with a suggestion to add an option to disable this behavior.

https://github.com/K1rakishou/Kuroba-Experimental/issues/504

**Comment by seniorm0ment** [comment]
My bad, had a weird title, didn't show up in my search

**Comment by K1rakishou** [comment]
By the way you can try using the "Show post options" option when this happens temporary.

![image](https://user-images.githubusercontent.com/10332458/135258067-6c7572e4-1bd8-4668-9adb-ac906f8a5ba4.png)
