### ISSUE TITLE
what is this hat thing in catalog thumbs?

### ISSUE THREAD

**Issue by samlux04** [K1rakishou/Kuroba-Experimental#571]
starting today I notice there's this hat thing.
sometimes chan does put small thing like at christmas or new year. can it be removed? I checked on browser there's no such thing.
it's distracting and hard to read the text.

![Screenshot_2021-10-01-05-04-47-279_com github k1rakishou chan beta](https://user-images.githubusercontent.com/85811479/135530323-78a26879-41d1-4424-9650-cd5187433231.png)

**Comment by K1rakishou** [comment]
Yeah I wonder what could it be it's like today is 4chan's birthday or something.

**Comment by samlux04** [comment]
can it be removed tho or maybe scaled down. it's not attached to the thumbnails image but some kind of overlay?

**Comment by K1rakishou** [comment]
No it's not possible to remove them. It's been like this since the Clover days. I only made them slightly transparent so you can see what's behind them. You can try changing your phone time but it may break the TLS. Or just wait for the October 2nd it only lasts for 24 hours.

**Comment by samlux04** [comment]
alrighty then
