### ISSUE TITLE
Images in posts are arranged in unnatural order 

### ISSUE THREAD

**Issue by cuteasci** [K1rakishou/Kuroba-Experimental#573]
Usually you expect everything to be ordered from left to right, but the order of images in posts starts from right.  So when you click image n.2 and start swiping you miss image  n. 1.  
![Screenshot_20211003-222303_Octavi_Launcher_17_1](https://user-images.githubusercontent.com/59581277/135768808-50c8647b-ee4a-4fce-8ebc-97085e3fb0bf.png)

I think this is better choice 
![Screenshot_20211003-222303_Octavi_Launcher_1_1](https://user-images.githubusercontent.com/59581277/135768819-1de1ceb0-c685-4714-86d5-f33a1388fd98.png)

**Comment by K1rakishou** [comment]
Yeah I wanted this thing to get mirrored when using the post alignment left but it makes no sense when you open the media viewer and start swiping forward/backward.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/157ab901d3509b8f844b8a7cd0f9b928fbc48894
