### ISSUE TITLE
[Feature Request] Add Conversation Threading a la 4chan-x

### ISSUE THREAD

**Issue by deltabravozulu** [K1rakishou/Kuroba-Experimental#574]
[4chan-x](https://github.com/ccd0/4chan-x) has a really cool feature of being able to take replies and thread them conversationally. This would be a top notch addition to KurobaEx. 
-----------
#### Unthreaded
![image](https://i.imgur.com/FKnSBdB.png)

#### Threaded
![image](https://i.imgur.com/o5HeLrc.png)
----------
With deep comment threads, like 15+ in a reply chain, display could be difficult. 

Here's a 4chan-x threaded representation of a chain 9 comments deep on a mobile device: 
<img width="413" alt="Screen Shot 2021-09-30 at 10 36 39 PM" src="https://user-images.githubusercontent.com/8893396/135577294-7f4959f5-8f59-4b75-ada9-099e32387bc2.png">

One might consider using a maximum recursion depth value. This is arbitrary, and is the chef's choice, but I'd pick 10 deep as the standard--maybe allowing users to choose how deep to make these threads if they have a threading option toggled on.

**Comment by K1rakishou** [comment]
To be honest I never liked this layout style. Whenever I had to use a website with this layout style, every time a new post is added, it's impossible to figure out where this post is located unless you scroll through the whole list to see where it is (yeah some sites have the "Show new posts" button that scrolls you to the new post position but if doesn't really work when there are multiple new posts). I think this is absolutely ridiculous and unusable. (By the way I have never used this feature in 4chanx maybe it does some magic that fixes the issue and I just don't know about that). I think the way imageboards handle it is the best way there is (new posts are always at the bottom). 

>With deep comment threads, like 15+ in a reply chain, display could be difficult.

Yeah there is also this problem.

So I don't think this will be useful for this application and I'm not going to work on this. If anyone ever makes a PR then I will merge it. But I highly doubt it will ever happen.

**Comment by samlux04** [comment]
It will turned imageboards into plebbit which we don't like. Go back ->

**Comment by deltabravozulu** [comment]
> It will turned local phone viewers of imageboards into plebbit which I don't like. Go back ->

ftfy
I don't use reddit.
