### ISSUE TITLE
Report "archived.moe not loading images"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#578]
UUID: b714d06622c4cd4f047fe4a1382e0f82
Build flavor: stable
Version name: v0.12.8
OS info: Android 11, sdk version: 30
Report description: archived.moe loads thumbnails normally but fails to load full size image. When full size image fails to load a message pops up: "Failed to download image (reason: HttpCodeException statusCode = 403)"

**Comment by K1rakishou** [comment]
Can't reproduce. Does this still happen? Send me the post url which image doesn't open.

**Comment by gink0824** [comment]
I had this issue on /b/ and /bant/. Images load on other boards.


Attached is a screenshot after tapping a thumbnail of a random thread on /b/. Full size image attempts to load, fails to load, and message pops up. 

Also on archived.moe /b/ and /bant/ seem to be the only boards that get full size images from thebarchive.com. The rest of the boards on archived.moe that link fullsize images from other archives such as 4plebs or desuarchive have no problem.

![Screenshot.jpg](https://user-images.githubusercontent.com/91985947/136301560-0dc2b40c-257c-4faf-9b5e-e74404ef3062.jpg)

Screenshot post url:
https://archived.moe/b/thread/864520647

**Comment by K1rakishou** [comment]
The same thing happens in the browser. Probably barchive decided to block opening it's media links from different sites.
![image](https://user-images.githubusercontent.com/10332458/136582133-9b9d14b5-f2ef-469a-940b-f6854d7b74ec.png)

**Comment by samlux04** [comment]
I can open it just fine with a browser. Tho it follow redirection page. Maybe it need a 'referer' header. Some servers do respond with 403 forbidden code without correct referer header. I'm on mobile so I can't confirm. But it's the common issue with forbidden resources. Some site even requires custom header or cookies.
