### ISSUE TITLE
Bug: Default/home board is stuck to whatever it's first set to

### ISSUE THREAD

**Issue by gut5** [K1rakishou/Kuroba-Experimental#579]
1. Set up boards, choose /biz/ as the "top" board in the list so that it will appear first
2. Decide later on I want to change to a different default board so I remove biz from the list and set something else as the first in the list
3. Biz is still showing up when I open the app

**Comment by K1rakishou** [comment]
Do you have the "open the last visited board on app start" setting turned on maybe?

**Comment by gut5** [comment]
sorry but I can't locate that setting anywhere in the settings tab, which section is it in?

**Comment by K1rakishou** [comment]
It's in the drawer settings now.

**Comment by gut5** [comment]
Thanks, I didn't notice that
