### ISSUE TITLE
how to use the "options" field?

### ISSUE THREAD

**Issue by darlopvil** [K1rakishou/Kuroba-Experimental#581]
May sound retarded but does it work or not? when i try to use a tripcode or a secure tripcode nothing changes from being a normal anon. I don't see the username change or anything in particular. Maybe it works different?

**Comment by K1rakishou** [comment]
I have never used tripcodes in my life but shouldn't it be used in the name field? I think options is for stuff like 4pass icon if you have the passcode.

**Comment by darlopvil** [comment]
Now it works, thank you very much!
I thought i had to use the "Options" field since in the 4chan rules it explains that this is where you must put what is necessary to have the tripcode. Thanks for everything, closing issue!
