### ISSUE TITLE
UI Bug report - Replies view glitch

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#583]
![Screenshot_20211008-214851_KurobaEx-beta_1](https://user-images.githubusercontent.com/88936537/136590729-f9386e6b-032a-4a22-8ac7-c6e86b58247f.png)

See attached image. This happens when you browse the catalog, and select the replies button. The left edge appears of the view appears clipped. Version is the latest beta - commit 5aa926

**Comment by ghost** [comment]
To add, this appears to reproducible only in potrait, works fine in landscape.
Bug is non-existent on latest version of fdroid - 0.12.8

**Comment by ghost** [comment]
I am not really an android dev, but maybe this is responsible?
https://github.com/K1rakishou/Kuroba-Experimental/commit/bbc428af47512e3d327186891de6dc283afd24c9

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/8854fa95db01f014e7dc28a13cba1b705a1145dd

**Comment by K1rakishou** [comment]
Reply Pop-up
UUID: 39ac0e3e8cb7dd0f64063a7a40de8e31
Build flavor: beta
Version name: v1.0.0
OS info: Android 10, sdk version: 29
Report description: The pop-up box with replies, when you click on the replies of a post, is truncated/cut off on both the left and right side.
