### ISSUE TITLE
Add diochan support

### ISSUE THREAD

**Issue by Dashchanon** [K1rakishou/Kuroba-Experimental#584]
Hi.
Can you add support for diochan.com?

I [forked this repo](https://github.com/Dashchanon/Kuroba-Experimental/tree/develop-diochan) and made some [changes](https://github.com/Dashchanon/Kuroba-Experimental/commit/4a20ddd1685335a4b45c9db2bf5db4eb1b3a0d4b) to make it work with diochan.  
It's pretty much a copy of Lainchan's implementation as both imageboards use [NPFchan](https://github.com/fallenPineapple/NPFchan) under the hood. Could be useful as a starting point.  

Thanks

**Comment by K1rakishou** [comment]
I mean make a PR and I will check it.

**Comment by Dashchanon** [comment]
> I mean make a PR and I will check it.

Made a PR (#586) but do notice that this isn't ready

- Posting does not work
- ~Search does not work~
  Meant global search actually. I don't know how this works tho, might be a very specific thing since I only see 4chan supporting it. 
- Some thumbnails won't load
- No embedding in boards that support it (e.g. /yt/ )
 
I'm sure there's more
