### ISSUE TITLE
[Feature request] Allow searching archives

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#588]
Currently, searching archives only searches their catalog. The global search does not allow searching desuarchive, which in my opinion kinda defeats the point of a archive - finding if a topic was discussed previously.

**Comment by K1rakishou** [comment]
Oh yeah, the global search still uses the archives.json which only contains archives that support search api (which excludes the desuarchive) and there is no need for that anymore.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/690bd356f7fbdd57a630bf5082440959668e43a1
