### ISSUE TITLE
Report "Filters doesn't seems to work"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#590]
UUID: 1fcd907801ddbd0b21aa8bbe9747786b
Build flavor: beta
Version name: v1.0.2
OS info: Android 9, sdk version: 28
Report description: Filters doesn't seems to work, filtered posts are still seen, and the post grid becomes not aligned.

**Comment by K1rakishou** [comment]
Just checked and it seems to work. Maybe you want to use the "remove" filter action instead of "hide"?

Also I don't understand what you mean by "post grid". The catalog grid layout mode?

**Comment by dimitrije-stamenkovic** [comment]
Yeah, removing instead of hiding solved the problem.
And yeah, I meant on grid layout mode. Thanks on quick respond.
