### ISSUE TITLE
[Feature] Auto Capitalize Captcha Input

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#593]
Suggesting automatically having all input for the captcha field be capitalized. 
While it detects lowercase, it is just easier to visually compare what you typed to what you need to type. The captchas themselves are always all capital. 
Just a nice QOL feature.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/091b36b01b4e41ff8ffcf2629f981898331ea98c
