### ISSUE TITLE
[Enhancement] Add option to disable automatically saving your own posts

### ISSUE THREAD

**Issue by trunc88** [K1rakishou/Kuroba-Experimental#594]
I noticed that KurobaEx automatically saves every post you make, and wasn't able to find a way to disable it.

**Comment by K1rakishou** [comment]
Without that your posts won't be shown as yours. No (You) indicator when somebody replies to you, no left side mark, no notifications.

**Comment by trunc88** [comment]
Oh, that makes sense. I guess I misunderstood and thought you were able to save any post, so it would be difficult to find the posts I chose to save among my own automatically saved posts. Just checked the app and saw that there is no "save post" option, only "mark as my post".

Thanks, and sorry about that

**Comment by K1rakishou** [comment]
> Just checked the app and saw that there is no "save post" option, only "mark as my post".

It's the same thing just named differently.

**Comment by trunc88** [comment]
Right, I understand now. What I mean is, I assumed the feature was there to save posts for reading later, like the local thread archiver, but for single posts. It might be better to label it as "my posts" instead of "saved posts" in my opinion, especially since the menu item says "mark as my post". Would also be cool if the local archiver had the option to download single posts.

Sorry for the confusion

**Comment by K1rakishou** [comment]
Yeah it should probably be renamed.

>Would also be cool if the local archiver had the option to download single posts.

I don't know why would anyone ever use this.

**Comment by trunc88** [comment]
> I don't know why would anyone ever use this.

Well, sometimes a post has some good information in it that I want to save for later, but don't need the whole thread to go along with it. I understand if you don't want to add that though. Can always just copy and paste into a text file or something

**Comment by K1rakishou** [comment]
>Well, sometimes a post has some good information in it that I want to save for later, but don't need the whole thread to go along with it.

Archives exist for this exact reason.

**Comment by trunc88** [comment]
>Archives exist for this exact reason.

The same could be said about the local thread archiver...
Obviously there are reasons why someone might want a local copy.

**Comment by K1rakishou** [comment]
That's true. Still adding support for per-post local archiving is an overkill in my opinion and it's probably going to be a huge pain in the ass to implement.

**Comment by trunc88** [comment]
OK that's fair. Thanks for responding!
