### ISSUE TITLE
Report "[FR] Clover/Kuroba style bookmarks"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#597]
UUID: 2ec9324c2f18824929c561a2d886466c
Build flavor: stable
Version name: v1.0.3
OS info: Android 10, sdk version: 29
Report description: Please, I just want to swipe them away.

**Comment by K1rakishou** [comment]
You can literally select multiple and remove them at once which is way faster than swiping them one by one.

**Comment by floppyD** [comment]
I also think swiping is nicer, specially when you just want to remove one of them. Having both would be great
