### ISSUE TITLE
Use bookmark_counter_has_replies_color here when there's a reply

### ISSUE THREAD

**Issue by floppyD** [K1rakishou/Kuroba-Experimental#605]
Makes more sense than accent_color, doesn't it?
![image](https://user-images.githubusercontent.com/29208110/138016147-5e80d9ee-023b-4f04-8cf6-b79ed5ef4335.png)

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/ca85b66b05553612e10a5ca2d2acc79a46ba2bc0
