### ISSUE TITLE
wtf there's a skeleton on my phone and the theme changed I can't change it

### ISSUE THREAD

**Issue by samlux04** [K1rakishou/Kuroba-Experimental#617]
Y tho? They are dancing.
Sometimes it's on the top. Sometimes on the bottom.
Sometimes there's two of them.
I'm scared, am I cursed? What do?

![Untitled1-2](https://user-images.githubusercontent.com/85811479/139519910-c08ebb13-87fa-4523-b777-7c29d5356828.jpg)

**Comment by astroanax** [comment]
It's Halloween, that's why. Nice little addition dev!

**Comment by Pentaphon** [comment]
> What do?

Did you also know...there's also a skeleton inside you, too. Right now.

**Comment by myilu** [comment]
>Did you also know...there's also a skeleton inside you, too. Right now.
>
Wait wait, what? WHAT?!

**Comment by samlux04** [comment]
> > What do?
> 
> Did you also know...there's also a skeleton inside you, too. Right now.

Big if true
