### ISSUE TITLE
how can I enable archive in kuroba ex? 

### ISSUE THREAD

**Issue by starlite-jack** [K1rakishou/Kuroba-Experimental#619]
whenever I want to view the external archive, this happens
![Edited_20211102_212114](https://user-images.githubusercontent.com/90665508/139865855-d4828531-3c49-47ea-b85f-744e348ec97b.jpg)
how do I enable archive viewing?

**Comment by K1rakishou** [comment]
Go to Sites settings, there you will find the archives. Enable them the same way you enabled 4chan.

**Comment by starlite-jack** [comment]
> Go to Sites settings, there you will find the archives. Enable them the same way you enabled 4chan.

![Edited_20211103_210203](https://user-images.githubusercontent.com/90665508/140074974-2d06c0cd-ad7f-4b77-a1d7-99a2a1febad9.jpg)
I tried it and it worked. thanks
