### ISSUE TITLE
Report "Thread downloader location"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#624]
UUID: 05b83aa9756c18df92940cf56bb821e6
Build flavor: stable
Version name: v1.1.2
OS info: Android 11, sdk version: 30
Report description: The default thread downloader location is inaccessible, especially for those who don't have/want root access. Can we change it by default to the internal storage somewhere like /storage/emulated/0/Android/media/ folder?

**Comment by K1rakishou** [comment]
>Can we change it by default to the internal storage somewhere like /storage/emulated/0/Android/media/ folder?

No that's not possible anymore thanks to https://developer.android.com/about/versions/11/privacy/storage
I mean it's possible to select a directory via SAF (Storage Access Framework) on the external storage but it will be slow as fuck (thanks to SAF), literally unusable for huge batched downloads which are required for thread downloading (because you need to download full images and thumbnails). That's why it was decided to use internal storage for that instead. Google hates external storage and SD-cards for some reason so they make it very hard for the devs to use them.

You can export downloaded threads as zipped html page with all the media (Longtap the thread and click export).

**Comment by mag0bei** [comment]
Thanks for the answer. I raised this ticket. The location suggested is internal storage. My point was accessing **/data/user/0/com.github.k1rakishou.chan/files/thread_downloader_storage** is impossible without root while the one suggested is the default for all Android users

**Comment by Luccb** [comment]
what if we want to download the entire thread-downloader folder via ADB?  
perhaps we dont want to mass export multiple threads as zip, maybe device storage is near full,

ive stumbled upon this error:
**_run-as: package not debuggable: com.github.k1rakishou.chan.fdroid_**

is this something the project could choose to enable?

**Comment by K1rakishou** [comment]
@Luccb If I make it debuggable the app will suffer from performance penalty.
