### ISSUE TITLE
Allow bookmarks created by filter watches to go to the default bookmark group or to be affected by bookmark group matchers

### ISSUE THREAD

**Issue by crisalis2** [K1rakishou/Kuroba-Experimental#625]
Please add a setting to optionally allow all bookmarks, even bookmarks which were created by filter watches, to go to the default bookmark group or to be affected by general bookmark group matchers.

I used the old bookmarks tab as a customized "catalog" of sorts (I use grid view), but now that it has merged with the old filter watches tab, and bookmarks created by filter watches are added to their own bookmark groups, the final result I get is basically that I have lost the old bookmarks tab that I liked, because the new bookmarks tab is more like the old filter watches tab.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/43b5747eb635949e54483a31569cc5c635f45cb2

**Comment by crisalis2** [comment]
Thanks!
