### ISSUE TITLE
Allow saving replies as bookmarks

### ISSUE THREAD

**Issue by dennis90a** [K1rakishou/Kuroba-Experimental#627]
Currently I can only mark posts as my own, which is a hack. A better solution would be to just allow bookmarking replies.

**Comment by K1rakishou** [comment]
"Mark post as my own" is exactly what you want. Go to the "My posts" screen to find them all.

**Comment by dennis90a** [comment]
Should i be using it, even when the post isnt my own?

----------------------------------------

Nov 14, 2021 1:46:28 PM Dmitry - notifications at github.com ***@***.***>:

**Comment by K1rakishou** [comment]
I mean what's the difference. It will be marked as yours and you will even receive notifications if someone replies to that post.

**Comment by dennis90a** [comment]
Yeah ig, its the same
