### ISSUE TITLE
Increase "Replies" TextView (in PostCell class) height so it's easier to click.

### ISSUE THREAD

**Issue by dennis90a** [K1rakishou/Kuroba-Experimental#628]
For example, swipe left for viewing replies, right gor going to post, or maybe if #627 is implemented bookmarking, etc

**Comment by K1rakishou** [comment]
You can already do all of that without the gestures. The new gestures will just create unnecessary conflicts (there are already swipe gestures to open the drawer/thread view pane).

**Comment by dennis90a** [comment]
Alright. The reason i thought of gentures is because sometimes the replies button is just too small, i have to click it multiple times to open replies. Maybe an option increasing the replies button size would help.

----------------------------------------

Nov 14, 2021 1:48:19 PM Dmitry - notifications at github.com ***@***.***>:

**Comment by K1rakishou** [comment]
It should take the whole view width so you don't have to click it specifically (exception are the posts on the catalog pane). I could make it slightly bigger, yes.

**Comment by dennis90a** [comment]
> I could make it slightly bigger, yes.
That would be amazing, thanks!

----------------------------------------

Nov 14, 2021 1:54:06 PM Dmitry - notifications at github.com ***@***.***>:

**Comment by K1rakishou** [comment]
I think I already did make them bigger in one of the latest updates. Gonna close this issue.

![image](https://user-images.githubusercontent.com/10332458/154257153-98047f21-5624-4898-b049-c2ce19a1e086.png)

I think this ^ is big enough.
