### ISSUE TITLE
Bug: image preview with transparent background shown with white background in dark mode 

### ISSUE THREAD

**Issue by dennis90a** [K1rakishou/Kuroba-Experimental#629]
![Screenshot_20211114-115724_KurobaEx-fdroid](https://user-images.githubusercontent.com/90372818/141670251-51022d59-07e5-4989-aa0b-7fff806cbf96.png)
On clicking - 
![Screenshot_20211114-115736_KurobaEx-fdroid](https://user-images.githubusercontent.com/90372818/141670253-a2d54c25-f5d7-49a4-bd30-0430d076020e.png)

**Comment by K1rakishou** [comment]
Because that's how the image thumbnail is stored on the server.
https://i.4cdn.org/g/1636869866218s.jpg

**Comment by dennis90a** [comment]
So should I close this?

**Comment by K1rakishou** [comment]
The bot will close it automatically in 4 weeks.
