### ISSUE TITLE
Support for 2ch imageboard archived threads

### ISSUE THREAD

**Issue by acimanx** [K1rakishou/Kuroba-Experimental#647]
Please realize support for 2ch.*/*/arch/ threads.

Google indexes older 2ch threads. For instance, you search on Google for "субкота site:2ch.hk". 
You receive result https://2ch.hk/b/arch/2020-09-16/res/228838338.html
Opening this link with Kurobaex will lead to error 404. 
When expected behaviour is a normal thread view.

2ch using archive integration on the website.
Example is https://2ch.hk/b/arch/ https://2ch.life/mobi/arch/ https://2ch.hk/pr/arch/ ... etc.
Please keep in mind that archived thread support on 2ch is very selective and is not working for all the boards, so realization should be flexible.

**Comment by K1rakishou** [comment]
It already supports archived threads you just can't open them via the link.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/19958d3a9aa1b305290c8c999b39198ab6149a79
