### ISSUE TITLE
Ability to explore Tor only chan sites.

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#650]
Could that be possible within the app with a Tor wrapper or would a whole new app have to be made?

**Comment by K1rakishou** [comment]
I guess you need to implement the site support and then enable tor and it should work?

**Comment by ghost** [comment]
Have you ever thought of that as a side project or something that you could look into in the future?

**Comment by K1rakishou** [comment]
I mean it should work in this app, you just need to add the site support. There is the overchan app that supports some tor imageboards for example, so it's possible. See https://github.com/overchan-project/Overchan-Android/blob/master/AndroidManifest.xml#L150

I guess tor does all the work for you (figures out where to connect to) and you just need to add the site support.

**Comment by ghost** [comment]
Thanks for responding with this info
