### ISSUE TITLE
Invalid proxy settings crashes KurobaEx

### ISSUE THREAD

**Issue by InvisibleRain** [K1rakishou/Kuroba-Experimental#657]
Release: 1.1.6 from F-Droid

Steps to reproduce:
1. Clear data in android settings for KurobaEx
2. Launch app, go to Settings => Security => Proxy Settings
3. Add a new SOCKS5 proxy with an invalid address (e.g. 127.0.0.1 port 1080 assuming no process is listening on that port) 
4. Select Lainchan in proxy settings and check all three checkboxes in the Actions section. Click save, then restart the app
5. Go to Settings => Sites and enable Lainchan

Expected result:
Lainchan is enabled

Current result:
App crashes

This issue isn't unique to Lainchan. I was also  able reproduced it on Endchan and Kohlchan

**Comment by K1rakishou** [comment]
Doesn't crash for me. Just can't load the site catalog (which is expected).

**Comment by InvisibleRain** [comment]
Here's the error log. I hope that will help to find the issue
[=== LOGS(2021-12-08 145658 UTC) ===_2021-12-08-18-03.txt](https://github.com/K1rakishou/Kuroba-Experimental/files/7678007/LOGS.2021-12-08.145658.UTC._2021-12-08-18-03.txt)

Feel free to ask any additional information if needed

**Comment by K1rakishou** [comment]
Oh this. Yeah I saw these crashlogs, but alas, I don't think I can do anything here since it crashes somewhere deep inside of Java and I can't even reproduce it locally.

>at java.net.SocksSocketImpl.privilegedConnect(SocksSocketImpl.java:94)

Do you use a custom ROM by any chance?

**Comment by InvisibleRain** [comment]
I'm using stock vendor-specific ROM, but never flashed it myself, nor do I have root privileges on the phone.
However, I was able to crash the app in a similar way on Anbox x86. Unfortunately, my Anbox break since then and I doubt I'll be able to extract any logs.

What's regarding socks proxy on the phone - it works fine in Firefox through FoxyProxy and on [Dollchan](https://github.com/Mishiranu/Dashchan) through plugins
