### ISSUE TITLE
how to select specific part of a text from a thread 

### ISSUE THREAD

**Issue by starlite-jack** [K1rakishou/Kuroba-Experimental#661]
in kuroba dev, it's possible to select a specific part of a text from a thread
![2021_12_06_07_41_28](https://user-images.githubusercontent.com/90665508/144848228-24d8aa4f-f24b-42e9-b674-5a46cc91dd6a.jpg)
the picture above is kuroba dev. as you can see, I can select a text from a thread in kuroba dev just fine but when I try it on kuroba ex, it only showed me the context menu 
![Edited_20211206_193115](https://user-images.githubusercontent.com/90665508/144848523-2b4b89cd-f903-490a-8da9-baa51dbb5810.jpg)
the option from the context menu in kuroba ex only lets me quote/copy the entire text from a thread.

i want to only select a specific part of a text from a thread. if kuroba dev lets me do this then how do I do the same in kuroba ex?

**Comment by myilu** [comment]
Double tap.

**Comment by jason-1001** [comment]
> Double tap.
thanks, it worked

**Comment by starlite-jack** [comment]
> Double tap.

thanks, it worked
