### ISSUE TITLE
Onion boards

### ISSUE THREAD

**Issue by yephny** [K1rakishou/Kuroba-Experimental#663]
Add .onion boards that are accessible only in Tor. Could require the user to download Orbot or another Tor proxy implementation.

**Comment by K1rakishou** [comment]
See https://github.com/K1rakishou/Kuroba-Experimental/issues/650

**Comment by K1rakishou** [comment]
Just for clarification: you need to add the site support by yourself, I don't do that except certain sites (If I feel like doing that). It should be possible and shouldn't be hard, tor already does all the work for you.

**Comment by yephny** [comment]
I specifically looked for a way to add a site (whether it be onion or not) to KurobaEx but couldn't find a way. Does the app not have a custom site support, so that I have to compile it every time I want to add a site?

**Comment by K1rakishou** [comment]
>Does the app not have a custom site support, so that I have to compile it every time I want to add a site?

Of course.
