### ISSUE TITLE
Report "Images and video not able to be rendered on image boards other than 4chan"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#674]
UUID: ae38076f6954947dada72d00a23d6cf1
Build flavor: fdroid
Version name: v1.1.6
OS info: Android 9, sdk version: 28
Report description: The issue from what I can tell is that on sites like 8chan, the app can't load/render media. I believe it has to do with the fact that they are behind html and not just an image, although I'm not technical enough to say for sure.

**Comment by K1rakishou** [comment]
8kun sends incorrect response for thumbnails that do not exist on the server. The status code of the response is 200 but they send the 404 html page. This is the site's fault, not mine. The images does not exist anyway.

![image](https://user-images.githubusercontent.com/10332458/146635098-1356cb61-457e-4f44-8b71-130afd07ff60.png)


![image](https://user-images.githubusercontent.com/10332458/146635108-46f42591-cc4b-482e-9026-65f15093f718.png)

**Comment by K1rakishou** [comment]
>Images and video not able to be rendered on image boards other than 4chan

What other sites don't display media?

**Comment by cuteasci** [comment]
> > Images and video not able to be rendered on image boards other than 4chan
> 
> What other sites don't display media?

2ch. It says decoding file preview but still nothing 
![IMG_20211231_011811](https://user-images.githubusercontent.com/59581277/147791536-be18d8a1-1c63-43d5-8655-ebd028defe3c.jpg)

**Comment by K1rakishou** [comment]
That's a completely different thing.
