### ISSUE TITLE
Newlines Don't Render Properly on 8kun

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#685]
I haven't seen this issue posted here after a brief search but it's a big one. For the past couple months, ever since the site loading issue with it was fixed (if I recall correctly), I have not had newlines render properly on 8kun threads. Just in case this issue is specific to phone models, I have a OnePlus 6T. An image of the problem in action ([using this thread as a demonstration](https://8kun.top/tech/res/965329.html)) follows and it persists across boards.

![Screenshot_20211223-173952_Trebuchet.png](https://user-images.githubusercontent.com/10644674/147297302-a2c4eb77-da84-497c-be72-2fb61fabc3e3.png)

**Comment by K1rakishou** [comment]
Oh, looks like 8kun uses `</p>` tag instead of `<br>` like most of the other sites for newlines.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/8532b803d0a6f2d647d8d2a9379f7838bb27db34
