### ISSUE TITLE
Feature request "Disable app easter eggs on demand"

### ISSUE THREAD

**Issue by acimanx** [K1rakishou/Kuroba-Experimental#686]
Dear @K1rakishou , thank you for a great app that I'm using every day! I wish you a happy christmas and happy new year!

I've really appreciated your message in changing theme before christmas with falling snow and other bells and whistles. But please make an option for user to decide to use such easter eggs or not. 
Best regards.

**Comment by K1rakishou** [comment]
I will add it. In 2022.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/3cedb62a778d4e2015781c0bd7cbf6c470503441
