### ISSUE TITLE
Report "4chan reporting still requires captcha even if user has a pass"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#692]
UUID: d59727d1c6d3e2d9024698a165df9fd6
Build flavor: stable
Version name: v1.2.4
OS info: Android 11, sdk version: 30
Report description: Still happening as of 1.2.4
Tried uninstalling and reinstalling, no dice.
Doesn't happen on base Kuroba (version 4.13.6)
Posting is fine, it's just that reporting still asks for a captcha.
Still understandable if it can't be fixed due to not wanting to buy a pass.

**Comment by K1rakishou** [comment]
Yes it doesn't work because the pass is not supported (because I don't have one to test it).

**Comment by iodine-dev** [comment]
> Yes it doesn't work because the pass is not supported (because I don't have one to test it).

Hi, this blocker should be fixed now if you check your email; thanks for keeping up with this!

**Comment by K1rakishou** [comment]
Thanks for the pass.

>Blocker

This is not a blocker. 
But I will fix it myself now that I can test it.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/4193321f2d08065397655b74325d023a76de100e
