### ISSUE TITLE
Report "Can't download images due to new Android filesystem crap"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#695]
UUID: 27cd5690ece2b00dceb96f1744bd5ab8
Build flavor: fdroid
Version name: v1.1.6
OS info: Android 10, sdk version: 29
Report description: When trying to download a file from 4chan I get a notification saying, "Finished downloading with 1 errors. Failed to access root directory. Click 'show settings' and then check that it exists and you have access to it!"

Clicking on the "show settings" button just causes the message, "Root directory is inaccessible" to briefly appear with nothing else.

I can't change any download settings in the app to fix this and the app already has storage permissions.

**Comment by K1rakishou** [comment]
Did you try clicking the big shining button? For whatever reason the permissions to that directory were lost and that's why it's inaccessible now, you need to select it again.

![image](https://user-images.githubusercontent.com/10332458/147754066-90d3541e-4881-469f-9f03-cd8b5e7d1b85.png)

**Comment by Enchoseon** [comment]
Ah, that button wasn't appearing for me, but clicking on the text itself opened up the prompt.

![Screenshot_20211230-115152](https://user-images.githubusercontent.com/38841444/147783864-556bc93a-5b53-49c0-8552-77a7dfd7e2e0.png)

**Comment by K1rakishou** [comment]
Yes it's the same thing. I probably should add a warning icon on top of it if the directory becomes inaccessible.
