### ISSUE TITLE
Feature Request - Tap once to close media

### ISSUE THREAD

**Issue by stealsfromhobos** [K1rakishou/Kuroba-Experimental#700]
Just a small detail from clover I liked.  Simply tapping an open image once would close the image viewer.  I understand there are swipe gestures that can do this but I preferred the tap.

**Comment by K1rakishou** [comment]
Tap gesture is already occupied by enter/exit fullscreen mode feature like what most of other media viewers do when you tap it. Clover didn't have fullscreen mode in the media viewer that's why it was possible to use tap gesture.
