### ISSUE TITLE
Copy Pasting Greentext is Colored?

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#709]
When copying greentext, it copies it with color instead of as plaintext.
I can see it as purple in my clipboard.
Using AnySoftKeyboard if it matters.

**Comment by K1rakishou** [comment]
You mean this copy? It's what the system puts there and handles itself.

![image](https://user-images.githubusercontent.com/10332458/148196280-32164ef5-f3ce-4728-8865-248adfa4a0a1.png)

Here is the handler method:

![image](https://user-images.githubusercontent.com/10332458/148196555-d0b0122d-ea7e-4c9d-af64-aae100a6a00c.png)

It just takes the part out of the CharSequence so obviously it copies the Spans as well which make the text colored.

![image](https://user-images.githubusercontent.com/10332458/148196598-a8f415c8-c160-4c4c-9ba8-8792f2b45964.png)

**Comment by seniorm0ment** [comment]
Yes that
Ok :/
