### ISSUE TITLE
(feature request) The Eye 

### ISSUE THREAD

**Issue by baraa272** [K1rakishou/Kuroba-Experimental#714]
Hello awesome dev 
Is there anyway to implement third eye ? 
Something that parse md5 in the name of images and search that md5 on popular sites like gelbooru/ATF Moe / rule34 and display the picture inside application ?
There is a userscript that can do that already for desktop but I'm asking if it can implemented in kuroba ?

**Comment by K1rakishou** [comment]
Already implemented 
https://github.com/K1rakishou/Kuroba-Experimental/commit/f3441a4995574b2a2b8bfc3442875bf52193c49b

**Comment by baraa272** [comment]
Nice thanks dev
