### ISSUE TITLE
Can't do much on a post besides copying text from it

### ISSUE THREAD

**Issue by a84r7a3rga76fg** [K1rakishou/Kuroba-Experimental#715]
Reviving this issue: https://github.com/K1rakishou/Kuroba-Experimental/issues/553

Video https://streamable.com/t2egnz

Very often it'll only let you copy text from a post, making it impossible to click on the post numbers. I've this issue on Nokia 5 and on Redmi Note 10.

**Comment by K1rakishou** [comment]
Yeah I remember this but I can't reproduce it and judging that I haven't seen anyone else reporting anything similar it's probably something your OEM did with the OS that causes this.

**Comment by cuteasci** [comment]
Same happens to me on MIUI.
 

Try tap and hold at that location and see the menu 

![IMG_20220111_234113](https://user-images.githubusercontent.com/59581277/149018367-5c97e2b3-208f-4ca8-b44c-4e171c2a8c7f.jpg)
![Screenshot_2022-01-11-23-42-27-135_com github k1rakishou chan beta](https://user-images.githubusercontent.com/59581277/149018434-0c9dd8ea-015e-49d2-b547-c82b67a87d2e.jpg)

**Comment by K1rakishou** [comment]
@cuteasci I don't think it's related to what @a84r7a3rga76fg is talking about. He is talking about the menu that appears when you doubletap post comment.
