### ISSUE TITLE
Report "can't open archive like via a quoted post"

### ISSUE THREAD

**Issue by K1rakishou** [K1rakishou/Kuroba-Experimental#716]
UUID: 65c668a170f1da952627305840da9101
Build flavor: stable
Version name: v1.2.4
OS info: Android 10, sdk version: 29
Report description: I checked with the archive site and the deleted post was there, but Kuroba can't open it.
for example, in thread thread https://boards.4chan.org/vg/thread/367857130 I tried to click the quoted post to 367916774 but I got a timeout error.
I have the archive site (arch.b4k.co) enable.

**Comment by K1rakishou** [comment]
Worked for me. Seeing that it's a timeout exception maybe there was some kind of a network problem at that moment.

**Comment by cordelia04m** [comment]
Weird. I tried it again but I still couldn't view the post, but for other archive sites worked fine. Guess the issue is solved now.
