### ISSUE TITLE
Option to switch 3dot menu and comments button in media viewer 

### ISSUE THREAD

**Issue by antglove** [K1rakishou/Kuroba-Experimental#721]
When i use my phone with the right hand its uncomfortable to reach the comments button
![faefac](https://user-images.githubusercontent.com/66039822/149570675-bf90acb8-2e75-4a29-8cf1-7040f6f83c67.jpg)

**Comment by K1rakishou** [comment]
Oh yeah I should probably make this thing reorderable.

**Comment by K1rakishou** [comment]
Actually already implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/303792f3451400f3fe85c13041ee6c28956e9298
