### ISSUE TITLE
how do I clean the bookmark button's notification? 

### ISSUE THREAD

**Issue by starlite-jack** [K1rakishou/Kuroba-Experimental#727]
![Edited_20220202_051415](https://user-images.githubusercontent.com/90665508/152061324-28ff8439-5085-47f2-bb5c-b09b2612b316.jpg)
as you can see from the image above, the bookmark button has notification sign. what I want to do is to clear those notification sign from the bookmark button.

how do I do that?

**Comment by K1rakishou** [comment]
Three dot menu -> Mark all bookmarks as read and clear notifications
