### ISSUE TITLE
Option to turn off swipe down to download on media

### ISSUE THREAD

**Issue by untitled-operator** [K1rakishou/Kuroba-Experimental#728]
When swiping media anywhere I would like for it to just dismiss the media and go back to the thread. swiping down brings up the download prompt and isn't an option I will ever use. Holding for options is the only additional way I'd like to interact with images, videos, etc.

**Comment by untitled-operator** [comment]
I'm aware with enough velocity, it will dismiss regardless, but this isn't consistent, and I will never act on the download gesture anyways.

**Comment by K1rakishou** [comment]
Open any image -> three dot menu -> gesture settings -> disable both of them.

**Comment by untitled-operator** [comment]
Thanks! I was able to get it there. I do still believe it should be in settings with the rest of the options, but this solved the problem
