### ISSUE TITLE
Option to mute all media

### ISSUE THREAD

**Issue by untitled-operator** [K1rakishou/Kuroba-Experimental#729]
Under the media tab, it should have an option to "mute all media" with an option for "always", "never", or "remember last set".

**Comment by K1rakishou** [comment]
There is already the mute button which is turned on (media is muted) by default unless you have headphones connected. You can toggle it and it will keep being toggled until you close the media viewer. There are also "start videos muted" and "mute headset videos" settings which will toggle the default state of the mute button.

**Comment by untitled-operator** [comment]
This solved the issue! I do believe this and the media gestures should be in the settings panel as well, but this fixes the issue. I appreciate the app!
