### ISSUE TITLE
nyafuu is going down (data transfer to archive.alice.al)

### ISSUE THREAD

**Issue by kimsin98** [K1rakishou/Kuroba-Experimental#734]
https://archive.nyafuu.org/_/articles/shutdown/

remove https://archive.nyafuu.org/
add https://archive.alice.al/

**Comment by K1rakishou** [comment]
The new archive support is already added (but not released yet), see https://github.com/K1rakishou/Kuroba-Experimental/commit/ded4f817062b3028e16496d9c452abb69a402d55
The old one will stay until it's 100% dead.
