### ISSUE TITLE
2ch.hk pass not working

### ISSUE THREAD

**Issue by meugr** [K1rakishou/Kuroba-Experimental#735]
2ch.hk pass return bad status code 303 in response.priorResponse.
PassCode is valid and work from web browser

**Comment by K1rakishou** [comment]
I don't have a passcode so I can't even check. Someone with a passcode will have to check this issue.

**Comment by meugr** [comment]
I can give you passcode for testing, but, not in public. Сan I send pass to kez1911@protonmail.com?

**Comment by K1rakishou** [comment]
Yes, you can send it to my email.

**Comment by meugr** [comment]
Done

**Comment by K1rakishou** [comment]
Alright give me an hour I will check what's going on there.

**Comment by K1rakishou** [comment]
Should be fixed in the next release. 
https://github.com/K1rakishou/Kuroba-Experimental/commit/d9c7ded581b17de74366b97e7df6af831242d932
