### ISSUE TITLE
Broken theme(?) behavior idk

### ISSUE THREAD

**Issue by Gugui322** [K1rakishou/Kuroba-Experimental#738]
**See**
https://boards.4chan.org/g/thread/85769259

Log:
https://mega.nz/file/Xd0BGaCJ#_R6VGhYU2PEX8MBZG-lRiPr8U0KSOlgsTObImrMiAKM

**Comment by K1rakishou** [comment]
Hmm, very interesting. Most likely PrecomputedTextCompat.getTextFuture() doesn't work as I expected it to work.

**Comment by Gugui322** [comment]
> Hmm, very interesting. Most likely PrecomputedTextCompat.getTextFuture() doesn't work as I expected it to work.

So i will close this, if you need more info i will reopen the issue.

**Comment by K1rakishou** [comment]
No you don't need to close it, it's an actual bug and needs to be fixed.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/5188a1d28f9099daced004def9d0f984e7dde547

**Comment by telometto** [comment]
I'm experiencing the same issue. When will the update make it into the official release?

![676.jpg](https://user-images.githubusercontent.com/65364211/155290294-cb501e4d-786b-4c5a-98aa-37df0c9158d3.jpg)

**EDIT:** nvm I have updated to the latest version. Thanks.
