### ISSUE TITLE
missing boards on 420chan.org

### ISSUE THREAD

**Issue by IAUMD** [K1rakishou/Kuroba-Experimental#739]
/psy/, /stim/...etc and non-drug related boards on the site lifestyle, misc, adult, academia...etc are not available to add from the boards list on 420chan

**Comment by K1rakishou** [comment]
Update the board list? Works for me.

![image](https://user-images.githubusercontent.com/10332458/157225499-54187ce4-d00f-4840-b270-f1c8010b4446.png)
