### ISSUE TITLE
Post numbers don't become bold when clicking on a reply within a chain

### ISSUE THREAD

**Issue by bungholemaster** [K1rakishou/Kuroba-Experimental#740]
On the latest version, seems like this got broken in an update because it worked before. Although I do remember this being iffy if you went back and forth within a post chain before and not working completely right still.

If you click on the replies to a post directly the post number in the replies becomes bold like it should, but if you do it from within a reply chain it does not. Makes following post chains with multiple quotes much more difficult.

Here's a video showing the issue:

https://user-images.githubusercontent.com/16147700/155432261-7123e697-0e2e-4049-b740-bbba6b46a303.mp4

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/8acad319735555723f660f7c2cdda9328d634e93
