### ISSUE TITLE
Ability to put the scroll bar on left

### ISSUE THREAD

**Issue by H3n-beep** [K1rakishou/Kuroba-Experimental#741]
Im righthanded and sometimes i accidently touch the bar and go up/down and i rarely use it and would like the ability to either remove it or change its placement

**Comment by myilu** [comment]
Settings > Appearance > Draggable scrollbars
You can disable it or select "Scroll only when dragging thumb".

**Comment by H3n-beep** [comment]
But what about putting it on left?

**Comment by H3n-beep** [comment]
But what about putting it on the left?

**Comment by K1rakishou** [comment]
It will be conflicting with the drawer gestures.
