### ISSUE TITLE
8kun boards

### ISSUE THREAD

**Issue by 8b17-cfg** [K1rakishou/Kuroba-Experimental#744]
I frequent a board on 8kun called /hivemind/ which is missing from the boards list in the app when I try to add it. I guess this is probably due to the nature of 8kun having user-created boards which can show up at any time and not automatically be supported by Kuroba.
Would it be possible to manually add that board to the list of supported boards for 8kun? It would be hugely appreciated.

Thank you!

**Comment by K1rakishou** [comment]
You should be able to just enter "hivemind" into the board selection menu's search input and then click the button under 8kun boards.

**Comment by 8b17-cfg** [comment]
Yeah, that's what I've tried, but it doesn't seem to show up, so there is no button/check-box for that specific board.

**Comment by K1rakishou** [comment]
I mean this menu

![image](https://user-images.githubusercontent.com/10332458/156819576-1e77d07f-4ffe-49fc-9044-963d62bd3022.png)

**Comment by 8b17-cfg** [comment]
Ahh, I got you now. Thanks!
