### ISSUE TITLE
When scrolling through webms, the progress bar shows up when it should stay hidden (annoying)

### ISSUE THREAD

**Issue by tonijarjour** [K1rakishou/Kuroba-Experimental#745]
If you tap a couple times on webms, the entire menu UI will disappear and the webm is clearly visible.
But when you start scrolling through, the progress bar shows back up. This is just plain annoying. 

Heres a video showing it happening: https://youtu.be/hcMgYrhY71Q

**Comment by K1rakishou** [comment]
Seems to be a bug in ExoPlayerVideoMediaView because when using mpv there is no such behavior.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/97685b24ef558990fa619c208165f9535f1bc922
