### ISSUE TITLE
How do view the files from the thread downloader without root? 

### ISSUE THREAD

**Issue by HASJ** [K1rakishou/Kuroba-Experimental#752]
Is there any way to change the default directory?
The only option I've found is to export the thread into a zip file but that just simply isn't useful.
Duplicate files also start becoming an issue after a while.

**Comment by K1rakishou** [comment]
Just open it, you will be redirected into the thread where you will be able to see all the files, use gallery, even download them (which will essentially copy them from one directory to another)

**Comment by HASJ** [comment]
But there is no way to change the directory? I just want to upload my saved threads to the cloud.
Kuroba is eating 80gb. You know... /gif/

**Comment by K1rakishou** [comment]
No there is no way because of SAF. You can export them as HTML with all the files, though.
