### ISSUE TITLE
4chan added Emojis now

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#753]
The title says it all, 4chan now has emojis, and I want the ability to post them and also to see them now

**Comment by K1rakishou** [comment]
They will be gone by tomorrow.

**Comment by ghost** [comment]
@K1rakishou rlly? Damn I didn't know

**Comment by samlux04** [comment]
> They will be gone by tomorrow.

Okay but what are the political implications of emojis on 4chin?
![](https://i.4cdn.org/pol/1648839373483.png)

**Comment by baraa272** [comment]
they aren't gone, also they disabled roll system and unlock all emoji for everyone

**Comment by Gugui322** [comment]
> they aren't gone, also they disabled roll system and unlock all emoji for everyone 
> 

It is over

**Comment by maxcutlyp** [comment]
From poking around in the code, it seems like this will need to start at [`chan.core.site.parser.CommentParser::handleImg`](https://github.com/K1rakishou/Kuroba-Experimental/blob/163387a61b09333e70cb790165140d575d0f0bc7/Kuroba/app/src/main/java/com/github/k1rakishou/chan/core/site/parser/CommentParser.java#L297), with a check for the class containing `xae`. I'm not sure if the functionality to embed an image in the comment text exists ~~(I don't think it does)~~ but that seems better suited to someone more familiar with the codebase.

Edit: actually, it could work similarly to how the youtube logo is embedded after youtube links

**Comment by Gugui322** [comment]
> From poking around in the code, it seems like this will need to start at [`chan.core.site.parser.CommentParser::handleImg`](https://github.com/K1rakishou/Kuroba-Experimental/blob/163387a61b09333e70cb790165140d575d0f0bc7/Kuroba/app/src/main/java/com/github/k1rakishou/chan/core/site/parser/CommentParser.java#L297), with a check for the class containing `xae`. I'm not sure if the functionality to embed an image in the comment text exists ~~(I don't think it does)~~ but that seems better suited to someone more familiar with the codebase.

Here maybe this can help

https://gitlab.com/anonanonymous/4chan-emote/-/blob/master/emote.js
