### ISSUE TITLE
Add support for PEE (PNG Extra Embedder)

### ISSUE THREAD

**Issue by bungholemaster** [K1rakishou/Kuroba-Experimental#763]
https://git.coom.tech/fuckjannies/lolipiss

I believe it incorporates Third Eye which is already supported by the app but this is much more robust. 
Not sure how realistic it would be to add.

**Comment by K1rakishou** [comment]
Is it even still possible to embed stuff into pngs? And then again, even if it's possible you will just get banned if they notice it. So yeah, probably kinda pointless to implement it. And it's too much work so I'm not going to do that 100%.

**Comment by ctr305** [comment]
I'm pretty sure that the current version just puts links to file hosts such as catbox into the image's metadata, which just barely skirts the rules since the image isn't ACTUALLY embeded

**Comment by K1rakishou** [comment]
So I had nothing to do and decided to actually add support for this thing. Only decoding is implemented, meaning you won't be able to embed files only view already embedded files. For now everything works except the embedded videos which will be fixed shortly.
https://github.com/K1rakishou/Kuroba-Experimental/commit/c07508c0ca93d0536e2f38480abf4e72ef4603a6

**Comment by K1rakishou** [comment]
Lmao, just as I decided to implement this the mods started detecting the new method of embedding. I guess I will wait a little bit and see where it goes next.

**Comment by K1rakishou** [comment]
In the end, I decided to not implement this thing.
