### ISSUE TITLE
No option to quote

### ISSUE THREAD

**Issue by floppyD** [K1rakishou/Kuroba-Experimental#765]
I saw some Xiaomi related changes recently so maybe it's related? This is the first time I'm using Kuroba on this device so no idea if it ever worked.

https://user-images.githubusercontent.com/29208110/170818144-56b2b63d-ace4-444d-8b5e-cda5bbf759ae.mp4

**Comment by K1rakishou** [comment]
I have no idea, tbh. I don't have a xiaomi device to test.

**Comment by floppyD** [comment]
It's weird because the selection thing looks different in basically every other app, KurobaEx is the only one so far I recall seeing that weird one in OP. Maybe you can take a look at what Wikipedia is doing? Their app is FOSS
![Screenshot_2022-06-12-14-22-13-622_org wikipedia](https://user-images.githubusercontent.com/29208110/173245494-9157dcb6-cae3-41a8-abd4-5624b00d9c15.jpg)

**Comment by K1rakishou** [comment]
I set custom colors to that thing depending on your theme and that apparently make it look weird on xiaomi phones. I have no idea why.

**Comment by floppyD** [comment]
Is it possible to offer an option to not theme it so it doesn't break?

**Comment by K1rakishou** [comment]
Yes it's possible. It probably won't fix the menu items disappearing, but it should fix the weird scaling issue.
Maybe I will add it as a developer setting for now because I don't want to hardcode it for xiaomi only (other phones may have similar issues).

**Comment by floppyD** [comment]
I forgot to mention it earlier, but it looks normal under the in app report form. Also there's some weirdness like I show in the beginning.

https://user-images.githubusercontent.com/29208110/173349525-48827c1d-c716-48b1-b753-d5c16176dc9c.mp4

**Comment by K1rakishou** [comment]
Huh, interesting. So it might even be fixable.

**Comment by K1rakishou** [comment]
What Android version do you use, btw?

**Comment by floppyD** [comment]
Pretty sure in OP it was Android 10/MIUI 12.something, now I'm using Android 11/MIUI 13.0.1. It looks identical.

**Comment by K1rakishou** [comment]
Oh wait, here https://github.com/K1rakishou/Kuroba-Experimental/issues/765#issuecomment-1153830827 I'm using Jetpack Compose to build that screen which implements it's own text selection cursor + selection handles which are system independent (xiaomi can't override them with it's own implementation), that's why it works.

**Comment by floppyD** [comment]
I tried every app that allows me to input anything, none of them uses the highlight marker Kuroba is using at the moment, most look like this (with different colors depending on the app) or like the Wikipedia one. Not even Xiaomi stock apps uses anything different. Weird stuff
![Screenshot_2022-06-13-10-59-35-663_com google android dialer](https://user-images.githubusercontent.com/29208110/173371318-30e4ebab-e795-4cbc-974c-f3a891dbb59e.jpg)

**Comment by K1rakishou** [comment]
I've added a setting to disable changing text selection cursor colors. Can be found in the experimental settings. Hopefully it should help.
https://github.com/K1rakishou/Kuroba-Experimental/commit/d0d718717c3a04731049c41e4a555db7ea0d044b

**Comment by floppyD** [comment]
yep, it's not broken as before
![Screenshot_2022-06-19-16-23-19-729_com github k1rakishou chan beta](https://user-images.githubusercontent.com/29208110/174497197-07393956-30f3-450c-bfa7-374930feb72c.jpg)

**Comment by K1rakishou** [comment]
Closing as fixed.

**Comment by floppyD** [comment]
I mean, you still can't quote, but the cursor is not visually broken anymore.
