### ISSUE TITLE
Lack of dynamically colored status bar

### ISSUE THREAD

**Issue by obscenelyvague** [K1rakishou/Kuroba-Experimental#766]
The status bar portion of the app seems to be using a solid black color alongside a fixed height. This creates a problem on certain devices where the action bar has abnormal padding and appear too close to status bar icons. Which in turn causes the status bar icons to not be aligned to the center relative to the status bar. Here's a stitched together image from an app that also has a colored action bar and _does_ have the action bar height and dynamic status bar color aspect done right [compared](https://i.ibb.co/DL06jxz/k.jpg) to KurobaEx.

Other possibly relevant information:
Android 12, AOSP
Display resolution - 1080*2400, 20:9

**Comment by K1rakishou** [comment]
I honestly don't know. Seems like this is something device specific.
