### ISSUE TITLE
Wrong board by default

### ISSUE THREAD

**Issue by khezuu** [K1rakishou/Kuroba-Experimental#770]
the default board that opens when you start the app was the first board in the list however now for some reason it opens 4chan /b/ for me as default even when i DELETE the whole board.

https://pastebin.com/HaKzFzBy

**Comment by K1rakishou** [comment]
Maybe because of the history? "Restore last visited catalog upon app start" option in the drawer.

**Comment by khezuu** [comment]
Yes but why does the app assume a catalog that I never used to begin with even when i delete it. I even uninstalled the app and cleared data, after a few uses it will revert to the old behavior. Weird.
