### ISSUE TITLE
"Uploading 96%..." notification stuck in status bar

### ISSUE THREAD

**Issue by zn-a** [K1rakishou/Kuroba-Experimental#771]
Sometimes when you attach a file (from "searx image search") and hit post, the "Uploading %..." notification gets stuck at 96%, eventhough the file was uploaded and posted. You have to force stop the app to get rid of it. App ver: v1.3.9

**Comment by K1rakishou** [comment]
Should be fixed by https://github.com/K1rakishou/Kuroba-Experimental/commit/f3b12887b148347a3a76fb62079683e28865f319
