### ISSUE TITLE
Tedious manual intervention needed to resolve conflicts 

### ISSUE THREAD

**Issue by obscenelyvague** [K1rakishou/Kuroba-Experimental#772]
It is fairly common for different media files to share the same file name. It can be kind of tedious to have to manually resolve the conflicts every single time. This can be alleviated in one of two ways.

1. Allow configuring the default behavior for when duplicates are found alongside an "Ask every time" option in settings.

Or

2. Introduce checksum verification alongside the file name check and only prompt the user about what they want to do if the checksum matches; save with duplicate number prefix in name otherwise.

**Comment by K1rakishou** [comment]
I guess this is related to https://github.com/K1rakishou/Kuroba-Experimental/issues/816 and it was implemented (partially, but it's better than nothing)
