### ISSUE TITLE
Privacy control against the Chans

### ISSUE THREAD

**Issue by unalignedcoder** [K1rakishou/Kuroba-Experimental#773]
It would be great if the user was given a bit of privacy control against the various channels.

The ability to delete cookies (while not losing any local preferences on the app), or otherwise being seen by the remote Chan as a new/different user; having transparency on how this can be achieved (cookies + change of ip number suffices?) would be a great addition to this app.

Edit: The only setting I've found relating to this, is the ability to reset the captcha cookie from within the site's settings. However it's not clear what the user achieves by performing this single action.

**Comment by K1rakishou** [comment]
4chan uses cookies to check whether you are banned or not even if you change the IP, so resetting cookies helps with that.
