### ISSUE TITLE
Filters that remove are showing as hidden

### ISSUE THREAD

**Issue by ShosuroJM** [K1rakishou/Kuroba-Experimental#775]
Hi,

I have a filter that removes all non real countries post in /pol/ and it seems that instead of removed status (not seeing them) I'm seeing them now as hidden.

I'm using KurobaEx-fdroid v1.3.10 commit ca374cedb963

Thanks

**Comment by K1rakishou** [comment]
I will need that filter to debug the issue. You can export them when from the Filters screen.
