### ISSUE TITLE
Feature request: Merging external sound with video on download, and seperating on upload (4chan)

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#779]
It would be great if you could upload webm files with sound and have the app strip its audio track and upload to catbox + add the URL to the filename by itself.

And on the opposite end, if you could download a video with an external sound file and have them merge back into each other automatically. This wouldn't be possible with ie mp3->webm like it is for ogg->webm, so a warning of quality degradation/re-encoding would be good, to be able to disable it and just keep a link to the original file in the filename. An option to set for this would be best.

**Comment by K1rakishou** [comment]
That's waaaay to much work and I will need to bundle ffmpeg which will increase the app size by 50 megabytes.

**Comment by floppyD** [comment]
Nvm, sound playing is already supported
