### ISSUE TITLE
AppLock for Kuroba-Ex

### ISSUE THREAD

**Issue by spectkiller** [K1rakishou/Kuroba-Experimental#781]
Considering the risky nsfw nature of these imageboard, a AppLock make sense, also with a option to hide app's preview in recent screen.

**Comment by K1rakishou** [comment]
Aren't there other apps out there that can do this job?

**Comment by spectkiller** [comment]
> Aren't there other apps out there that can do this job? 

Yes, there're but it would be nice to have a inbuilt lock like these app, where they just use the system lock/fingerprint. So not even need to implement your own lock abilities.

**Comment by K1rakishou** [comment]
Yeah, I don't know about that, seems like an overkill for this app.
