### ISSUE TITLE
Text pointer is black when "colorize text selection cursors" is disabled

### ISSUE THREAD

**Issue by floppyD** [K1rakishou/Kuroba-Experimental#784]
It's really hard to see it on dark themes. Kuroba can theme them without breaking the cursor on Xiaomi so I guess it's possible.

KurobaEx
![Screenshot_2022-08-08-14-24-55-942_com github k1rakishou chan](https://user-images.githubusercontent.com/29208110/183477612-8f5d4e59-ca0b-4938-b241-ea1cd82e5878.jpg)

Kuroba
![Screenshot_2022-08-08-14-27-05-656_com github adamantcheese chan dev](https://user-images.githubusercontent.com/29208110/183477687-3115f210-727f-479f-8c8c-0b32d058e431.jpg)

**Comment by K1rakishou** [comment]
By the way what android version is this?

**Comment by floppyD** [comment]
Android 11, MIUI 13.0.1

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/a2b034dd136737ab77675302be6707198b74f564
Hopefully this won't break the drag handles again. If it does then I will revert it to how it is now. Also only for Android 10+.
