### ISSUE TITLE
How to use the Third Eye? 

### ISSUE THREAD

**Issue by darlopvil** [K1rakishou/Kuroba-Experimental#785]
Hello, 
So i've just seen here a previous post of January, i think, where how this thing works got questioned. After importing the file do i need to tap on something? How does this the issue? 

Tried to look for info on the Internet but i don't get anything relevant.

**Comment by K1rakishou** [comment]
You just scroll over posts with images that have specific file names (they are marked with yellow on the scrollbar I think) and if it's actual content id then it will be loaded and displayed in that post.
