### ISSUE TITLE
Bookmark Groups - feature hidden/add

### ISSUE THREAD

**Issue by SD-Tre** [K1rakishou/Kuroba-Experimental#788]
Current; Long press on a bookmark, and use move to bring up the bookmarks group.

Issue; no method of managing the book mark groups, or configuring them after creation.

Possible solutions
Minimum addition - in group list prompt, be able to swipe right on name to be prompted with option to delete.
Advanced - press and hold to be given options for specific bookmark group, such as rename, or apply all active filters.

Thoughts?

**Comment by K1rakishou** [comment]
There is the "Bookmark group settings" menu option in the three dot menu (Bookmarks screen) which opens a screen with all the bookmark groups, where you can move them around and do other stuff.
