### ISSUE TITLE
Fix posting on newer Lynxchan sites

### ISSUE THREAD

**Issue by SomeGuy719** [K1rakishou/Kuroba-Experimental#789]
I've done what poking around I can and it seems as though the issue is related to the captcha, somewhere in https://github.com/K1rakishou/Kuroba-Experimental/blob/develop/Kuroba/app/src/main/java/com/github/k1rakishou/chan/ui/captcha/lynxchan/LynxchanCaptchaLayoutViewModel.kt in extractLynxchanHeaders. On older lynxchan sites (or at least endchan as that seems to be the only lynxchan site that can be posted to at the moment) the captcha is available directly at (for example) https://endchan.net/captcha.js. On sites running newer versions, the captcha is still at /captcha.js but redirects to /.global/captchas/[captcha ID]. An example of a newer site is yeshoney.xyz (https://yeshoney.xyz/captcha.js). I wish I could offer more help but I'm just really not familiar with Android development. But I would like to see a Clover fork support such sites, so hopefully it doesn't take too much to get posting working.

**Comment by K1rakishou** [comment]
Are you trying to add support for a new site? Because I just checked endchan's and kohlchan's captchas and they both work.

**Comment by SomeGuy719** [comment]
Yes (a couple anyway). Basically I copied endchan's site file and modified it, added it to the site registry. Viewing works just fine but the captcha always fails with "failed to extract headers". I thought I read in an issue or commit or something here that kohlchan was currently read only, but I could very well be wrong on that. I suppose I could try to start with kohlchan's file and see if that makes a difference.

**Comment by SomeGuy719** [comment]
Just tried that (using kohlchan's files as a base) and same result. "Failed to extract captcha info from headers".

**Comment by K1rakishou** [comment]
Can you make a PR with all your changes so I can test it locally and add support to that new captcha?

**Comment by SomeGuy719** [comment]
Sorry about the delay, made the PR.

**Comment by K1rakishou** [comment]
No need to rush I will only be able to check it out tomorrow.

**Comment by K1rakishou** [comment]
Well I tried to fix it but now there is something wrong with "blockBypass" (I'm using a VPN) and when trying to reply it just returns 404 html page. I pushed my changed into that branch.

**Comment by SomeGuy719** [comment]
Looking at the javascript on the block bypass page, it looks like endchan posts the data to /.api/renewBypass while yes honey posts to /renewBypass.js?json=1 . Perhaps this is the issue? 

Also there seems to be other issues with the regular captcha. Through the browser I don't need a block bypass to post on the site, but through the app it always detects that a block bypass is needed. The captcha loads correctly here, but solving the block bypass results in an endless loop of block passes. Could it be falsely detecting that a bypass is needed?

I should add that for me, after solving the block bypass in the app, it reports success and that I now need to complete the regular captcha. But instead of the regular captcha it just loads the block bypass again. This is what I meant by the endless loop of block bypasses.

Should also add that all this is new behavior with the adjustments to the captcha.

**Comment by K1rakishou** [comment]
Yes, I had the same issues. You can also post without attempting to solve the captcha (long tap the "send reply" button) and then it will just return 404 html page. In the browser I managed to post without having to solve the captcha at all.

**Comment by SomeGuy719** [comment]
Alright, I now see that the same overrides necessary for Kohlchan are also necessary here. I've applied these changes.

Next thing I tested is setting needBlockBypass to always be false in LynxchanCaptchaLayoutViewModel. Doing so lets the regular captcha load and posting seems to function. So it does seem that the issue is the block bypass being falsely needed.

As a side note, how does one delete their own posts in KurobaEx? Or is that just not available in the app yet for Lynxchan sites?

**Comment by SomeGuy719** [comment]
So looking more at LynxchanCaptchaLayoutViewModel line 249, I see that it looks for the status of the "valid" entry in the returned json. However, as far as I can tell this entry is only relevant when the user is actually blocked from posting. I'm guessing that it should (at least initially) look and see if the "status" entry is "ok" and go by that instead. Looking at the "valid" entry if the "status" entry is "bypassable".

https://gitgud.io/LynxChan/LynxChan/-/blob/master/doc/Form.txt

So I've added a check for an ok status that will return false if so. Things seem to be working.

**Comment by K1rakishou** [comment]
>Or is that just not available in the app yet for Lynxchan sites?

I never implemented that. Feel free to do that.

Yeah, seems to work now. I can merge it if you are not going to add anything else.

**Comment by SomeGuy719** [comment]
You can go ahead and merge, I think this issue is resolved. And thanks for taking a look at the captcha.

**Comment by canjbfeeltheesemuffins** [comment]
@K1rakishou The URL `yeshoney.xyz` will be gone in a few months. The new one is `lynx.farted.net` listed on the status page.

**Comment by canjbfeeltheesemuffins** [comment]
@K1rakishou 

The URL `yeshoney.xyz` will be gone in a few months. The new one is `lynx.farted.net` from the status page.

**Comment by canjbfeeltheesemuffins** [comment]
@SomeGuy719 kolhchan is new lynxchan + mods, endchan is old lynxchan + mods
