### ISSUE TITLE
VERY MINOR: Can't swipe post window away from right side in catalog

### ISSUE THREAD

**Issue by reportthings** [K1rakishou/Kuroba-Experimental#795]
This only applies to creating a new thread in the catalog.  Replying to existing threads does not have this problem.

Short video displaying it.  Very minor and probably doesn't even really need a fix

https://user-images.githubusercontent.com/85461551/185733557-91be3067-f071-47ab-bf70-3ae8da517bf6.mp4

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/eb6e9a9753bf554a61675dd10ff2fbfbe9c6a6e9
