### ISSUE TITLE
Can't use external archives

### ISSUE THREAD

**Issue by HNKMaster** [K1rakishou/Kuroba-Experimental#801]
I'm using the current version of Kuroba-EX, which is working really well, but I can't use the external archives. I get the error message, but I can't find the option to enable them. I don't know if I'm missing something or is a bug.

**Comment by K1rakishou** [comment]
You need to enable them first. Just like any other site.

![image](https://user-images.githubusercontent.com/10332458/187035283-3daab101-3967-4572-a3c4-4191a126968b.png)
