### ISSUE TITLE
Archived.moe returns 403

### ISSUE THREAD

**Issue by SleepyZzed** [K1rakishou/Kuroba-Experimental#802]
When trying to view images on any archived.moe thread it says image cannot be downloaded error 403 any fixes?

**Comment by K1rakishou** [comment]
The same happens in the browser. They use incorrect urls, I think? At least for images stored on desuarchive.

![image](https://user-images.githubusercontent.com/10332458/187075396-36c225c9-8533-4c98-bed0-8025d212201d.png)

**Comment by SleepyZzed** [comment]
> The same happens in the browser. They use incorrect urls, I think? At least for images stored on desuarchive.
> 
> ![image](https://user-images.githubusercontent.com/10332458/187075396-36c225c9-8533-4c98-bed0-8025d212201d.png)

Wonder If they'll fix it so it can be accessed 😓

**Comment by K1rakishou** [comment]
I guess it's better to ask them. I could probably fix it on the client side but I would prefer it if they fixed it. And I mean it doesn't work in the browser so they kinda have no other way but to fix it.
