### ISSUE TITLE
Reply field problem ?

### ISSUE THREAD

**Issue by baraa272** [K1rakishou/Kuroba-Experimental#805]
![Screenshot_20220829-162208_KurobaEx.png](https://user-images.githubusercontent.com/32843097/187211484-fc1704dd-766e-4bfb-b969-84ad21add79b.png)

When you press the enter button ? Then this 
![Screenshot_20220829-162234_KurobaEx.png](https://user-images.githubusercontent.com/32843097/187211566-cde38b56-c479-4a49-8aea-480a7fcce09f.png)

In first image you see weird enter key ? But when you press it at end of Line you get normal enter (writing) but cursor disappears as reply form got unselected

**Comment by K1rakishou** [comment]
I don't get it. Also what version?

**Comment by K1rakishou** [comment]
Ahh, I see.

**Comment by K1rakishou** [comment]
>After updating the app from 1-2 versions ago to fix the captcha cloudflare issue I'm now missing a line break key on both GBoard and Hacker's Keyboard, it shows a "Next" key that changes focus away from the text box. The input box also seems to display multi line text when pasted as a single line, though the line breaks are there once posted
(btw line breaks and the enter button are working fine in this report input box)

Seems to be related.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/db2a0d47be91a8570e8da29bdc8be9674777c003
