### ISSUE TITLE
[Request] media player lock

### ISSUE THREAD

**Issue by KnowledgeEngineer** [K1rakishou/Kuroba-Experimental#806]
Pretty simple, the media player needs a lock feature, so that no inputs disturb playing media.

**Comment by K1rakishou** [comment]
Can't use just turn the screen off? That should do what you want, no?

**Comment by KnowledgeEngineer** [comment]
Turning the screen off stops the media playing.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by K1rakishou** [comment]
Turn off the "Pause players when app goes into background" setting which can be found in the media viewer settings (three dot menu).

**Comment by KnowledgeEngineer** [comment]
Can't believe I missed that option. Thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
