### ISSUE TITLE
Pressing anywhere while typing a comment highlights words

### ISSUE THREAD

**Issue by reportthings** [K1rakishou/Kuroba-Experimental#809]
Since last update, when tapping the screen to edit a typo or add a word, it automatically acts as if I am long pressing to highlight, rather than just moving the blinking cursor to where I pressed.  

https://user-images.githubusercontent.com/85461551/188300583-74ae837b-f559-4752-86ab-9c75123d1998.mp4

As always thanks for the awesome app

Here is a gfycat link.  I have no idea why GitHub won't play videos I upload. https://gfycat.com/offbeatsoulfulinchworm

**Comment by jdevstatic** [comment]
seems it's corrupted even if I open that directly on another tab, it should play, but it's not playing

![image](https://user-images.githubusercontent.com/47092464/188314687-3488a691-4cbf-4e34-8da9-e827e41665c0.png)

**Comment by K1rakishou** [comment]
Weird.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/1ec92e68a21ffc70f65265273621098cded01aef

**Comment by reportthings** [comment]
Just updating: Whatever you did in the new update for cloudflare bypass resolved this issue.  Have a good day

**Comment by K1rakishou** [comment]
@reportthings I reverted that change. Now it will be crashing instead ;^) (for some people)
