### ISSUE TITLE
Add new board page makes the "add" button hyphenated 

### ISSUE THREAD

**Issue by Kmad666** [K1rakishou/Kuroba-Experimental#813]
![SNOW_20220909_191230_727~2](https://user-images.githubusercontent.com/112305558/189457482-28c0c475-7402-49f8-936c-13e5fbd18eb8.jpg)

Something is wrong with the spacing of the other 2 buttons which is causing the add button to look odd.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/9457cb8a00c70bf729e2796e1f0a86614436c5f3
