### ISSUE TITLE
Captcha is asking for Cloudflare 5 seconds authentication over and over

### ISSUE THREAD

**Issue by hafizhmakmur** [K1rakishou/Kuroba-Experimental#815]
Everytime I try to post and solve the captcha,  Cloudflare will appear and ask to wait for 5 seconds. After that im asked to reload and then Cloudflare appear again. It almost never stops.

**Comment by K1rakishou** [comment]
Try clearing cookies? Also make sure you are using the latest version of WebView. https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en&gl=US
