### ISSUE TITLE
Duplicate resolution skip behaivour.

### ISSUE THREAD

**Issue by sansarselim** [K1rakishou/Kuroba-Experimental#816]
current behaivour:

```
if same_name_exist:
    skip
else:
    download
```

desired behaivour:

```
if same_name_exist:
    if same_size & same_checksum:
        skip
    else:
        download_with_another_name
else:
    if same_size_exist & same_checksum:
        skip
    else:
        download;
```

**Comment by K1rakishou** [comment]
In this part 

```
else:
    if same_size_exist & same_checksum:
        skip
```

do you mean to check every single file in the directory whether any of them has the same size and checksum? If yes, then it's not possible with SAF. I mean it is technically possible but each image download will be exponentially slower the more files you have in that directory.


This

```
if same_name_exist:
    if same_size & same_checksum:
        skip
```

however, is probably a good idea.

**Comment by sansarselim** [comment]
if you calculate checksums after the sizes match it would be fast. Since the checksums of files with different sizes can't be the same. Still it has to loop for every file in the directory but comparing the names and the sizes are light operations and the propabilty to have multiple files with the exact same size is low.

Like this;

```
if same_name_exist:
    if same_size:
        if same_checksum:
            skip
    else:
        download_with_another_name
else:
    if same_size_exist:
        if same_checksum:
            skip
    else:
        download;
```

**Comment by K1rakishou** [comment]
>Still it has to loop for every file in the directory but comparing the names and the sizes are light operations

It's not with SAF. To get a filename or a file size SAF sends an IPC request to another application with SQL QUERY. And when doing that to a whole directory multiply that by the amount of files in that directory.

It's literally 50+ times slower than the old API so unfortunately it's just not possible anymore to do advanced stuff like you what are suggesting on Android (without the super permission which only some special apps are allowed to use).

**Comment by K1rakishou** [comment]
Okay, so I implemented file size + md5 checksum checks so now it won't ask you anything if those match.
https://github.com/K1rakishou/Kuroba-Experimental/commit/36f8a3362829f24b5a40399f875666629df16f95
