### ISSUE TITLE
auto post chan without showing captcha solver

### ISSUE THREAD

**Issue by samlux04** [K1rakishou/Kuroba-Experimental#817]
Automatically post without showing captcha window when using captcha solver? And only show the window after the first attempt fail? Or with option to limit captcha solver attempt before it show the dialog?
Thanks.

**Comment by K1rakishou** [comment]
Nah, I believe the user should be aware of what's going on.

**Comment by samlux04** [comment]
> Nah, I believe the user should be aware of what's going on.

I believe most people who searched for chan app isn't a newfag either. By its nature it's not advertised in the open web. Not even in the playstore. They should know what's going on already.

Just make an option with disabled as default.

**Comment by K1rakishou** [comment]
I mean even forgetting about that, if I implement it, it still won't last long since the devs most likely already working on the new captcha because. The current one clearly doesn't do it's job anymore since the solver is used by actual spamming scripts.
