### ISSUE TITLE
Can't post on 2ch.hk

### ISSUE THREAD

**Issue by wholivesunderthesea** [K1rakishou/Kuroba-Experimental#819]
It gives 404 popup which is supposed to cloudfare check and after press cancel because it doesn't dissapperon its own it shows me another error 
![Screenshot_20220917-223449_KurobaEx-beta](https://user-images.githubusercontent.com/110178324/190873738-1e0c0519-cf08-44e0-9a18-e6ca03223ead.png)

![Screenshot_20220917-223029_KurobaEx-beta](https://user-images.githubusercontent.com/110178324/190873663-9a5dd1ba-316e-4b75-83a3-29a8ba3bd8c0.png)

**Comment by K1rakishou** [comment]
What happens if you open this link https://2ch.hk/challenge in an incognito mode in your browser (on your phone)? It works for me, it starts the CloudFlare check. It also works for me in the app for both .hk and .life domains.

**Comment by K1rakishou** [comment]
Also, try clearing the cookies.

**Comment by wholivesunderthesea** [comment]
https://2ch.hk/challenge gives me the same cloudfare 404, but I still can post using my browser. 

https://2ch.life/challenge seems passes the cloudfare check and redirects me to 2ch 404 page.
 
So I changed domain from .hk to .life in the app and I can post now.
