### ISSUE TITLE
Can't post on the 4chan.org domain

### ISSUE THREAD

**Issue by starlite-jack** [K1rakishou/Kuroba-Experimental#820]
See this picture? 
![20220920_214759701](https://user-images.githubusercontent.com/90665508/191291499-a297e6a8-5e75-44d7-bc39-5fa4f9570866.jpeg)
For some reason, I can't post on the 4chan.org site. Even after I've updated my webview on my android, it still shows absolutely nothing. What do I do?

**Comment by K1rakishou** [comment]
Weird, what Android version is that?
