### ISSUE TITLE
Export multiple threads

### ISSUE THREAD

**Issue by overgeeked** [K1rakishou/Kuroba-Experimental#823]
Can we have an option to export multiple downloaded threads?

Currently you can only export one thread at a time. When you select a single thread, you can "Export" or "Delete", however, when you select multiple threads, the only option is to delete.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/c2bf42367126abe309fe39d731d48fbe8d224cbb
