### ISSUE TITLE
Asks for captia while authorized

### ISSUE THREAD

**Issue by kaizervonmaanen** [K1rakishou/Kuroba-Experimental#828]
Logged in with 4chan pass. It still require captia when posting.

**Comment by K1rakishou** [comment]
Longtap the "Send reply" button and check the "Post with passcode" option.

**Comment by kaizervonmaanen** [comment]
Ah, a hidden feature. Why isn't it changed by default when logged on with
pass? I cannot imagine that most people who log on with a password would
want to continue to do captia. Unless I miss something, I thought that was
the point of the pass.

**Comment by K1rakishou** [comment]
It should change to that, maybe it's a bug.

**Comment by K1rakishou** [comment]
Ok I added a helpful toast when you login/logout.
https://github.com/K1rakishou/Kuroba-Experimental/commit/60feea59c92dd3131a4366adce09c73c63d54fb4
