### ISSUE TITLE
Unable to post on 4chan.org domain

### ISSUE THREAD

**Issue by starlite-jack** [K1rakishou/Kuroba-Experimental#829]
I have already posted an issue about this
![chrome_screenshot_1666327276840](https://user-images.githubusercontent.com/90665508/197113731-b8c07681-6c9b-43fb-b8c0-5a7233d7761c.png)
https://github.com/K1rakishou/Kuroba-Experimental/issues/820
Basically to repeat what I've said in that post:
>For some reason, I can't post on the 4chan.org site. Even after I've updated my webview on my android, it still shows absolutely nothing. What do I do?

Also, sorry for being so late to respond to the issue, I forgot about replying it. 
Responding to K1rakishou's question:
>Weird, what Android version is that?

It's android 7. But now I have updated my android from android 7 to android 12 as seen on the picture below
![chrome_screenshot_1666332555646](https://user-images.githubusercontent.com/90665508/197124761-25efe30d-c41f-467c-9695-59c5b818f06f.png)
But it still shows the same thing when I tried to post on the 4chan.org domain
![Screenshot_20221021-113820](https://user-images.githubusercontent.com/90665508/197124859-7396e561-4a31-48e3-841f-d261e000bc10.png)
So what do I do now?

**Comment by starlite-jack** [comment]
hello?

**Comment by K1rakishou** [comment]
Unfortunately, I'm not really sure. This is probably the first time I'm seeing a problem like this one so this is most likely something device/OS/or software specific.

**Comment by starlite-jack** [comment]
@K1rakishou but I already have updated the webview...

**Comment by K1rakishou** [comment]
Well then maybe the problem is not in webview but in something different.
