### ISSUE TITLE
can't post on 4chan.org, stuck on cloudfare verification

### ISSUE THREAD

**Issue by starlite-jack** [K1rakishou/Kuroba-Experimental#830]
@K1rakishou please answer my question on why i'm always stuck on cloudfare verification every time i try to post on 4chan.org. to sum the post up:
>For some reason, I can't post on the 4chan.org site. Even after I've updated my webview on my android, it still shows absolutely nothing. What do I do?

![image](https://user-images.githubusercontent.com/90665508/197382710-421536fd-7c7b-4e5d-a290-93d79131764a.png)

so what's the solution here? 
this is the previous question that has remained unanswered: [https://github.com/K1rakishou/Kuroba-Experimental/issues/829#issue-1417805916](url)

**Comment by K1rakishou** [comment]
You don't need to create a new issue to ask a question. Just use this one https://github.com/K1rakishou/Kuroba-Experimental/issues/829
