### ISSUE TITLE
Lockscreen Notifications

### ISSUE THREAD

**Issue by seniorm0ment** [K1rakishou/Kuroba-Experimental#831]
I notice KurobaEx is my only app I have this issue with.
I do not get notifications on the lock screen. If I have a notification for say a duplicate that needs to be resolved while saving something, then I lock my phone, that shows up.

However, I get no thread reply notifications. They seem to come through when the screen is unlocked, or when I open the app I'll get an immediate notification.
But nothing on the lockscreen.

I have it set to hide sensitive info, so it shouldn't show board info or reply or anything on the lockscreen, but it should still show I have a notification from Kuroba, it doesn't. 
Not sure if it's a setting, or a bug.

Android 13, GrapheneOS, KurobaEx FDroid 1.3.21

**Comment by K1rakishou** [comment]
Logs are needed. Preferably full logs, see https://github.com/K1rakishou/Kuroba-Experimental/wiki/Getting-application-logs-or-crashlogs-on-beta-or-release-builds

**Comment by seniorm0ment** [comment]
Still relevant, have not had time to get logs sorry.
