### ISSUE TITLE
Add Vietnamese language

### ISSUE THREAD

**Issue by Kimphunh** [K1rakishou/Kuroba-Experimental#832]
[https://drive.google.com/file/d/14i-uj9aXMxOsFzE1cyRAfBuqOSuoLZQ9/view?usp=drivesdk](url)
I translated it into Vietnamese,Although there were no problems during the build process, it still crashed
Can you add it for me pls

**Comment by K1rakishou** [comment]
>Although there were no problems during the build process, it still crashed

That's probably because you translated something that shouldn't have been translated. Some special symbol or something like that. That's one of the reasons I don't want to add translations to this app.
