### ISSUE TITLE
why there's dancing skeleton on my phone?

### ISSUE THREAD

**Issue by samlux04** [K1rakishou/Kuroba-Experimental#835]
![Screenshot_20221030-210707_KurobaEx-beta](https://user-images.githubusercontent.com/85811479/198880167-171d3e3d-734f-4e6b-bdca-86b85b4869d3.png)

Why the fck there's a dancing skeleton on my phone? Is my phone cursed or it's something to do with dancing Israeli?
Picrel.

**Comment by G2G2G2G** [comment]
stfu and enjoy it

**Comment by samlux04** [comment]
> stfu and enjoy it

Here's (You)

**Comment by BinariGuy** [comment]
Newfag

**Comment by samlux04** [comment]
> Newfag

Stfu phaggot
