### ISSUE TITLE
global search is broken

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#836]
it does not work

**Comment by K1rakishou** [comment]
What site/board doesn't work?

**Comment by ghost** [comment]
@K1rakishou all of them

**Comment by K1rakishou** [comment]
Seems to work fine

![image](https://user-images.githubusercontent.com/10332458/200517119-7d732a09-63a6-4397-98a9-8613717b760c.png)

**Comment by ghost** [comment]
nvm it was an issue with cloudflare
