### ISSUE TITLE
Kuroba uses the tablet interface on foldable cover screen

### ISSUE THREAD

**Issue by starcraft66** [K1rakishou/Kuroba-Experimental#839]
I am using kuroba on the Samsung Z Fold 3 which is a folding phone with a small outer display and a large folding inner display.

Unlike other apps with tablet mode UIs like Discord who use the phone UI on the outer screen and the tablet UI on the inner one, Kuroba forces the tablet layout on the small cover display as well which makes it look silly and unusable.

![Screenshot_20221104_100617](https://user-images.githubusercontent.com/1858154/199995201-6b5b054e-6612-4d1b-a511-201d0db19786.jpg)

**Comment by K1rakishou** [comment]
By default it tries to determine when layout mode to use based on screen width. You can change the layout mode manually in the settings (Appearance).

**Comment by starcraft66** [comment]
I understand that the layout can be manually changed but this is not ergonomic on a folding device, different layouts should be used on the different displays. I'm not an android developer professionally but I did some research and it seems using an [adaptive layout](https://developer.android.com/guide/topics/large-screens/learn-about-foldables#responsive_adaptive_design) would fix this issue. Unsure of how hard this would be to implement but it would really make this app much more usable on foldables.

**Comment by K1rakishou** [comment]
Yeah, I know about that but unfortunately it won't be easy to implement in KurobaEx due to it not supporting configuration changes properly (it was like that since Clover). Most likely the whole UI will have to be rewritten to add the proper support. It's this much work.

However, It's actually supported and works in [KurobaExLite](https://github.com/K1rakishou/KurobaExLite).

**Comment by starcraft66** [comment]
> However, It's actually supported and works in [KurobaExLite](https://github.com/K1rakishou/KurobaExLite).

Thanks, I will give it a try. Is there any CI building apks somewhere or do I need to build it myself?

**Comment by K1rakishou** [comment]
The apks are in the "Releases" section.

**Comment by LostCursor** [comment]
> Yeah, I know about that but unfortunately it won't be easy to implement in KurobaEx due to it not supporting configuration changes properly (it was like that since Clover). Most likely the whole UI will have to be rewritten to add the proper support. It's this much work.
> 
> However, It's actually supported and works in [KurobaExLite](https://github.com/K1rakishou/KurobaExLite).

If it is not possible to implement this feature, then could you add a toggleable button to the bottom navigation bar that simply restarts the app/switches the layout? This way, we wouldn't have to manually close and reopen the app/go to the settings to switch layouts.

**Comment by K1rakishou** [comment]
@LostCursor 
I'm planning to get rid of bottom bar so I think the toggle will be needed.

**Comment by LostCursor** [comment]
> @LostCursor I'm planning to get rid of bottom bar so I think the toggle will be needed.

Oh... I really prefer the bottom navigation over a drawer. I hope you make it a choice.

**Comment by K1rakishou** [comment]
There are no plans to keep both navigation styles but I'm planning to rearrange where screens (global search/bookmarks/marked posts/etc) are displayed so it probably won't even be needed.
