### ISSUE TITLE
Keep bookmarks window on the left side in split mode

### ISSUE THREAD

**Issue by clutzygamers** [K1rakishou/Kuroba-Experimental#840]
When opening bookmarks in tablet/split mode, it would cover the entire screen. Would it be possible to keep the bookmarks window open on the left hand side just like the board? This way the user can view any new thread updates without having to open the bookmarks every time.

**Comment by K1rakishou** [comment]
Probably not in this project, however this is already possible in [KurobaExLite](https://github.com/K1rakishou/KurobaExLite).
You can even toggle it between history/bookmarks.

![image](https://user-images.githubusercontent.com/10332458/200155401-f60b9c3b-abf9-42ee-9497-339c2309c877.png)

**Comment by clutzygamers** [comment]
I see. Too bad it doesn't seem to work on my Fold 4, I guess the screen is too small to support it.

**Comment by K1rakishou** [comment]
>I guess the screen is too small to support it.

This bug is already fixed, just not released yet.

**Comment by clutzygamers** [comment]
> > I guess the screen is too small to support it.
> 
> This bug is already fixed, just not released yet.

Nice, I'll look forward to it.
