### ISSUE TITLE
vp9 webms don't play on first try

### ISSUE THREAD

**Issue by sirbanana2** [K1rakishou/Kuroba-Experimental#846]
only happens with vp9 webms, gives an error and you have to exit the webm player and enter again for the video to play. small but annoying bug

**Comment by K1rakishou** [comment]
Which player?

**Comment by sirbanana2** [comment]
> Which player?

the built in webm player, which one do you think i'm talking about? is there another one?

**Comment by K1rakishou** [comment]
Yes, these is also mpv. You can install it in the "Plugins" section of the app main settings.

**Comment by sirbanana2** [comment]
> Yes, these is also mpv. You can install it in the "Plugins" section of the app main settings.

interesting, i'll try playing vp9 webms with that one to see if they work.

**Comment by sirbanana2** [comment]
looks like mpv works as intended.

**Comment by sirbanana2** [comment]
looks like mpv works as intended.

**Comment by K1rakishou** [comment]
Yeah, mpv is better because it can fallback to software decoding automatically if hardware fails which happens a lot with webms (both VP8 and VP9).
