### ISSUE TITLE
Can't see /jp/ archived threads

### ISSUE THREAD

**Issue by darlopvil** [K1rakishou/Kuroba-Experimental#849]
Hi,

Well, this only happens with /jp/, other boards seem to work correctly so far.
The problem here is that I cannot see any old archived thread. Any archive site I've tried gives errors (warosu, wakarimasen, tokyo chronos, etc).

**Comment by darlopvil** [comment]
no comments?

**Comment by K1rakishou** [comment]
Haven't checked it yet. Probably all archives are dead. Do any of them work in the browser?

**Comment by darlopvil** [comment]
So it seems. I've made a short video of each archive (app view and browser version). It seems everything is dead.

Maybe there is another archive that works, but it isn't included in the app? 

https://user-images.githubusercontent.com/60988792/208152502-10d749fc-c4c1-4982-a8dd-974e5de0ed42.mp4
