### ISSUE TITLE
Request support for 8chan.moe

### ISSUE THREAD

**Issue by Dan-Quokka** [K1rakishou/Kuroba-Experimental#858]
I recently discovered the site 8chan.moe/8chan.se/8chan.cc (all the same site, .moe is the main one), it's quite active, definitely has potential, and since the structure is identical to 8kun i thought that maybe adding support for this site wouldn't be that hard.

here's the site in question: https://8chan.moe/

**Comment by K1rakishou** [comment]
There is already an issue for this site, see https://github.com/K1rakishou/Kuroba-Experimental/issues/847
