### ISSUE TITLE
Add support for using a mpv.conf

### ISSUE THREAD

**Issue by 1sad** [K1rakishou/Kuroba-Experimental#861]
some webms just give "decoder failed: OMX.MTK.VIDEO.DECODER.VP9"
mpv plugin sometimes doesnt work either, even with standalone version. vlc works though.
im guessing this isnt an app issue but a phone issue, though my phone is only couple years old model.
but i want to ask if its possible to switch from the mtk vp9 decoder to c2.android.vp9.decoder somehow? maybe that would work
just really annoying to deal with vp9 webms.

**Comment by K1rakishou** [comment]
I can't choose what hardware decoders are used in neither ExoPlayer nor in mpv. Mpv is supposed to switch to software decoding if it can't use the hardware decoders for whatever reason.

**Comment by 1sad** [comment]
damn.
even on the standalone mpv-android when i switch between sw and hw it still doesnt play those files. 

any possible chance to integrate dashchan webm libraries/plugin https://github.com/Mishiranu/Dashchan-Webm ? 
vp9 webms work in dashchan, but dashchan itself hasnt been updated in years so its not too nice to use compared to this...

**Comment by K1rakishou** [comment]
Probably a better idea is to report the bug to mpv devs? Then I could just update the libs and it would work.

**Comment by 1sad** [comment]
mpv-android? or just mpv
im not sure what information i provide 
also in kuroba light it gives me these errors, is it even mpv related at this point?
![image](https://user-images.githubusercontent.com/23120024/217362577-7a18710c-527a-4049-9460-140dd905313c.png)

**Comment by K1rakishou** [comment]
>mpv-android? or just mpv

Well, technically the issue is most likely in the mpv itself but since it doesn't work in mpv-android too then I guess you should report it to mpv-android repository. The dev of mpv-android also develops mpv. I just think that he should be aware of this issue.

>im not sure what information i provide

There is a template when you create a new issue. It says that you need to provide Android version and mpv version. I guess the logs will be useful as well but they are not mentioned in the template.

>also in kuroba light it gives me these errors, is it even mpv related at this point?

I mean mpv uses ffmpeg so yes.

**Comment by 1sad** [comment]
so i asked the mpv-android dev and turns out its a Mali GPU issue with 10-bit video
https://github.com/mpv-android/mpv-android/issues/198

"forcing dumb mode indirectly via `vf=format=yuv420p` or directly via `gpu-dumb-mode` makes it work" 

is there a way to get to mpv.conf in kurobaex? could you add a toggle somewhere for these options, or a way to edit mpv.conf please ? (probably the better option to be able to edit it)

**Comment by K1rakishou** [comment]
Yeah, I guess I could do that.

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/commit/a8cff0e9c539ba1900db4139baebe7eb5b9d58db
