### ISSUE TITLE
Global WebM size limit was raised to 4MB, app still gives warning for being larger than 3MB

### ISSUE THREAD

**Issue by bungholemaster** [K1rakishou/Kuroba-Experimental#862]
Extremely minor issue, you can still post WebMs up to 4MB but I figured it'd be worth mentioning to fix in whatever the next release is.

**Comment by K1rakishou** [comment]
Try updating the board list and then restarting the app.

**Comment by bungholemaster** [comment]
> Try updating the board list and then restarting the app.

Huh, that actually worked.
