### ISSUE TITLE
Suggestion: Capture post sections

### ISSUE THREAD

**Issue by darlopvil** [K1rakishou/Kuroba-Experimental#863]
Hello there, so i think this can be a good option within a thread menu. 

The idea is to be able to only capture some posts in a thread. Take this as an example:

![imagen](https://user-images.githubusercontent.com/60988792/217900707-03678628-ed18-4967-a11d-6e170903a2a7.png)

So you only want to save in your phone posts 4 and 6. Nowadays, you can't do it without making a screenshot. Even in this case, you'd have to crop the screenshot to the desire area and then, manually eliminate post 5 and finally, combine 4 and 6 as desired. This will be the result:
![imagen](https://user-images.githubusercontent.com/60988792/217901304-9ec41a65-b558-4a53-a89b-0ff629c9a37f.png)

I think this can be implemented as a quick option in the 3 points menu in the top right corner. Something called "Capture posts" or similar. By the way, this is an easy example. But please take in consideration another scenario, where you want to capture more posts in a whole thread.

I am sorry if this was previously mentioned here, but I think it can be a powerful addon in the app since this feature can be very powerful to take only what you want and save it for later consultations.

**Comment by K1rakishou** [comment]
Post screenshoting is actually already implemented in KurobaExLite. Dunno if I ever port it here, though.

**Comment by darlopvil** [comment]
KurobaExLite doesn't have archive support. Neither i can use the "share" option inside the thread to open it in Lite. Please, consider it. It's not mandatory, i know you have a ton of other issues to fix.
