### ISSUE TITLE
Captchas don't load anymore

### ISSUE THREAD

**Issue by mYnDstrEAm** [K1rakishou/Kuroba-Experimental#865]
KurobaEx used to work for a long time but since a few days ago the captchas don't load anymore: when I press refresh it's stuck at the "Checking your browser before accessing sys.4channel.org." "Please allow up to 5 seconds..." screen.

After a minute or so it displays a small popup with "If a browser check seems to get stuck then make sure your system's 'WebView' is updated to the LATEST version".

I already tried switching IPs, waiting a few days, deleting the Captcha cookie, trying the other Captcha provider (not supported anymore but still in the settings) and made sure both KurobaEx from FDroid (v1.3.22) and Android System WebView from PlayStore (v109.0.5414.117) are at the latest version.

I'm using the NetGuard firewall, there wasn't a connection request in its logs so I don't think that is the problem and I also didn't do anything inappropriate which may have caused an intentional ban via not providing captchas to my IP anymore.

Why did this happen and how to get the Captchas to display again?

**Comment by mYnDstrEAm** [comment]
Just found #864 and this seems to be a duplicate of that issue

**Comment by K1rakishou** [comment]
Already fixed and update is out.

**Comment by Gobz** [comment]
I'm on 1.3.23 and still experiencing this issue

**Comment by Noja87** [comment]
Having the same issue for a week. Today I downloaded the new update and it's still not fixed for me. Hangs on the captcha, asks to update my Webview. Wont let me post.

**Comment by Cmcmk11** [comment]
I have this same repeated issue with the latest fix. Tried alternative user-agents. Didn't work. So, stuck back at square 1.

**Comment by mYnDstrEAm** [comment]
> Already fixed and update is out.

What do you mean? There is no update in FDroid and the problem persists.

If it works with alternative user-agents, please explain where to change that setting and with what exactly.

**Comment by K1rakishou** [comment]
FDroid is updated whenever. I don't control it.

**Comment by mYnDstrEAm** [comment]
The update is out in FDroid but it still doesn't work. Exactly same problem as before.

**Comment by Engineer31301** [comment]
On the latest version (1.3.23). Tried the latest beta, too. Also tried webview beta and webview dev. 
Same issue. Impossible to post anything without a pass.
I know Hiro is paying you off. Remove this "bug" and stop trying to jew me into buying a pass.

**Comment by Engineer31301** [comment]
Heh heh. If you do some digging and get lucky you might find the developer's "fix" for this issue. I won't bother sharing it here because half the time it doesn't even work. It's just some nonsense so the dev can throw his hands up and say "I already fixed this!!" while he pockets Hiro's bribes. 
Have some integrity for God's sake.
