### ISSUE TITLE
So, i'm basically having this problem https://github.com/K1rakishou/Kuroba-Experimental/issues/446

### ISSUE THREAD

**Issue by Bravelittlesneed** [K1rakishou/Kuroba-Experimental#867]
https://github.com/K1rakishou/Kuroba-Experimental/issues/446
Using simple gallery pro

**Comment by 1sad** [comment]
did you try the new version of ex? it used not to work and just took me to default android file picker, but with new version it actually let's me pick simple gallery

also try long tap on the upload file button, it will have option of "show all file pickers" or something

**Comment by Bravelittlesneed** [comment]
Already fixed the problem 4 days ago.None of your ideas worked however.What did the job was uninstalling every possible file picker until Simple Gallery showed up.Sneed
