### ISSUE TITLE
Suggestion: Make a default user-agent 

### ISSUE THREAD

**Issue by aardvark0420** [K1rakishou/Kuroba-Experimental#868]
Why is the user made to input a custom user-agent with the new update (any random one will work it seems)? The user-agent should be set to a default one, for everyone in order to minimizie tracking/fingerprinting. Alternatively, couldnt the user-agent be a randomized string everytime, for everyone?

**Comment by 1sad** [comment]
it uses webview useragent by default, something just broke with it lately, look at #864 

just use KurobaEx/v1.2.3.4 its what a lot of people put by suggestion of dev

**Comment by K1rakishou** [comment]
I don't want to do that because it might stop working in the future and people will start complaining that it's broken and nothing works. Now they at least know what they should try doing when the same issue happens the next time.

**Comment by a84r7a3rga76fg** [comment]
> couldnt the user-agent be a randomized string everytime, for everyone?

It should. The app creates a new post password when you're on a new IP. Posting from a new IP should also create a new random useragent.
