### ISSUE TITLE
Captcha will not accept any solutions 

### ISSUE THREAD

**Issue by Cmcmk11** [K1rakishou/Kuroba-Experimental#871]
Got the captcha to load, using most recent release and new user-agent as suggested. Sliders are okay. Position the text, fill out the form.

No matter what is entered: "error posting authentication required".

This just repeats.

**Comment by K1rakishou** [comment]
Try different user-agents, try deleting cookies, changing IP address.

**Comment by Cmcmk11** [comment]
Issue resolved itself.
