### ISSUE TITLE
Cloudflare Toast cutoff

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#873]
![Screenshot_20230217-085042_KurobaEx-fdroid](https://user-images.githubusercontent.com/96967473/219529707-d0d4235d-026a-46af-bb56-7667df9513b1.png)

**Comment by Tetrahybrid** [comment]
Same here.

Started a couple of weeks ago. Only happens in the app but not in the browser.

It never counts down, always staying at 5 seconds

![IMG_20230218_232758.jpg](https://user-images.githubusercontent.com/37155087/219902270-9c2f1525-7eb1-4424-ac40-1faf3eb9c16b.jpg)

![IMG_20230218_232627.jpg](https://user-images.githubusercontent.com/37155087/219902272-48e83a69-0ba8-4128-a642-4073fb8f8b6a.jpg)

![IMG_20230218_232929.jpg](https://user-images.githubusercontent.com/37155087/219902271-12592a7f-dfa1-46b9-b2ec-8178cf435098.jpg)

**Comment by K1rakishou** [comment]
I think they made it 2 lines long max in Android 12 or 13. So I can't really do anything here.

**Comment by moldyharriet** [comment]
Any thoughts on how to pass the cloudflare check, regardless of the android 12 toast cutoff? I can't pass the check regardless of what I try.

**Comment by K1rakishou** [comment]
@moldyharriet 
Did you try doing this - https://github.com/K1rakishou/Kuroba-Experimental/issues/864#issuecomment-1429152975 ?

**Comment by Tetrahybrid** [comment]
> @moldyharriet 
> Did you try doing this - https://github.com/K1rakishou/Kuroba-Experimental/issues/864#issuecomment-1429152975 ?

I added "KurobaEx/v1.2.3.4" to the user-agent and it did work for me.

**Comment by moldyharriet** [comment]
@K1rakishou 

That worked, thanks!

**Comment by cgw158** [comment]
@K1rakishou 
Thank you. This worked.

**Comment by nicholaicascio** [comment]
> @moldyharriet Did you try doing this - [#864 (comment)](https://github.com/K1rakishou/Kuroba-Experimental/issues/864#issuecomment-1429152975) ?

Doesn't work for me.
