### ISSUE TITLE
Add colour-theme support for the app icon (Android 13)

### ISSUE THREAD

**Issue by kotodorii** [K1rakishou/Kuroba-Experimental#875]
[https://files.catbox.moe/mvu86j.png](Example)

**Comment by HotarunIchijou** [comment]
Right now you can download F-Droid version, download icon pack named "Pix Material You Light/Dark" and apply icon from this pack

**Comment by K1rakishou** [comment]
Implemented in https://github.com/K1rakishou/Kuroba-Experimental/pull/935
