### ISSUE TITLE
Respect metered (Wi-fi) networks

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#880]
Currently, loading media settings set "on Wi-fi" will still loads from metered networks that was set manually. Wi-Fi SSIDs can be marked as "metered" so apps knows not to suck data from such SSIDs (e.g. using portable hotspot)

Expected: Metered (wi-fi, or any other networks that can manually set as metered) is treated like mobile data

**Comment by ghost** [comment]
Instead of if [`(networkType == ChanSettings.NetworkContentAutoLoadMode.WIFI) `](https://github.com/K1rakishou/Kuroba-Experimental/blob/1f89e3556910b3b7f07a32b8917b2f6576586b4e/Kuroba/app/src/main/java/com/github/k1rakishou/chan/utils/AppModuleAndroidUtils.java#L380)
can you add this one? https://developer.android.com/reference/android/net/ConnectivityManager#isActiveNetworkMetered()

**Comment by K1rakishou** [comment]
You probably meant it like this:

![image](https://github.com/K1rakishou/Kuroba-Experimental/assets/10332458/5ba7af7e-0733-4ade-8e39-547f185cfbee)

If the setting is set to only load media/threads on unmetered connections (was called WiFi previously) then we check if the current network is unmetered or not.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/c6f213765a9684f9b83d9619e82ccd17205f7dbf
