### ISSUE TITLE
Stucks at Cloudflare check

### ISSUE THREAD

**Issue by Odysch** [K1rakishou/Kuroba-Experimental#881]
I cannot pass through Cloudflare check despite Custom User Agent
Edit: Now it does work. After waiting about a minute the process succeeded. Tried numeroud times, worked every time.
Edit2: Now works normally. Then it was a Cloudflare issue.

**Comment by reportthings** [comment]
Edit: Nevermind it's working but takes about 15 seconds to pass cloudflare checks now

**Comment by kulapik** [comment]
It's not working for me either, I have the custom user agent set

**Comment by kaedechi** [comment]
cant pass cloudflare check with or without custom useragent

**Comment by SneedFormerlyChuck** [comment]
Can't pass cloudflare check, setting custom useragent doesn't fix it.

**Comment by Shigbeard** [comment]
Ditto the above, using latest release of korubaex and latest Android webview on Galaxy Z Fold 3.

**Comment by nambona890** [comment]
For a bit, disabling "Allow OkHttp to use HTTP/2 protocol" was working, but now nothing works. No matter the user agent or settings.

**Comment by GyaruFan** [comment]
Still not working, others apps also have this issue.

**Comment by GTFishcake** [comment]
Bro what are they doing with 4chan.  💀💀💀

**Comment by SneedFormerlyChuck** [comment]
> Bro what are they doing with 4chan. 💀💀💀

Nothing, it's just cloudflare being shit as usual
