### ISSUE TITLE
How to I restore downloaded threads?

### ISSUE THREAD

**Issue by DungeonManager3051** [K1rakishou/Kuroba-Experimental#882]
It seems that the app config was reset and I had to add needed boards like for the first run of the program. And all of the downloaded threads aren't visible in the local thread archive but the 20gb of files are still there. Is there any way to add them back somehow?

**Comment by K1rakishou** [comment]
You didn't make an app backup? I think it's impossible right now to restore them since there is some information about the stored in the database and with app reset it's deleted.

**Comment by DungeonManager3051** [comment]
I only had a backup that was created in November. Is there any way of enabling auto backup (like once in a month)???

**Comment by K1rakishou** [comment]
No that's not supported.
