### ISSUE TITLE
[Feature] Suggestions for new guesture controls

### ISSUE THREAD

**Issue by bagajohny** [K1rakishou/Kuroba-Experimental#883]
I find following gesture controls to be more intuitive. I request you to implement them in the app if you agree.

1. Swipe RIGHT anywhere to dismiss current page(even applies in full media view)
2. Swipe LEFT to see reply comments or more options
3. Swipe UP or DOWN to navigate through images
4. Long PRESS on image to download file
5. Long PRESS again to undo download(or delete downloaded file)

I found these controls on another 4chan reader app named **ReadChan**

Link for reference: https://play.google.com/store/apps/details?id=com.deezus.pchan&hl=en_US&gl=US

**Comment by ghost** [comment]
yes please! it is tiring to swipe horizontally
