### ISSUE TITLE
Layout does not automatically change on Galaxy Fold 4

### ISSUE THREAD

**Issue by LostCursor** [K1rakishou/Kuroba-Experimental#888]
Layout is set to Auto in the settings, but does not automatically change when the Fold 4 is folded or unfolded. A restart of the app is necessary each time.

**Comment by K1rakishou** [comment]
Can't fix this, unfortunatelly, see https://github.com/K1rakishou/Kuroba-Experimental/issues/839#issuecomment-1303960301

**Comment by LostCursor** [comment]
> Can't fix this, unfortunatelly, see [#839 (comment)](https://github.com/K1rakishou/Kuroba-Experimental/issues/839#issuecomment-1303960301)

Dammit, thanks anyways. I do need the features of full KurobaEx so I won't be switching to KurobaExLite.
