### ISSUE TITLE
Publish Kuroba Experimental to google play

### ISSUE THREAD

**Issue by soredake** [K1rakishou/Kuroba-Experimental#889]
It would be nice if app is available in google play.

**Comment by K1rakishou** [comment]
It will be banned there like any other image board app.

**Comment by soredake** [comment]
Can't agree with "any", that's what i found with a quick search:
https://play.google.com/store/apps/details?id=one.phobos.omnichan
https://play.google.com/store/apps/details?id=one.phobos.omnichan.pro
https://play.google.com/store/apps/details?id=adriandp.beechan
https://play.google.com/store/apps/details?id=com.lucasgoudin.mobichan
https://play.google.com/store/apps/details?id=com.zchandev.zchanapp
https://play.google.com/store/apps/details?id=com.deezus.pchan

**Comment by K1rakishou** [comment]
That's just because nobody reported them yet.

**Comment by soredake** [comment]
Omnichan exists in google play since 2017, mobichan/Read Chan since 2021, ichan since 2020, after several years someone must been reported them already, and they are still here.

**Comment by K1rakishou** [comment]
Yeah, and there were lots of other clients that got the short stick. It's a gamble and I don't want to take a part in it.
