### ISSUE TITLE
How to use 4chan pass? 

### ISSUE THREAD

**Issue by GyllenByte** [K1rakishou/Kuroba-Experimental#890]
Sorry if this is a dumb question, but I have a premium pass to bypass captchas entirely. I wasn't able to find a setting to use my premium auth in KurobaEx. Is there support for this?

**Comment by ErraticFox** [comment]
~~I've also come to look for this feature as well. Kind of odd how they'll add support for a captcha solver that you have to pay for but not a method to use the legitimate way to bypass the captcha.~~

Edit: @sh00ter999 I have found it. If you go into Sites > 4chan > Login
