### ISSUE TITLE
"Failed to download image" error message

### ISSUE THREAD

**Issue by ZenOrion** [K1rakishou/Kuroba-Experimental#894]
Recently it seems that whenever I try to view random images, I'll randomly get the error message:

Failed to download image (reason: HttpCodeException statusCode = 416)

And the image will fail to load. I can sometimes get them to load properly if I close Kuroba and reopen it and go back to the image, but its honestly just random if it works or not when I do.

![Screenshot_20230526-014850](https://github.com/K1rakishou/Kuroba-Experimental/assets/79720845/fd22a220-3586-4f4d-b372-725419267904)

**Comment by tidux** [comment]
I can confirm the same issue.

**Comment by K1rakishou** [comment]
Try changing "Concurrent downloading chunk count" or whatever it's called to 1.

**Comment by ZenOrion** [comment]
I've only recently been able to check if changing the chunk count fixed things and it seems like it has. Haven't had any problems so far, so thanks. I'll close this for now, hopefully that's all it was.

**Comment by cinnyamon** [comment]
> I've only recently been able to check if changing the chunk count fixed things and it seems like it has. Haven't had any problems so far, so thanks. I'll close this for now, hopefully that's all it was.

I'm sorry to ask this but where exactly is this option located? Tried to search and even downgraded to a version from February. Please tell.

**Comment by ZenOrion** [comment]
> > I've only recently been able to check if changing the chunk count fixed things and it seems like it has. Haven't had any problems so far, so thanks. I'll close this for now, hopefully that's all it was.
> 
> I'm sorry to ask this but where exactly is this option located? Tried to search and even downgraded to a version from February. Please tell.

Should be under Settings > Sites > 4chan (or whatever site you use I guess, click the cog button) > Concurrent chunk file downloading, and change it to 1
