### ISSUE TITLE
Hash differs from server

### ISSUE THREAD

**Issue by Kpthoux** [K1rakishou/Kuroba-Experimental#895]
Shows "hash differs from the one we got from the server....use force reload". It doesn't fix anything. Anyone know a fix?
![IMG_20230528_022917](https://github.com/K1rakishou/Kuroba-Experimental/assets/134815797/9dc32fed-59db-4ae7-8927-e41fab687d56)

**Comment by K1rakishou** [comment]
Hmm, this doesn't look like KurobaEx.
