### ISSUE TITLE
Images will not load

### ISSUE THREAD

**Issue by bungholemaster** [K1rakishou/Kuroba-Experimental#897]
![Screenshot_20230530_003250](https://github.com/K1rakishou/Kuroba-Experimental/assets/16147700/21be2d04-f317-47d7-93b5-455bc1c07c18)

Seemingly random images will not load, with this unreadable error popping up when you open them.

Opening the images in the browser they load fine so it shouldn't be a 4chan problem.

**Comment by K1rakishou** [comment]
Sites -> 4chan -> concurrent chunked downloading -> set to 1

**Comment by bungholemaster** [comment]
> Sites -> 4chan -> concurrent chunked downloading -> set to 1

This seemed to fix it, thanks.

**Comment by OkyDooky** [comment]
I've been having this a lot recently, as well. It didn't happen in the past. Did 4Chan change something on their end, possibly?
