### ISSUE TITLE
Cannot pass CloudFlare check even with custom user agent

### ISSUE THREAD

**Issue by bungholemaster** [K1rakishou/Kuroba-Experimental#908]
It used to work before even if it took a long time, I don't know what changed.

Even with a custom user agent set it just hangs on the "Checking your browser" popup indefinitely until it times out.

I have tried clearing the app cache and manually clearing each cookie and it still occurs.

**Comment by Gamma-Velorum** [comment]
Having the same problem. My custom user agent is set to KurobaEx/v1.2.3.4

**Comment by K1rakishou** [comment]
People say that removing it helps.

**Comment by Gamma-Velorum** [comment]
> People say that removing it helps.

Yep it just resolved it for me. Thanks.

**Comment by legaedon** [comment]
> People say that removing it helps.

How do you do that
