### ISSUE TITLE
Cannot post with passcode after ban warning

### ISSUE THREAD

**Issue by Paibilica** [K1rakishou/Kuroba-Experimental#909]
I am trying to post with a passcode and was warned on a board, now I get the "you are banned" post that leads me to the 4chan website to do the Captcha which doesn't clear that message and tells me "you are not currently banned." attempted to clear cache which did not solve the issue. Posting without the passcode is unaffected

**Comment by K1rakishou** [comment]
Should be (hopefully) fixed by https://github.com/K1rakishou/Kuroba-Experimental/commit/d61c96d883a5af8f1649c46807f25f723ece9304
