### ISSUE TITLE
Can't control notifications or permissions 

### ISSUE THREAD

**Issue by XPEH69** [K1rakishou/Kuroba-Experimental#916]
![Screenshot_2023-08-05-23-19-26-51_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/K1rakishou/Kuroba-Experimental/assets/125198400/5bd19d74-6fc5-44a5-9961-e2b234d29039)
After updating the app to the latest release, I noticed I couldn't add a pic from local storage. It said "permissions not granted". Going to my app management screen, I saw that manage notifications was greyed out for KurobaEx,and that the app didn't request any permissions so I couldn't change anything. Wiping the app settings and installing  older versions didn't change anything

**Comment by K1rakishou** [comment]
Oh I think I need the new notifications permission on API 33.

**Comment by K1rakishou** [comment]
Should be fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/7994cdf659b62b950f1424adf148d92418ca6629

**Comment by K1rakishou** [comment]
Update is out.

**Comment by XPEH69** [comment]
> Update is out.

So notifications work now, but it doesn't ask for permission to access the internal storage, and I can't manually allow it in the app management settings. Trying to attach a picture, I get this "Permission was not granted" error
![Screenshot_2023-08-06-05-19-35-82_601aace0ccf7d5780a960a2292e133ad](https://github.com/K1rakishou/Kuroba-Experimental/assets/125198400/2b550c09-8fab-41b2-abb5-f2460844864b)

**Comment by K1rakishou** [comment]
Weird, did they add a new permission for file pickers or something like that.

**Comment by XPEH69** [comment]
No clue, but doesn't it normally ask for permission to access internal storage? My app management page for KurobaEx says no permissions denied, and it never asked for permission to access internal storage
![Screenshot_2023-08-06-06-12-01-11_ab1359306de43320f9557c797b1c4be5](https://github.com/K1rakishou/Kuroba-Experimental/assets/125198400/35e8099c-31fb-422d-9ea6-f6f3b428e58d)

**Comment by tobia** [comment]
Same here. Trying to attach a file gives the "Permission was not granted" error, but it never asked me for permission to use the file picker (as other apps do) and I can't manually add the permission from the app info screen. I'm on Android 13.
