### ISSUE TITLE
Can't upload image in the latest KurobaEx because permission to internal storage can't be granted  

### ISSUE THREAD

**Issue by XPEH69** [K1rakishou/Kuroba-Experimental#917]
![Screenshot_2023-08-06-05-19-35-82_601aace0ccf7d5780a960a2292e133ad](https://github.com/K1rakishou/Kuroba-Experimental/assets/125198400/7042e763-9603-48cb-8736-0a4094ebdb74)
![Screenshot_2023-08-06-06-12-01-11_ab1359306de43320f9557c797b1c4be5](https://github.com/K1rakishou/Kuroba-Experimental/assets/125198400/d0908c7b-83c2-4ff9-80d7-ef022ed97cd0)
KurobaEx doesn't ask for permission to access internal storage like it used to, and it can't be granted manually in app management. Posting images from the built-in yandex search works, but I can't select anything from internal storage.

**Comment by XPEH69** [comment]
So I went back to version 1.3.23, pressed the + to attach a file, and a popup asked me if I want to allow KurobaEx to access internal storage. I pressed allow, and I was able to attach a picture/video. App management showed that photo/video and internal storage permissions were allowed. I updated to 1.3.25 within the KurobaEx settings page, and suddenly I'm no longer able to attach files as it says "Permission was not granted"
Lo and behold, I check my app management again with v1.3.25, and it only has notifications allowed with no other permissions denied

**Comment by AHMKHA97** [comment]
> So I went back to version 1.3.23, pressed the + to attach a file, and a popup asked me if I want to allow KurobaEx to access internal storage. I pressed allow, and I was able to attach a picture/video. App management showed that photo/video and internal storage permissions were allowed. I updated to 1.3.25 within the KurobaEx settings page, and suddenly I'm no longer able to attach files as it says "Permission was not granted" Lo and behold, I check my app management again with v1.3.25, and it only has notifications allowed with no other permissions denied

I have this exact same issue.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/a6c36b26bfee8ef32d13ddab750c9e2d3357c598
