### ISSUE TITLE
theme not working. its crashing in F-droid version 

### ISSUE THREAD

**Issue by aicynide** [K1rakishou/Kuroba-Experimental#926]

**Comment by tobia** [comment]
Can confirm. The MORE THEMES button makes the app crash.

I get this behaviour with 1.3.24, 1.3.25, and 1.3.26, both GitHub APK and F-Droid. Version 1.3.23 works correctly.

I'm on Android 13 (latest stable GrapheneOS)

**Comment by aicynide** [comment]
>GrapheneOS

Secure but not free & privacy-friendly

**Comment by This-Here-dat-dere** [comment]
I'm also experiencing the same. However, if you download the theme and then import then it works and you change the theme.

**Comment by khezuu** [comment]
crashes for me too, not sure how to import a theme also

**Comment by SWBGTOC** [comment]
> crashes for me too, not sure how to import a theme also

Download or copy one from
https://github.com/K1rakishou/KurobaEx-themes/tree/master/themes and in the app, click the three dots of the light or dark theme and import from file/clipboard

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/2e99bdc85d7652ef39fab2099982ea784a9d4e07

**Comment by This-Here-dat-dere** [comment]
Kudos to the developers! It's not crashing anymore while clicking on "More Themes". Thank you!

**Comment by aicynide** [comment]
@K1rakishou f-droid please

**Comment by K1rakishou** [comment]
@aicynide 
I don't update the f-droid version. They do it by themselves.
