### ISSUE TITLE
Yandex remote image search no longer works

### ISSUE THREAD

**Issue by XPEH69** [K1rakishou/Kuroba-Experimental#951]
Searx still works. Yandex just shows "End reached" no matter what I type
![Screenshot_2023-11-09-12-41-17-59_daf9683798e97ec54ec934cee23f7ded](https://github.com/K1rakishou/Kuroba-Experimental/assets/125198400/76c90603-0cae-4d5a-8374-77ffbf963fc5)

**Comment by fhtdtdj** [comment]
Same issue.

**Comment by XPEH69** [comment]
Nothing? Dimon only seems to update when posting is broken

**Comment by K1rakishou** [comment]
They changed how they serve the search results. Before the change it was all in a static html page. Now it loads stuff dynamically.

**Comment by XPEH69** [comment]
It's over

**Comment by XPEH69** [comment]
> They changed how they serve the search results. Before the change it was all in a static html page. Now it loads stuff dynamically.

Can you make the yandex option open the yandex image page in webview within kuroba so images can be searched and picked from there?

**Comment by fhtdtdj** [comment]
Getting "Bad status 502" with Searx now as well. Any chance of getting more alternative choices? Thanks.

**Comment by bqv** [comment]
#963

**Comment by K1rakishou** [comment]
Actually, there was a way. Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/02f430ed52313ca54c8bf95b6a86778d4ebcf2d9
