### ISSUE TITLE
Wrong image is showed when toggling off a filtered reply

### ISSUE THREAD

**Issue by ghost** [K1rakishou/Kuroba-Experimental#952]
Basically I have filters set in the app hiding some posts (not removing, they get minimized). But if I try to unhide them and then open the image they might contain, a completely different image from the thread is showed instead. Sometimes it's the immediately next or previous picture, sometimes it's the OP one. Version 1.3.27

**Comment by bqv** [comment]
same issue, 1.3.28.

my temp fix is to open the post in an archive and then the image works

**Comment by XPEH69** [comment]
I've had that on every version of KurobaEx since the beginning. I just assumed it was how it was supposed to work

**Comment by bqv** [comment]
@K1rakishou this one still plagues us. Should be relatively easy to solve, but I don't know where to start, any ideas?

**Comment by bqv** [comment]
@K1rakishou?

**Comment by K1rakishou** [comment]
I will take a look at it once they stop changing the captcha.

**Comment by bqv** [comment]
@K1rakishou still in the pipeline?

**Comment by K1rakishou** [comment]
Already fixed in latest beta.
