### ISSUE TITLE
"Checking if the site connection is secure" making it impossible to post, gets stuck in loop pre-CAPTCHA

### ISSUE THREAD

**Issue by frozenpandaman** [K1rakishou/Kuroba-Experimental#962]
I click on the arrow to make a post, the webview page appears and now (as of recently) displays "Checking if the site connection is secure"… once that completes, I get the "Successfully passed Cloudflare checks! You can now retry the last attempt" toast notification at the bottom which reveals the "Url cannot be opened without going through Cloudflare checks first" popup which was under the webview. Clicking refresh (or closing that popup and trying to click the arrow to post again) simply opens up the "Checking if the site connection is secure" webview again and again, in a loop – so I can never actually load the CAPTCHA or make a post.

v1.3.28 fb43f896ffc0

**Comment by bungholemaster** [comment]
I am also having this problem

**Comment by johng199** [comment]
same here, started happening after the last update
temporary fix is to force stop the app, clear cache and clear all cloudflare/captcha cookies, doesn't last for long before looping again though
doesn't seem to happen in 1.3.27

**Comment by CorpulentBrony** [comment]
Also having this issue, same version.

**Comment by frozenpandaman** [comment]
Seems to be working now so I'll close this.
