### ISSUE TITLE
4chan cloudflare started to go into loop today

### ISSUE THREAD

**Issue by Odysch** [K1rakishou/Kuroba-Experimental#976]
![Screenshot_2024-01-09-14-21-56-743-edit_com github k1rakishou chan](https://github.com/K1rakishou/Kuroba-Experimental/assets/89589129/753ce538-583c-40d6-bab4-f6d1adf35261)

**Comment by tidux** [comment]
I think this is related to the retirement of 4channel.org.  Updating the blue board API configs to go through 4chan.org again should fix it.

EDIT for clarity: posting on red boards still works for me, blue not.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/11b1ea6ac2e9c59b4caa33de5e49a2762a7f97b6
