### ISSUE TITLE
Captchas will not open, impossible to post

### ISSUE THREAD

**Issue by bungholemaster** [K1rakishou/Kuroba-Experimental#977]
![Screenshot_20240109_082625](https://github.com/K1rakishou/Kuroba-Experimental/assets/16147700/04ee686c-7cb8-4792-9c36-9bb499335640)
This error gets thrown up when I attempt to load the captcha after a cloudflare check.

**Comment by K1rakishou** [comment]
Yeah it seems like `4channel.org` shouldn't be used to get captcha anymore because it just redirects you to the main 4chan page. I will fix it by the weekends.

**Comment by tidux** [comment]
This also impacts posting, I could post on red boards but not blue boards (formerly 4channel) until my IP rotated and the endpoint issue prevented me from signing back in to my pass.  A global `s/4channel/4chan/` on the whole source tree might be necessary.

**Comment by xx1182** [comment]
> Yeah it seems like `4channel.org` shouldn't be used to get captcha anymore because it just redirects you to the main 4chan page. I will fix it by the weekends.

No, do it now or you have a undesiderable skin colour.

**Comment by bqv** [comment]
I have a monkeypatch that works, fwiw. I don't tend to do PRs, but i'll post the diff or an apk if anyone wants, until the weekend when Dmitry fixes it

**Comment by hiragashi** [comment]
> I have a monkeypatch that works, fwiw. I don't tend to do PRs, but i'll post the diff or an apk if anyone wants, until the weekend when Dmitry fixes it

Post it then my jogger

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/11b1ea6ac2e9c59b4caa33de5e49a2762a7f97b6
