### ISSUE TITLE
Can't reach captcha

### ISSUE THREAD

**Issue by Bomatoo** [K1rakishou/Kuroba-Experimental#979]
![Screenshot_20240110_011021](https://github.com/K1rakishou/Kuroba-Experimental/assets/37197718/dd9d712c-53b9-4226-8deb-b950b68e3c4c)

**Comment by ghost** [comment]
Also happens with me, build v1.3.28, from F-Droid.

**Comment by duanemoody** [comment]
Right after seeing the Cloudflare browser test for the first time in this app, yeah

**Comment by pixL404** [comment]
same issue as #977

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/11b1ea6ac2e9c59b4caa33de5e49a2762a7f97b6
