### ISSUE TITLE
can't post at all on mobile

### ISSUE THREAD

**Issue by ridgeblaze** [K1rakishou/Kuroba-Experimental#981]
![Screenshot_20240109_195555](https://github.com/K1rakishou/Kuroba-Experimental/assets/130591549/fe01a605-ace2-4297-9a4f-b67ba8996ec1)
I keep getting this error, I have no idea what's going on or how to fix it.

**Comment by magnus1500** [comment]
I have the same issue as well.

**Comment by xx1182** [comment]
Same.

Regards.

**Comment by pixL404** [comment]
same issue as #977

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/11b1ea6ac2e9c59b4caa33de5e49a2762a7f97b6
