### ISSUE TITLE
Captcha borked: returns an error on post

### ISSUE THREAD

**Issue by redpiller** [K1rakishou/Kuroba-Experimental#985]
Captcha doesn't even show up in the first place, instead, I'm getting an error Message: "Use JsonReader.setLenient(true) to accept malformed JSON at path $"

Using the currently available F-Droid version (1.3.28)

**Comment by K1rakishou** [comment]
Already fixed in v1.3.29
You are probably better off switching to the Github releases because the F-Droid version will be updated God knows when. It's not in my control.

**Comment by Fredolx** [comment]
> Already fixed in v1.3.29
> You are probably better off switching to the Github releases because the F-Droid version will be updated God knows when. It's not in my control.

I was always using the f droid version thinking it was updated frequently. Good to know. Maybe you could add a disclaimer on the README to use Obtainium for those who want to get the latest updates faster

**Comment by K1rakishou** [comment]
Already fixed.
