### ISSUE TITLE
Swiping add image button on reply form causes crash

### ISSUE THREAD

**Issue by pehdfms** [K1rakishou/Kuroba-Experimental#987]
`Exception: java.lang.NullPointerException
Message: Parameter specified as non-null is null: method com.github.k1rakishou.chan.features.reply.ReplyLayoutGestureListener.onScroll, parameter e1`

To replicate, simply tap and hold the add image button in the reply form, then swipe up or down before the popup appears. Consistent crash.

**Comment by pehdfms** [comment]
it appears to be a duplicate of #953 now that I'm looking at open issues, but after being bothered by this crash for a while I managed to figure out a consistent setup for it.

if it's possible to replicate with the added information then I would be very grateful for a fix, somehow I keep triggering it by accident. otherwise I guess I'll just live with it.

**Comment by pehdfms** [comment]
the code for the onScroll function assumes that MotionEvent e1 is not null, but the [docs](https://developer.android.com/reference/kotlin/android/view/GestureDetector.SimpleOnGestureListener#onscroll) state that null is a valid value for e1.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/e084fcc899377cc5bf3695869d0c63ad2b9db84d
