### ISSUE TITLE
Pressing the submit button with no solved captcha not showing captcha window

### ISSUE THREAD

**Issue by uenoshita** [K1rakishou/Kuroba-Experimental#991]
kuroba version: Kurobaex v1.3.30
1. Type message
2. press the submit button(no captcha)
captcha window is not shown, your message is gone and the next message that is fetched is tagged as your post.

**Comment by hiragashi** [comment]
Post log fgt or see previous closed PR

**Comment by uenoshita** [comment]
[logskuroba.txt](https://github.com/K1rakishou/Kuroba-Experimental/files/14019539/logskuroba.txt)
Is this good enough? Also the tagging seems random or maybe if I leave the app go back later the next post is tagged as mine.

**Comment by K1rakishou** [comment]
Long tap the send reply button and select "Solve captcha then post" option.

**Comment by uenoshita** [comment]
That fixed the captcha part although I'm not sure about tagging the next post part. Seems like a different bug related to the other mode.

**Comment by K1rakishou** [comment]
The second one is already fixed - https://github.com/K1rakishou/Kuroba-Experimental/commit/2ee0c2ca050b4bb8bce98f759fa424b3363a825f but the fix is not released yet.
