### ISSUE TITLE
Random images won't load

### ISSUE THREAD

**Issue by Fush4** [K1rakishou/Kuroba-Experimental#992]
Ramdom images on a thread won't load and show an error message (HttpCodeException status code = 416).
Seems to be random, but happens more often with black and white images.
Sometimes might be one image, sometimes it's half the images in a thread.
If I open the image in browser, it loads fine.
![Screenshot_20240121_124117](https://github.com/K1rakishou/Kuroba-Experimental/assets/157623381/a5069d4a-6359-443b-81c7-bbffea3b2bb8)

**Comment by K1rakishou** [comment]
Sites -> 4chan -> set "concurrent chunked file downloading" to 1

**Comment by Fush4** [comment]
Seems to be solved, thank you.
