### ISSUE TITLE
Post acknowledge check for 4chan on 2ch.hk

### ISSUE THREAD

**Issue by zms16** [K1rakishou/Kuroba-Experimental#995]
I get this error each time I post on 2ch.hk after updating to 1.3.31

> Setting Check4chanPostAcknowledged not found for site SD{2ch.hk}

Long pressing reply button while on 2ch.hk crashes the app.
Long pressing and unchecking the option while on 4chan does nothing for the issue.

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/Kuroba-Experimental/commit/c24edf9da856fd6a8b5d4695d18602980f43af42

See this https://github.com/K1rakishou/Kuroba-Experimental/issues/996 thread for a temporary solution until I push the update.
