### ISSUE TITLE
Post is flagged as discarded even when it wasn't discarded

### ISSUE THREAD

**Issue by rdloo** [K1rakishou/Kuroba-Experimental#999]
I always wait until at least 6 seconds pass to submit the captcha, and this causes my posts to almost always go through. Kuroba thinks my post has not gone through half the time.

![markup_1000010652](https://github.com/K1rakishou/Kuroba-Experimental/assets/96710687/15c981f6-4486-4cb3-81f3-131cc3ae1a94)

**Comment by K1rakishou** [comment]
Try this build - https://github.com/K1rakishou/Kuroba-Experimental/issues/996#issuecomment-1913098403
